package com.rehletshifaa.shared.persistence;

import jakarta.persistence.MappedSuperclass;
import jakarta.persistence.PostLoad;
import jakarta.persistence.PostPersist;
import jakarta.persistence.Transient;
import org.hibernate.Hibernate;
import org.springframework.data.domain.Persistable;

import java.util.Objects;

/**
 * Base for entities whose key is assigned by the application (a minted UUID, a subject, a catalogue key)
 * rather than generated by the database.
 *
 * <p>Spring Data otherwise treats an entity with a non-null key as existing and issues a SELECT before every
 * insert; {@link #isNew()} makes {@code save} a plain persist. Equality is by key, which is stable across the
 * entity's whole lifecycle because the key never changes.
 */
@MappedSuperclass
public abstract class PersistableEntity<ID> implements Persistable<ID> {
    @Transient
    private boolean persisted;

    @Override
    public boolean isNew() { return !persisted; }

    @PostLoad
    @PostPersist
    void markPersisted() { persisted = true; }

    @Override
    public final boolean equals(Object other) {
        if (this == other) return true;
        if (other == null || Hibernate.getClass(this) != Hibernate.getClass(other)) return false;
        ID id = getId();
        return id != null && id.equals(((PersistableEntity<?>) other).getId());
    }

    @Override
    public final int hashCode() { return Objects.hashCode(Hibernate.getClass(this)); }
}
