package com.rehletshifaa.journey.application;

import com.rehletshifaa.casemanagement.application.IntakeLifecycleService;
import com.rehletshifaa.journey.api.JourneyDtos.*;
import com.rehletshifaa.security.ActorContext;
import com.rehletshifaa.security.ActorRole;
import com.rehletshifaa.shared.api.ApiException;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.*;
import java.util.*;

import static com.rehletshifaa.shared.persistence.SqlValues.timestamp;

@Service
public class JourneyService {
    private final JdbcClient jdbc; private final ActorContext actors; private final IntakeLifecycleService intake; private final Clock clock;
    private static final Map<String,Set<String>> TRANSITIONS=Map.ofEntries(
        Map.entry("RECEIVED",Set.of("INTAKE_REVIEW","CANCELLED")),Map.entry("INTAKE_REVIEW",Set.of("INFORMATION_REQUIRED","READY_FOR_CONSULTANT","CANCELLED")),
        Map.entry("INFORMATION_REQUIRED",Set.of("INTAKE_REVIEW","READY_FOR_CONSULTANT","CANCELLED")),Map.entry("READY_FOR_CONSULTANT",Set.of("CONSULTANT_ASSIGNMENT_PENDING","CANCELLED")),
        Map.entry("CONSULTANT_ASSIGNMENT_PENDING",Set.of("CONSULTANT_REVIEW","READY_FOR_CONSULTANT","CANCELLED")),Map.entry("CONSULTANT_REVIEW",Set.of("INFORMATION_REQUIRED","CLINICAL_RECOMMENDATION_READY")),
        Map.entry("CLINICAL_RECOMMENDATION_READY",Set.of("PROPOSAL_PREPARATION")),Map.entry("PROPOSAL_PREPARATION",Set.of("PROPOSAL_INTERNAL_APPROVAL")),
        Map.entry("PROPOSAL_INTERNAL_APPROVAL",Set.of("PROPOSAL_READY","PATIENT_DECISION","REVISION_REQUESTED")),Map.entry("PROPOSAL_READY",Set.of("PATIENT_DECISION")),
        Map.entry("PATIENT_DECISION",Set.of("ACCEPTED","DECLINED","REVISION_REQUESTED","EXPIRED")),Map.entry("REVISION_REQUESTED",Set.of("PROPOSAL_PREPARATION")),
        Map.entry("ACCEPTED",Set.of("TRAVEL_COORDINATION")),Map.entry("TRAVEL_COORDINATION",Set.of("ARRIVAL_CONFIRMED","CANCELLED")),
        Map.entry("ARRIVAL_CONFIRMED",Set.of("TREATMENT_IN_PROGRESS")),Map.entry("TREATMENT_IN_PROGRESS",Set.of("DISCHARGED")),
        Map.entry("DISCHARGED",Set.of("FOLLOW_UP")),Map.entry("FOLLOW_UP",Set.of("CLOSED")));

    public JourneyService(JdbcClient jdbc,ActorContext actors,IntakeLifecycleService intake,Clock clock){this.jdbc=jdbc;this.actors=actors;this.intake=intake;this.clock=clock;}

    @Transactional public CaseView claimByNumber(ClaimCaseRequest request){UUID caseId=jdbc.sql("SELECT id FROM medical_cases WHERE case_number=?").param(request.caseNumber().toUpperCase(Locale.ROOT)).query(UUID.class).optional().orElseThrow(()->new ApiException(404,"CLAIM_NOT_FOUND","The case reference and verification code could not be verified"));return claim(caseId,new ClaimRequest(request.code()));}
    @Transactional public CaseView claimByReference(String reference,ClaimRequest request){try{return claim(UUID.fromString(reference),request);}catch(IllegalArgumentException ignored){return claimByNumber(new ClaimCaseRequest(reference.toUpperCase(Locale.ROOT),request.code()));}}

    @Transactional public CaseView claim(UUID caseId,ClaimRequest request){
        var actor=actors.require(ActorRole.PATIENT);Instant now=clock.instant();Claim challenge=jdbc.sql("SELECT id,patient_id,token_hash,expires_at,attempts,max_attempts,consumed_at,revoked_at FROM case_claim_challenges WHERE case_id=? ORDER BY created_at DESC LIMIT 1").param(caseId).query((rs,n)->new Claim(rs.getObject("id",UUID.class),rs.getObject("patient_id",UUID.class),rs.getString("token_hash"),instant(rs,"expires_at"),rs.getInt("attempts"),rs.getInt("max_attempts"),instantNullable(rs,"consumed_at"),instantNullable(rs,"revoked_at"))).optional().orElseThrow(()->new ApiException(404,"CLAIM_NOT_FOUND","A claim challenge was not found"));
        if(challenge.consumedAt()!=null||challenge.revokedAt()!=null||challenge.expiresAt().isBefore(now)||challenge.attempts()>=challenge.maxAttempts())throw new ApiException(410,"CLAIM_EXPIRED","The claim challenge is no longer valid");
        boolean matches=java.security.MessageDigest.isEqual(challenge.hash().getBytes(StandardCharsets.US_ASCII),intake.hash(request.code()).getBytes(StandardCharsets.US_ASCII));
        if(!matches){int attempts=challenge.attempts()+1;jdbc.sql("UPDATE case_claim_challenges SET attempts=?,revoked_at=CASE WHEN ?>=max_attempts THEN ? ELSE revoked_at END WHERE id=?").params(attempts,attempts,timestamp(now),challenge.id()).update();audit("CASE_CLAIM_FAILED",actor,caseId,"ClaimChallenge",challenge.id().toString(),"VERIFY","FAILURE","Invalid verification code");throw new ApiException(400,"CLAIM_CODE_INVALID","The verification code is invalid");}
        int bound=jdbc.sql("UPDATE patient_profiles SET external_subject=?,phone_verified_at=?,updated_at=?,version=version+1 WHERE id=? AND (external_subject IS NULL OR external_subject=?)").params(actor.subject(),timestamp(now),timestamp(now),challenge.patientId(),actor.subject()).update();
        if(bound!=1)throw new ApiException(409,"PATIENT_ALREADY_CLAIMED","This case belongs to another verified account");
        jdbc.sql("UPDATE case_claim_challenges SET attempts=attempts+1,consumed_at=? WHERE id=?").params(timestamp(now),challenge.id()).update();
        jdbc.sql("UPDATE medical_cases SET claimed_at=?,status=CASE WHEN status='RECEIVED' THEN 'INTAKE_REVIEW' ELSE status END,updated_at=?,version=version+1 WHERE id=?").params(timestamp(now),timestamp(now),caseId).update();
        audit("CASE_CLAIMED",actor,caseId,"MedicalCase",caseId.toString(),"CLAIM","SUCCESS",null);return caseView(caseId);
    }

    public List<CaseView> patientCases(){var actor=actors.require(ActorRole.PATIENT,ActorRole.PATIENT_REPRESENTATIVE);return jdbc.sql("SELECT c.* FROM medical_cases c JOIN patient_profiles p ON p.id=c.patient_id WHERE p.external_subject=? OR EXISTS(SELECT 1 FROM patient_representatives r WHERE r.patient_id=p.id AND r.representative_subject=? AND r.revoked_at IS NULL AND (r.expires_at IS NULL OR r.expires_at>?)) ORDER BY c.updated_at DESC").params(actor.subject(),actor.subject(),timestamp(clock.instant())).query((rs,n)->mapCase(rs)).list();}
    public List<CaseView> coordinatorQueue(){var actor=actors.require(ActorRole.COORDINATOR,ActorRole.COORDINATOR_LEAD);boolean lead=actor.has(ActorRole.COORDINATOR_LEAD);return jdbc.sql("SELECT c.* FROM medical_cases c WHERE c.status NOT IN ('DRAFT','CLOSED','CANCELLED') ORDER BY c.updated_at ASC").query((rs,n)->{CaseView view=mapCase(rs);boolean owned=actor.subject().equals(view.coordinatorSubject());return lead||owned?view:new CaseView(view.id(),view.caseNumber(),view.status(),"Restricted until claimed",view.country(),view.preferredLanguage(),view.createdAt(),view.updatedAt(),view.version(),view.coordinatorSubject(),view.doctorSubject());}).list();}
    public List<CaseView> assignedCases(ActorRole role){var actor=actors.require(role);return jdbc.sql("SELECT c.* FROM medical_cases c JOIN case_assignments a ON a.case_id=c.id WHERE a.assignee_subject=? AND a.assignee_role=? AND a.status IN ('PENDING','ACTIVE') ORDER BY c.updated_at ASC").params(actor.subject(),role.name()).query((rs,n)->mapCase(rs)).list();}
    public List<VerifiedDoctorView> verifiedDoctors(){actors.require(ActorRole.COORDINATOR,ActorRole.COORDINATOR_LEAD);return jdbc.sql("SELECT external_subject,display_name,specialty,subspecialty,availability_status,care_category FROM practitioner_profiles WHERE credentialing_status='VERIFIED' AND practitioner_type='CONSULTANT' AND external_subject IS NOT NULL ORDER BY display_name").query((rs,n)->new VerifiedDoctorView(rs.getString("external_subject"),rs.getString("display_name"),rs.getString("specialty"),rs.getString("subspecialty"),rs.getString("availability_status"),rs.getString("care_category"))).list();}
    public List<CareCategoryView> careCategories(){actors.require(ActorRole.COORDINATOR,ActorRole.COORDINATOR_LEAD);return jdbc.sql("SELECT slug,name_en,name_ar FROM care_categories ORDER BY sort_order,name_en").query((rs,n)->new CareCategoryView(rs.getString("slug"),rs.getString("name_en"),rs.getString("name_ar"))).list();}
    public void assertCanRead(UUID caseId){authorizeRead(caseId,actors.current());}

    public CaseWorkspace workspace(UUID caseId){var actor=actors.current();authorizeRead(caseId,actor);CaseView summary=caseView(caseId);List<TimelineEvent>timeline=jdbc.sql("SELECT 'STATUS' type,to_status label,created_at,to_status status FROM case_status_history WHERE case_id=? ORDER BY created_at").param(caseId).query((rs,n)->new TimelineEvent(rs.getString("type"),rs.getString("label"),instant(rs,"created_at"),rs.getString("status"))).list();List<TaskView>tasks=jdbc.sql("SELECT * FROM case_tasks WHERE case_id=? ORDER BY created_at").param(caseId).query((rs,n)->new TaskView(rs.getObject("id",UUID.class),rs.getString("task_type"),rs.getString("title"),rs.getString("description"),rs.getString("owner_role"),rs.getString("priority"),rs.getString("status"),rs.getBoolean("blocking"),instantNullable(rs,"due_at"),rs.getLong("version"))).list();List<MessageView>messages=jdbc.sql("SELECT * FROM case_messages WHERE case_id=? AND (?=FALSE OR internal_only=FALSE) ORDER BY created_at").params(caseId,actor.has(ActorRole.PATIENT)||actor.has(ActorRole.PATIENT_REPRESENTATIVE)).query((rs,n)->new MessageView(rs.getObject("id",UUID.class),rs.getString("thread_type"),rs.getString("sender_role"),rs.getString("body"),rs.getString("language"),rs.getBoolean("internal_only"),instant(rs,"created_at"))).list();List<AssignmentView>assignments=jdbc.sql("SELECT id,assignee_subject,assignee_role,assignment_type,status,assigned_at,version FROM case_assignments WHERE case_id=? AND status IN ('PENDING','ACTIVE') ORDER BY assigned_at").param(caseId).query((rs,n)->new AssignmentView(rs.getObject("id",UUID.class),rs.getString("assignee_subject"),rs.getString("assignee_role"),rs.getString("assignment_type"),rs.getString("status"),instant(rs,"assigned_at"),rs.getLong("version"))).list();List<ClinicalReviewView>reviews=jdbc.sql("SELECT id,version_number,status,suitability,recommended_treatment,risks_and_limitations,created_at FROM clinical_review_versions WHERE case_id=? ORDER BY version_number DESC").param(caseId).query((rs,n)->new ClinicalReviewView(rs.getObject("id",UUID.class),rs.getInt("version_number"),rs.getString("status"),rs.getString("suitability"),rs.getString("recommended_treatment"),rs.getString("risks_and_limitations"),instant(rs,"created_at"))).list();if(actor.has(ActorRole.PATIENT)||actor.has(ActorRole.PATIENT_REPRESENTATIVE))reviews=reviews.stream().filter(r->"APPROVED".equals(r.status())).toList();return new CaseWorkspace(summary,timeline,tasks,messages,assignments,reviews,latestProposal(caseId,actor));}

    @Transactional public CaseView transition(UUID caseId,TransitionRequest request){var actor=actors.require(ActorRole.COORDINATOR,ActorRole.COORDINATOR_LEAD,ActorRole.SYSTEM_ADMIN);authorizeWrite(caseId,actor);requireCoordinatorOwnership(caseId,actor);transitionInternal(caseId,request.targetStatus(),request.reason(),request.expectedVersion(),actor);return caseView(caseId);}

    @Transactional public IdResponse claimCoordinatorCase(UUID caseId,String pod){var actor=actors.require(ActorRole.COORDINATOR,ActorRole.COORDINATOR_LEAD);jdbc.sql("SELECT id FROM medical_cases WHERE id=? FOR UPDATE").param(caseId).query(UUID.class).optional().orElseThrow(()->new ApiException(404,"CASE_NOT_FOUND","Case was not found"));Integer active=jdbc.sql("SELECT count(*) FROM case_assignments WHERE case_id=? AND assignee_role='COORDINATOR' AND assignment_type='PRIMARY' AND status='ACTIVE'").param(caseId).query(Integer.class).single();if(active!=null&&active>0)throw new ApiException(409,"CASE_ALREADY_ASSIGNED","The case already has a primary coordinator");UUID id=UUID.randomUUID();Instant now=clock.instant();jdbc.sql("INSERT INTO case_assignments(id,case_id,assignee_subject,assignee_role,assignment_type,pod,status,reason,assigned_by,assigned_at,accepted_at,version) VALUES(?,?,?,?,?,?,?,?,?,?,?,0)").params(id,caseId,actor.subject(),"COORDINATOR","PRIMARY",pod,"ACTIVE","Coordinator claimed intake queue case",actor.subject(),timestamp(now),timestamp(now)).update();transitionWithoutVersion(caseId,"INTAKE_REVIEW","Coordinator took ownership",actor);audit("CASE_COORDINATOR_CLAIMED",actor,caseId,"CaseAssignment",id.toString(),"ASSIGN","SUCCESS",null);return new IdResponse(id,"ACTIVE");}

    @Transactional public IdResponse assign(UUID caseId,AssignmentRequest request){var actor=actors.require(ActorRole.COORDINATOR,ActorRole.COORDINATOR_LEAD,ActorRole.SYSTEM_ADMIN);authorizeWrite(caseId,actor);requireCoordinatorOwnership(caseId,actor);ActorRole role=parseRole(request.assigneeRole());if(role==ActorRole.DOCTOR){Integer verified=jdbc.sql("SELECT count(*) FROM practitioner_profiles WHERE external_subject=? AND credentialing_status='VERIFIED' AND practitioner_type='CONSULTANT'").param(request.assigneeSubject()).query(Integer.class).single();if(verified==null||verified==0)throw new ApiException(409,"DOCTOR_NOT_VERIFIED","Only a verified consultant can receive a case assignment");String currentStatus=state(caseId).status();if("INTAKE_REVIEW".equals(currentStatus)||"INFORMATION_REQUIRED".equals(currentStatus))transitionWithoutVersion(caseId,"READY_FOR_CONSULTANT","Ready for consultant assignment",actor);String readyStatus=state(caseId).status();if(!"READY_FOR_CONSULTANT".equals(readyStatus)&&!"CONSULTANT_ASSIGNMENT_PENDING".equals(readyStatus))throw new ApiException(409,"CASE_NOT_READY_FOR_CONSULTANT","The case cannot be assigned to a consultant from its current status");}Instant now=clock.instant();UUID id=UUID.randomUUID();jdbc.sql("UPDATE case_assignments SET status='ENDED',ended_at=? WHERE case_id=? AND assignee_role=? AND assignment_type=? AND status IN ('PENDING','ACTIVE')").params(timestamp(now),caseId,role.name(),request.assignmentType()).update();String status=role==ActorRole.DOCTOR?"PENDING":"ACTIVE";jdbc.sql("INSERT INTO case_assignments(id,case_id,assignee_subject,assignee_role,assignment_type,pod,status,reason,assigned_by,assigned_at,accepted_at,version) VALUES(?,?,?,?,?,?,?,?,?,?,?,0)").params(id,caseId,request.assigneeSubject(),role.name(),request.assignmentType(),request.pod(),status,request.reason(),actor.subject(),timestamp(now),"ACTIVE".equals(status)?timestamp(now):null).update();if(role==ActorRole.DOCTOR)transitionWithoutVersion(caseId,"CONSULTANT_ASSIGNMENT_PENDING","Verified doctor assigned",actor);audit("CASE_ASSIGNED",actor,caseId,"CaseAssignment",id.toString(),"ASSIGN","SUCCESS",request.reason());return new IdResponse(id,status);}

    @Transactional public IdResponse acceptDoctorAssignment(UUID caseId,UUID assignmentId,boolean accept){var actor=actors.require(ActorRole.DOCTOR);int changed=jdbc.sql("UPDATE case_assignments SET status=?,accepted_at=?,ended_at=? WHERE id=? AND case_id=? AND assignee_subject=? AND assignee_role='DOCTOR' AND status='PENDING'").params(accept?"ACTIVE":"DECLINED",accept?timestamp(clock.instant()):null,accept?null:timestamp(clock.instant()),assignmentId,caseId,actor.subject()).update();if(changed!=1)throw new ApiException(409,"ASSIGNMENT_NOT_PENDING","The assignment is not available for this doctor");if(accept)transitionWithoutVersion(caseId,"CONSULTANT_REVIEW","Doctor accepted assignment",actor);audit("DOCTOR_ASSIGNMENT_DECISION",actor,caseId,"CaseAssignment",assignmentId.toString(),accept?"ACCEPT":"DECLINE","SUCCESS",null);return new IdResponse(assignmentId,accept?"ACTIVE":"DECLINED");}

    @Transactional public IdResponse message(UUID caseId,MessageRequest request){var actor=actors.current();authorizeRead(caseId,actor);boolean patient=actor.has(ActorRole.PATIENT)||actor.has(ActorRole.PATIENT_REPRESENTATIVE);String thread=patient?"PATIENT_COORDINATOR":request.threadType();boolean internal=patient?false:request.internalOnly();if(actor.has(ActorRole.DOCTOR)&&!"COORDINATOR_DOCTOR".equals(thread))throw new ApiException(403,"THREAD_ACCESS_DENIED","Doctors may use only the coordinator-doctor thread");UUID id=UUID.randomUUID();jdbc.sql("INSERT INTO case_messages(id,case_id,thread_type,sender_subject,sender_role,body,language,internal_only,created_at) VALUES(?,?,?,?,?,?,?,?,?)").params(id,caseId,thread,actor.subject(),actor.primaryRole(),request.body().trim(),request.language()==null?"en":request.language(),internal,timestamp(clock.instant())).update();audit("CASE_MESSAGE_CREATED",actor,caseId,"CaseMessage",id.toString(),"CREATE","SUCCESS",null);return new IdResponse(id,"SENT");}

    @Transactional public IdResponse task(UUID caseId,TaskRequest request){var actor=actors.require(ActorRole.COORDINATOR,ActorRole.COORDINATOR_LEAD,ActorRole.DOCTOR,ActorRole.OPERATIONS);authorizeWrite(caseId,actor);requireCoordinatorOwnership(caseId,actor);UUID id=UUID.randomUUID();Instant now=clock.instant();jdbc.sql("INSERT INTO case_tasks(id,case_id,task_type,title,description,owner_subject,owner_role,priority,status,blocking,due_at,created_by,created_at,updated_at,version) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,0)").params(id,caseId,request.taskType(),request.title(),request.description(),request.ownerSubject(),request.ownerRole(),request.priority(),"OPEN",request.blocking(),timestamp(request.dueAt()),actor.subject(),timestamp(now),timestamp(now)).update();audit("CASE_TASK_CREATED",actor,caseId,"CaseTask",id.toString(),"CREATE","SUCCESS",null);return new IdResponse(id,"OPEN");}
    @Transactional public IdResponse completeTask(UUID caseId,UUID taskId,CompleteTaskRequest request){var actor=actors.current();authorizeWrite(caseId,actor);int changed=jdbc.sql("UPDATE case_tasks SET status='COMPLETED',completed_at=?,completion_evidence=?,updated_at=?,version=version+1 WHERE id=? AND case_id=? AND version=? AND status IN ('OPEN','IN_PROGRESS') AND (owner_subject IS NULL OR owner_subject=? OR ?=TRUE)").params(timestamp(clock.instant()),request.evidence(),timestamp(clock.instant()),taskId,caseId,request.expectedVersion(),actor.subject(),actor.has(ActorRole.COORDINATOR_LEAD)||actor.has(ActorRole.SYSTEM_ADMIN)).update();if(changed!=1)throw new ApiException(409,"TASK_CONFLICT","The task changed or is not assigned to this account");audit("CASE_TASK_COMPLETED",actor,caseId,"CaseTask",taskId.toString(),"COMPLETE","SUCCESS",null);return new IdResponse(taskId,"COMPLETED");}

    @Transactional public IdResponse createPractitioner(PractitionerRequest request){var actor=actors.require(ActorRole.CREDENTIALING_ADMIN,ActorRole.SYSTEM_ADMIN);UUID id=UUID.randomUUID();Instant now=clock.instant();jdbc.sql("INSERT INTO practitioner_profiles(id,external_subject,legal_name,display_name,registration_number,specialty,subspecialty,qualifications,appointments,hospital_privileges,languages,approved_procedures,indemnity_reference,contract_status,availability_status,expected_review_hours,credentialing_status,created_at,updated_at,version) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,0)").params(id,request.externalSubject(),request.legalName(),request.displayName(),request.registrationNumber(),request.specialty(),request.subspecialty(),request.qualifications(),request.appointments(),request.hospitalPrivileges(),request.languages(),request.approvedProcedures(),request.indemnityReference(),request.contractStatus(),request.availabilityStatus(),request.expectedReviewHours(),"UNDER_REVIEW",timestamp(now),timestamp(now)).update();audit("PRACTITIONER_CREATED",actor,null,"Practitioner",id.toString(),"CREATE","SUCCESS",null);return new IdResponse(id,"UNDER_REVIEW");}
    @Transactional public IdResponse addCredential(UUID practitionerId,CredentialRequest request){var actor=actors.require(ActorRole.CREDENTIALING_ADMIN,ActorRole.SYSTEM_ADMIN);UUID id=UUID.randomUUID();jdbc.sql("INSERT INTO practitioner_credentials(id,practitioner_id,credential_type,reference_number,source,evidence_document_id,issued_at,expires_at,status,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)").params(id,practitionerId,request.credentialType(),request.referenceNumber(),request.source(),request.evidenceDocumentId(),timestamp(request.issuedAt()),timestamp(request.expiresAt()),"UNDER_REVIEW",timestamp(clock.instant())).update();audit("PRACTITIONER_CREDENTIAL_ADDED",actor,null,"PractitionerCredential",id.toString(),"CREATE","SUCCESS",null);return new IdResponse(id,"UNDER_REVIEW");}
    @Transactional public IdResponse verifyPractitioner(UUID practitionerId,boolean approved,String reason){var actor=actors.require(ActorRole.CREDENTIALING_ADMIN,ActorRole.SYSTEM_ADMIN);String status=approved?"VERIFIED":"REJECTED";jdbc.sql("UPDATE practitioner_profiles SET credentialing_status=?,suspension_reason=?,updated_at=?,version=version+1 WHERE id=?").params(status,approved?null:reason,timestamp(clock.instant()),practitionerId).update();jdbc.sql("UPDATE practitioner_credentials SET status=?,verified_at=?,verified_by=? WHERE practitioner_id=? AND status='UNDER_REVIEW'").params(status,timestamp(clock.instant()),actor.subject(),practitionerId).update();audit("PRACTITIONER_VERIFIED",actor,null,"Practitioner",practitionerId.toString(),approved?"APPROVE":"REJECT","SUCCESS",reason);return new IdResponse(practitionerId,status);}

    @Transactional public IdResponse saveClinicalReview(UUID caseId,ClinicalReviewRequest request){var actor=actors.require(ActorRole.DOCTOR);authorizeWrite(caseId,actor);UUID practitionerId=practitionerId(actor.subject());Integer version=jdbc.sql("SELECT COALESCE(MAX(version_number),0)+1 FROM clinical_review_versions WHERE case_id=?").param(caseId).query(Integer.class).single();UUID id=UUID.randomUUID();jdbc.sql("UPDATE clinical_review_versions SET status='SUPERSEDED' WHERE case_id=? AND status='DRAFT'").param(caseId).update();jdbc.sql("INSERT INTO clinical_review_versions(id,case_id,practitioner_id,version_number,status,case_summary,suitability,missing_information,recommended_investigations,recommended_treatment,alternatives,risks_and_limitations,expected_sequence,expected_duration,follow_up_recommendation,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").params(id,caseId,practitionerId,version,"DRAFT",request.caseSummary(),request.suitability(),request.missingInformation(),request.recommendedInvestigations(),request.recommendedTreatment(),request.alternatives(),request.risksAndLimitations(),request.expectedSequence(),request.expectedDuration(),request.followUpRecommendation(),actor.subject(),timestamp(clock.instant())).update();audit("CLINICAL_REVIEW_VERSION_CREATED",actor,caseId,"ClinicalReview",id.toString(),"CREATE","SUCCESS",null);return new IdResponse(id,"DRAFT");}
    @Transactional public IdResponse approveClinicalReview(UUID caseId,UUID reviewId){var actor=actors.requireRecentAuthentication(Duration.ofMinutes(10),ActorRole.DOCTOR);authorizeWrite(caseId,actor);int changed=jdbc.sql("UPDATE clinical_review_versions SET status='APPROVED',approved_by=?,approved_at=? WHERE id=? AND case_id=? AND practitioner_id=? AND status='DRAFT'").params(actor.subject(),timestamp(clock.instant()),reviewId,caseId,practitionerId(actor.subject())).update();if(changed!=1)throw new ApiException(409,"REVIEW_NOT_APPROVABLE","The review is not an approvable draft");jdbc.sql("UPDATE clinical_review_versions SET status='SUPERSEDED' WHERE case_id=? AND id<>? AND status='APPROVED'").params(caseId,reviewId).update();transitionWithoutVersion(caseId,"CLINICAL_RECOMMENDATION_READY","Clinical recommendation approved",actor);audit("CLINICAL_REVIEW_APPROVED",actor,caseId,"ClinicalReview",reviewId.toString(),"APPROVE","SUCCESS",null);return new IdResponse(reviewId,"APPROVED");}

    @Transactional public ProposalView createProposal(UUID caseId,ProposalDraftRequest request){var actor=actors.require(ActorRole.COORDINATOR,ActorRole.COORDINATOR_LEAD);authorizeWrite(caseId,actor);requireCoordinatorOwnership(caseId,actor);Integer review=jdbc.sql("SELECT count(*) FROM clinical_review_versions WHERE id=? AND case_id=? AND status='APPROVED'").params(request.clinicalReviewId(),caseId).query(Integer.class).single();if(review==null||review==0)throw new ApiException(409,"CLINICAL_APPROVAL_REQUIRED","An approved clinical review is required");UUID proposalId=jdbc.sql("SELECT id FROM proposals WHERE case_id=?").param(caseId).query(UUID.class).optional().orElseGet(()->{UUID id=UUID.randomUUID();Instant now=clock.instant();jdbc.sql("INSERT INTO proposals(id,case_id,current_version,created_at,updated_at,version) VALUES(?,?,0,?,?,0)").params(id,caseId,timestamp(now),timestamp(now)).update();return id;});Integer version=jdbc.sql("SELECT current_version+1 FROM proposals WHERE id=?").param(proposalId).query(Integer.class).single();UUID versionId=UUID.randomUUID();Instant now=clock.instant();jdbc.sql("UPDATE proposal_versions SET status='SUPERSEDED',superseded_at=? WHERE proposal_id=? AND status IN ('RELEASED','VIEWED')").params(timestamp(now),proposalId).update();jdbc.sql("INSERT INTO proposal_versions(id,proposal_id,version_number,status,language,clinical_review_id,operational_plan,currency,included_services,excluded_services,payment_terms,refund_terms,disclaimers,valid_until,clinical_approved_by,clinical_approved_at,created_by,created_at) SELECT ?,?,?,?, ?,?,?,?,?,?,?,?,?,?,approved_by,approved_at,?,? FROM clinical_review_versions WHERE id=?").params(versionId,proposalId,version,"CLINICALLY_APPROVED",request.language()==null?"en":request.language(),request.clinicalReviewId(),request.operationalPlan(),request.currency(),request.includedServices(),request.excludedServices(),request.paymentTerms(),request.refundTerms(),request.disclaimers(),timestamp(request.validUntil()),actor.subject(),timestamp(now),request.clinicalReviewId()).update();for(ProposalItemRequest item:request.items())jdbc.sql("INSERT INTO proposal_items(id,proposal_version_id,category,description,quantity,unit_price,optional,sort_order) VALUES(?,?,?,?,?,?,?,?)").params(UUID.randomUUID(),versionId,item.category(),item.description(),item.quantity(),item.unitPrice(),item.optional(),item.sortOrder()==null?0:item.sortOrder()).update();jdbc.sql("UPDATE proposals SET current_version=?,updated_at=?,version=version+1 WHERE id=?").params(version,timestamp(now),proposalId).update();transitionWithoutVersion(caseId,"PROPOSAL_PREPARATION","Proposal draft created",actor);audit("PROPOSAL_VERSION_CREATED",actor,caseId,"ProposalVersion",versionId.toString(),"CREATE","SUCCESS",null);return proposal(versionId);}
    @Transactional public ProposalView completeOperations(UUID caseId,UUID versionId,String plan){var actor=actors.require(ActorRole.OPERATIONS);authorizeWrite(caseId,actor);ensureProposalBelongs(caseId,versionId);int changed=jdbc.sql("UPDATE proposal_versions SET operational_plan=?,status='OPERATIONS_COMPLETED',operations_completed_by=?,operations_completed_at=? WHERE id=? AND status='CLINICALLY_APPROVED'").params(plan,actor.subject(),timestamp(clock.instant()),versionId).update();if(changed!=1)throw new ApiException(409,"PROPOSAL_STATE_CONFLICT","Proposal is not ready for operations");audit("PROPOSAL_OPERATIONS_COMPLETED",actor,caseId,"ProposalVersion",versionId.toString(),"COMPLETE_OPERATIONS","SUCCESS",null);return proposal(versionId);}
    @Transactional public ProposalView approveFinance(UUID caseId,UUID versionId){var actor=actors.requireRecentAuthentication(Duration.ofMinutes(10),ActorRole.FINANCE);authorizeWrite(caseId,actor);ensureProposalBelongs(caseId,versionId);int changed=jdbc.sql("UPDATE proposal_versions SET status='FINANCE_APPROVED',finance_approved_by=?,finance_approved_at=? WHERE id=? AND status='OPERATIONS_COMPLETED' AND currency IS NOT NULL").params(actor.subject(),timestamp(clock.instant()),versionId).update();if(changed!=1)throw new ApiException(409,"PROPOSAL_STATE_CONFLICT","Proposal is not ready for finance approval");transitionWithoutVersion(caseId,"PROPOSAL_INTERNAL_APPROVAL","Commercial proposal approved",actor);audit("PROPOSAL_FINANCE_APPROVED",actor,caseId,"ProposalVersion",versionId.toString(),"APPROVE_FINANCE","SUCCESS",null);return proposal(versionId);}
    @Transactional public ProposalView releaseProposal(UUID caseId,UUID versionId){var actor=actors.require(ActorRole.COORDINATOR,ActorRole.COORDINATOR_LEAD);authorizeWrite(caseId,actor);requireCoordinatorOwnership(caseId,actor);ensureProposalBelongs(caseId,versionId);ProposalView view=proposal(versionId);if(!"FINANCE_APPROVED".equals(view.status()))throw new ApiException(409,"PROPOSAL_STATE_CONFLICT","Proposal is not ready for release");String html=renderProposal(view);int changed=jdbc.sql("UPDATE proposal_versions SET status='RELEASED',released_by=?,released_at=?,html_snapshot=? WHERE id=? AND status='FINANCE_APPROVED'").params(actor.subject(),timestamp(clock.instant()),html,versionId).update();if(changed!=1)throw new ApiException(409,"PROPOSAL_STATE_CONFLICT","Proposal changed before release");transitionWithoutVersion(caseId,"PATIENT_DECISION","Proposal released to patient",actor);audit("PROPOSAL_RELEASED",actor,caseId,"ProposalVersion",versionId.toString(),"RELEASE","SUCCESS",null);return proposal(versionId);}
    @Transactional public ProposalView decideProposal(UUID caseId,UUID versionId,ProposalDecisionRequest request){var actor=actors.requireRecentAuthentication(Duration.ofMinutes(10),ActorRole.PATIENT);authorizeRead(caseId,actor);ensureProposalBelongs(caseId,versionId);ProposalView view=proposal(versionId);if(!Set.of("RELEASED","VIEWED").contains(view.status()))throw new ApiException(409,"PROPOSAL_NOT_DECIDABLE","This proposal version can no longer be decided");if(view.validUntil()!=null&&view.validUntil().isBefore(clock.instant())){jdbc.sql("UPDATE proposal_versions SET status='EXPIRED' WHERE id=?").param(versionId).update();throw new ApiException(410,"PROPOSAL_EXPIRED","This proposal has expired");}UUID id=UUID.randomUUID();jdbc.sql("INSERT INTO proposal_decisions(id,proposal_version_id,patient_subject,decision,selected_optional_item_ids,comment,reauthenticated_at,created_at) VALUES(?,?,?,?,?,?,?,?)").params(id,versionId,actor.subject(),request.decision(),request.selectedOptionalItemIds()==null?null:request.selectedOptionalItemIds().toString(),request.comment(),timestamp(actor.authenticatedAt()),timestamp(clock.instant())).update();jdbc.sql("UPDATE proposal_versions SET status=? WHERE id=?").params(request.decision(),versionId).update();String target=switch(request.decision()){case "ACCEPTED"->"ACCEPTED";case "DECLINED"->"DECLINED";default->"REVISION_REQUESTED";};transitionWithoutVersion(caseId,target,"Patient proposal decision",actor);audit("PROPOSAL_DECIDED",actor,caseId,"ProposalVersion",versionId.toString(),request.decision(),"SUCCESS",null);return proposal(versionId);}

    @Transactional public IdResponse upsertTravel(UUID caseId,TravelPlanRequest request){var actor=actors.require(ActorRole.OPERATIONS);authorizeWrite(caseId,actor);UUID id=jdbc.sql("SELECT id FROM travel_plans WHERE case_id=?").param(caseId).query(UUID.class).optional().orElse(UUID.randomUUID());int updated=jdbc.sql("UPDATE travel_plans SET planned_arrival=?,confirmed_arrival=?,visa_status=?,flight_details=?,airport_reception=?,accommodation=?,local_transport=?,companion_details=?,facility=?,exceptions=?,responsible_subject=?,status=?,updated_at=?,version=version+1 WHERE id=?").params(timestamp(request.plannedArrival()),timestamp(request.confirmedArrival()),request.visaStatus(),request.flightDetails(),request.airportReception(),request.accommodation(),request.localTransport(),request.companionDetails(),request.facility(),request.exceptions(),actor.subject(),request.status(),timestamp(clock.instant()),id).update();if(updated==0)jdbc.sql("INSERT INTO travel_plans(id,case_id,planned_arrival,confirmed_arrival,visa_status,flight_details,airport_reception,accommodation,local_transport,companion_details,facility,exceptions,responsible_subject,status,updated_at,version) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,0)").params(id,caseId,timestamp(request.plannedArrival()),timestamp(request.confirmedArrival()),request.visaStatus(),request.flightDetails(),request.airportReception(),request.accommodation(),request.localTransport(),request.companionDetails(),request.facility(),request.exceptions(),actor.subject(),request.status(),timestamp(clock.instant())).update();transitionWithoutVersion(caseId,"TRAVEL_COORDINATION","Travel plan updated",actor);if(request.confirmedArrival()!=null)transitionWithoutVersion(caseId,"ARRIVAL_CONFIRMED","Arrival confirmed",actor);audit("TRAVEL_PLAN_UPDATED",actor,caseId,"TravelPlan",id.toString(),"UPSERT","SUCCESS",null);return new IdResponse(id,request.status());}
    @Transactional public IdResponse treatment(UUID caseId,TreatmentRequest request){var actor=actors.require(ActorRole.DOCTOR);authorizeWrite(caseId,actor);if(request.dischargeDocumentId()!=null){Integer document=jdbc.sql("SELECT count(*) FROM medical_documents WHERE id=? AND case_id=? AND status='CLEAN'").params(request.dischargeDocumentId(),caseId).query(Integer.class).single();if(document==null||document==0)throw new ApiException(409,"INVALID_DISCHARGE_DOCUMENT","The discharge document must be a clean document from this case");}UUID id=UUID.randomUUID();Instant now=clock.instant();jdbc.sql("INSERT INTO treatment_episodes(id,case_id,facility,practitioner_id,start_at,end_at,status,planned_procedures,actual_procedures,milestones,complications,discharge_ready,discharge_document_id,created_at,updated_at,version) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,0)").params(id,caseId,request.facility(),request.practitionerId()==null?practitionerId(actor.subject()):request.practitionerId(),timestamp(request.startAt()),timestamp(request.endAt()),request.status(),request.plannedProcedures(),request.actualProcedures(),request.milestones(),request.complications(),request.dischargeReady(),request.dischargeDocumentId(),timestamp(now),timestamp(now)).update();transitionWithoutVersion(caseId,request.endAt()==null?"TREATMENT_IN_PROGRESS":"DISCHARGED","Treatment episode updated",actor);audit("TREATMENT_EPISODE_CREATED",actor,caseId,"TreatmentEpisode",id.toString(),"CREATE","SUCCESS",null);return new IdResponse(id,request.status());}
    @Transactional public IdResponse followUp(UUID caseId,FollowUpRequest request){var actor=actors.require(ActorRole.DOCTOR);authorizeWrite(caseId,actor);if(request.treatmentEpisodeId()!=null){Integer episode=jdbc.sql("SELECT count(*) FROM treatment_episodes WHERE id=? AND case_id=?").params(request.treatmentEpisodeId(),caseId).query(Integer.class).single();if(episode==null||episode==0)throw new ApiException(409,"INVALID_TREATMENT_EPISODE","The treatment episode does not belong to this case");}UUID id=UUID.randomUUID();Instant now=clock.instant();jdbc.sql("INSERT INTO follow_up_plans(id,case_id,treatment_episode_id,practitioner_id,due_at,mode,required_tests,instructions,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)").params(id,caseId,request.treatmentEpisodeId(),request.practitionerId()==null?practitionerId(actor.subject()):request.practitionerId(),timestamp(request.dueAt()),request.mode(),request.requiredTests(),request.instructions(),"PLANNED",timestamp(now),timestamp(now)).update();transitionWithoutVersion(caseId,"FOLLOW_UP","Follow-up plan created",actor);audit("FOLLOW_UP_CREATED",actor,caseId,"FollowUpPlan",id.toString(),"CREATE","SUCCESS",null);return new IdResponse(id,"PLANNED");}

    private CaseView caseView(UUID caseId){return jdbc.sql("SELECT * FROM medical_cases WHERE id=?").param(caseId).query((rs,n)->mapCase(rs)).optional().orElseThrow(()->new ApiException(404,"CASE_NOT_FOUND","Case was not found"));}
    private CaseView mapCase(ResultSet rs)throws SQLException{UUID id=rs.getObject("id",UUID.class);String coordinator=assignment(id,"COORDINATOR");String doctor=assignment(id,"DOCTOR");return new CaseView(id,rs.getString("case_number"),rs.getString("status"),rs.getString("full_name"),rs.getString("country"),rs.getString("preferred_language"),instant(rs,"created_at"),instant(rs,"updated_at"),rs.getLong("version"),coordinator,doctor);}
    private String assignment(UUID caseId,String role){return jdbc.sql("SELECT assignee_subject FROM case_assignments WHERE case_id=? AND assignee_role=? AND status='ACTIVE' ORDER BY assigned_at DESC LIMIT 1").params(caseId,role).query(String.class).optional().orElse(null);}
    private void authorizeRead(UUID caseId,ActorContext.Actor actor){if(actor.has(ActorRole.SYSTEM_ADMIN)||actor.has(ActorRole.AUDITOR)||actor.has(ActorRole.COORDINATOR_LEAD)||actor.has(ActorRole.COORDINATOR))return;if(actor.has(ActorRole.PATIENT)||actor.has(ActorRole.PATIENT_REPRESENTATIVE)){Integer count=jdbc.sql("SELECT count(*) FROM medical_cases c JOIN patient_profiles p ON p.id=c.patient_id WHERE c.id=? AND (p.external_subject=? OR EXISTS(SELECT 1 FROM patient_representatives r WHERE r.patient_id=p.id AND r.representative_subject=? AND r.revoked_at IS NULL AND (r.expires_at IS NULL OR r.expires_at>?)))").params(caseId,actor.subject(),actor.subject(),timestamp(clock.instant())).query(Integer.class).single();if(count!=null&&count>0)return;}else{Integer count=jdbc.sql("SELECT count(*) FROM case_assignments WHERE case_id=? AND assignee_subject=? AND status IN ('PENDING','ACTIVE')").params(caseId,actor.subject()).query(Integer.class).single();if(count!=null&&count>0)return;}throw new ApiException(403,"CASE_ACCESS_DENIED","This account is not authorized to access the case");}
    private void authorizeWrite(UUID caseId,ActorContext.Actor actor){if(actor.has(ActorRole.AUDITOR))throw new ApiException(403,"READ_ONLY_ROLE","Auditors cannot modify records");authorizeRead(caseId,actor);}
    private void requireCoordinatorOwnership(UUID caseId,ActorContext.Actor actor){if(actor.has(ActorRole.SYSTEM_ADMIN))return;if(!actor.has(ActorRole.COORDINATOR)&&!actor.has(ActorRole.COORDINATOR_LEAD))return;Integer owned=jdbc.sql("SELECT count(*) FROM case_assignments WHERE case_id=? AND assignee_subject=? AND assignee_role='COORDINATOR' AND assignment_type='PRIMARY' AND status='ACTIVE'").params(caseId,actor.subject()).query(Integer.class).single();if(owned==null||owned==0)throw new ApiException(409,"CASE_NOT_OWNED","Take ownership of the case before performing this action");}
    private void transitionInternal(UUID caseId,String target,String reason,long expectedVersion,ActorContext.Actor actor){CaseState current=state(caseId);Set<String>allowed=TRANSITIONS.getOrDefault(current.status(),Set.of());if(!allowed.contains(target))throw new ApiException(409,"INVALID_CASE_TRANSITION","The requested case transition is not allowed");int changed=jdbc.sql("UPDATE medical_cases SET status=?,updated_at=?,version=version+1 WHERE id=? AND version=?").params(target,timestamp(clock.instant()),caseId,expectedVersion).update();if(changed!=1)throw new ApiException(409,"CASE_VERSION_CONFLICT","The case was updated by another user");history(caseId,current.status(),target,actor,reason);}
    private void transitionWithoutVersion(UUID caseId,String target,String reason,ActorContext.Actor actor){CaseState current=state(caseId);if(current.status().equals(target))return;Set<String>allowed=TRANSITIONS.getOrDefault(current.status(),Set.of());if(!allowed.contains(target))return;int changed=jdbc.sql("UPDATE medical_cases SET status=?,updated_at=?,version=version+1 WHERE id=? AND version=?").params(target,timestamp(clock.instant()),caseId,current.version()).update();if(changed!=1)throw new ApiException(409,"CASE_VERSION_CONFLICT","The case was updated by another user");history(caseId,current.status(),target,actor,reason);}
    private CaseState state(UUID caseId){return jdbc.sql("SELECT status,version FROM medical_cases WHERE id=?").param(caseId).query((rs,n)->new CaseState(rs.getString("status"),rs.getLong("version"))).optional().orElseThrow(()->new ApiException(404,"CASE_NOT_FOUND","Case was not found"));}
    private void history(UUID caseId,String from,String to,ActorContext.Actor actor,String reason){jdbc.sql("INSERT INTO case_status_history(id,case_id,from_status,to_status,actor_subject,actor_role,reason,created_at) VALUES(?,?,?,?,?,?,?,?)").params(UUID.randomUUID(),caseId,from,to,actor.subject(),actor.primaryRole(),reason,timestamp(clock.instant())).update();audit("CASE_STATUS_CHANGED",actor,caseId,"MedicalCase",caseId.toString(),"TRANSITION","SUCCESS",reason);}
    private UUID practitionerId(String subject){return jdbc.sql("SELECT id FROM practitioner_profiles WHERE external_subject=? AND credentialing_status='VERIFIED'").param(subject).query(UUID.class).optional().orElseThrow(()->new ApiException(403,"DOCTOR_NOT_VERIFIED","The doctor account is not linked to a verified practitioner profile"));}
    private ActorRole parseRole(String role){try{return ActorRole.valueOf(role);}catch(Exception e){throw new ApiException(400,"INVALID_ROLE","The assignment role is invalid");}}
    private ProposalView latestProposal(UUID caseId,ActorContext.Actor actor){String restriction=actor.has(ActorRole.PATIENT)||actor.has(ActorRole.PATIENT_REPRESENTATIVE)?" AND pv.status IN ('RELEASED','VIEWED','ACCEPTED','DECLINED','REVISION_REQUESTED','EXPIRED')":"";return jdbc.sql("SELECT pv.id FROM proposal_versions pv JOIN proposals p ON p.id=pv.proposal_id WHERE p.case_id=?"+restriction+" ORDER BY pv.version_number DESC LIMIT 1").param(caseId).query(UUID.class).optional().map(this::proposal).orElse(null);}
    private void ensureProposalBelongs(UUID caseId,UUID versionId){Integer count=jdbc.sql("SELECT count(*) FROM proposal_versions pv JOIN proposals p ON p.id=pv.proposal_id WHERE pv.id=? AND p.case_id=?").params(versionId,caseId).query(Integer.class).single();if(count==null||count==0)throw new ApiException(404,"PROPOSAL_NOT_FOUND","Proposal version was not found for this case");}
    private ProposalView proposal(UUID versionId){return jdbc.sql("SELECT p.id proposal_id,pv.* FROM proposal_versions pv JOIN proposals p ON p.id=pv.proposal_id WHERE pv.id=?").param(versionId).query((rs,n)->new ProposalView(rs.getObject("proposal_id",UUID.class),rs.getObject("id",UUID.class),rs.getInt("version_number"),rs.getString("status"),rs.getString("language"),rs.getString("currency"),instantNullable(rs,"valid_until"),rs.getString("operational_plan"),rs.getString("included_services"),rs.getString("excluded_services"),rs.getString("payment_terms"),rs.getString("refund_terms"),rs.getString("disclaimers"),proposalItems(versionId))).optional().orElseThrow(()->new ApiException(404,"PROPOSAL_NOT_FOUND","Proposal version was not found"));}
    private List<ProposalItemView> proposalItems(UUID versionId){return jdbc.sql("SELECT * FROM proposal_items WHERE proposal_version_id=? ORDER BY sort_order,id").param(versionId).query((rs,n)->new ProposalItemView(rs.getObject("id",UUID.class),rs.getString("category"),rs.getString("description"),rs.getBigDecimal("quantity"),rs.getBigDecimal("unit_price"),rs.getBoolean("optional"))).list();}
    private String renderProposal(ProposalView view){StringBuilder html=new StringBuilder("<article><h1>RehletShifaa Proposal v").append(view.versionNumber()).append("</h1><p>Status: released</p><ul>");for(ProposalItemView item:view.items())html.append("<li>").append(escape(item.description())).append(" — ").append(item.quantity().multiply(item.unitPrice())).append(' ').append(escape(view.currency())).append("</li>");return html.append("</ul><p>Proposal acceptance is not procedure-specific medical consent.</p></article>").toString();}
    private String escape(String value){return value==null?"":value.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;");}
    private void audit(String type,ActorContext.Actor actor,UUID caseId,String entity,String entityId,String action,String outcome,String reason){jdbc.sql("INSERT INTO audit_events(id,event_type,actor_subject,actor_role,case_id,entity_type,entity_id,action,outcome,reason,occurred_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)").params(UUID.randomUUID(),type,actor.subject(),actor.primaryRole(),caseId,entity,entityId,action,outcome,reason,timestamp(clock.instant())).update();}
    private static Instant instant(ResultSet rs,String column)throws SQLException{return rs.getObject(column,OffsetDateTime.class).toInstant();}
    private static Instant instantNullable(ResultSet rs,String column)throws SQLException{OffsetDateTime value=rs.getObject(column,OffsetDateTime.class);return value==null?null:value.toInstant();}
    private record Claim(UUID id,UUID patientId,String hash,Instant expiresAt,int attempts,int maxAttempts,Instant consumedAt,Instant revokedAt){}
    private record CaseState(String status,long version){}
}
