package com.rehletshifaa.journey.application;

import com.rehletshifaa.casemanagement.application.IntakeLifecycleService;
import com.rehletshifaa.document.api.DocumentDtos;
import com.rehletshifaa.document.application.DocumentService;
import com.rehletshifaa.journey.api.PublicCaseDtos.*;
import com.rehletshifaa.shared.api.ApiException;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.SecureRandom;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.*;
import java.util.*;

import static com.rehletshifaa.shared.persistence.SqlValues.timestamp;

@Service
public class PublicCaseAccessService {
    private static final Duration CODE_TTL=Duration.ofMinutes(15);
    private static final Duration GRANT_TTL=Duration.ofMinutes(30);
    private static final int MAX_ATTEMPTS=5;
    private static final int MAX_SENDS_PER_HOUR=5;
    private static final int MAX_RECOVERY_SENDS_PER_HOUR=3;
    private final JdbcClient jdbc; private final IntakeLifecycleService intake; private final DocumentService documents; private final Clock clock; private final SecureRandom random=new SecureRandom();

    public PublicCaseAccessService(JdbcClient jdbc,IntakeLifecycleService intake,DocumentService documents,Clock clock){this.jdbc=jdbc;this.intake=intake;this.documents=documents;this.clock=clock;}

    @Transactional(readOnly=true) public CaseAccessSummary summary(String token){return summary(find(token));}

    /**
     * Sends a fresh status link only when both identifiers match. The public response is deliberately
     * identical for matches, misses, and throttled cases so this endpoint cannot be used to enumerate
     * patients or case numbers.
     */
    @Transactional public void recoverStatusLink(CaseLinkRecoveryRequest request){
        String caseNumber=request.caseNumber().trim().toUpperCase(Locale.ROOT);
        Optional<RecoveryContact> match=jdbc.sql("SELECT c.id,c.patient_id,p.whatsapp_number,p.preferred_language FROM medical_cases c JOIN patient_profiles p ON p.id=c.patient_id WHERE c.case_number=? AND c.status<>'DRAFT'")
            .param(caseNumber).query((rs,n)->new RecoveryContact(rs.getObject("id",UUID.class),rs.getObject("patient_id",UUID.class),rs.getString("whatsapp_number"),rs.getString("preferred_language"))).optional();
        if(match.isEmpty()||!samePhone(match.get().whatsapp(),request.whatsappNumber()))return;
        RecoveryContact contact=match.get();Instant now=clock.instant();String prefix="case-status-recovery:"+contact.caseId()+":";
        Integer recent=jdbc.sql("SELECT count(*) FROM notification_outbox WHERE idempotency_key LIKE ? AND created_at>?").params(prefix+"%",timestamp(now.minus(Duration.ofHours(1)))).query(Integer.class).single();
        if(recent!=null&&recent>=MAX_RECOVERY_SENDS_PER_HOUR)return;
        String token=randomToken();UUID linkId=UUID.randomUUID();String language="ar".equals(request.language())||("ar".equals(contact.language())&&request.language()==null)?"ar":"en";
        jdbc.sql("INSERT INTO case_access_links(id,case_id,patient_id,purpose,token_hash,expires_at,created_at) VALUES(?,?,?,?,?,?,?)").params(linkId,contact.caseId(),contact.patientId(),"STATUS",intake.hash(token),timestamp(now.plus(Duration.ofDays(30))),timestamp(now)).update();
        jdbc.sql("INSERT INTO notification_outbox(id,notification_type,channel,destination,template_key,template_data,status,attempts,max_attempts,next_attempt_at,idempotency_key,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)")
            .params(UUID.randomUUID(),"CASE_STATUS_RECOVERY","WHATSAPP",contact.whatsapp(),"case-status-link",intake.encryptedJson("{\"token\":\""+token+"\",\"lang\":\""+language+"\"}"),"PENDING",0,5,timestamp(now),prefix+linkId,timestamp(now)).update();
        audit("CASE_STATUS_LINK_RECOVERED",contact.caseId(),linkId.toString(),"RECOVER");
    }

    @Transactional public CaseAccessSummary requestAccess(String token){return requestAccess(token,null);}
    /** OTP for secure case-status/information access. The patient may choose WhatsApp or email (default
     *  WhatsApp); the destination is always the profile's own contact. A verified OTP proves contact
     *  possession (CONTACT_VERIFIED) — never legal identity. Resending revokes the prior active challenge. */
    @Transactional public CaseAccessSummary requestAccess(String token,String requestedChannel){Link link=find(token);Instant now=clock.instant();Integer recent=jdbc.sql("SELECT count(*) FROM case_access_challenges WHERE link_id=? AND created_at>?").params(link.id(),timestamp(now.minus(Duration.ofHours(1)))).query(Integer.class).single();if(recent!=null&&recent>=MAX_SENDS_PER_HOUR)throw new ApiException(429,"TOO_MANY_REQUESTS","Too many verification requests. Please try again later.");jdbc.sql("UPDATE case_access_challenges SET revoked_at=? WHERE link_id=? AND consumed_at IS NULL AND revoked_at IS NULL").params(timestamp(now),link.id()).update();Contact contact=contact(link.caseId());String channel=chooseChannel(requestedChannel,contact.whatsapp(),contact.email());String destination="WHATSAPP".equals(channel)?contact.whatsapp():contact.email();String code="%06d".formatted(random.nextInt(1_000_000));UUID id=UUID.randomUUID();jdbc.sql("INSERT INTO case_access_challenges(id,link_id,code_hash,delivery_channel,destination_hint,expires_at,attempts,max_attempts,created_at) VALUES(?,?,?,?,?,?,?,?,?)").params(id,link.id(),intake.hash(code),channel,mask(destination),timestamp(now.plus(CODE_TTL)),0,MAX_ATTEMPTS,timestamp(now)).update();jdbc.sql("INSERT INTO notification_outbox(id,notification_type,channel,destination,template_key,template_data,status,attempts,max_attempts,next_attempt_at,idempotency_key,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)").params(UUID.randomUUID(),"CASE_ACCESS",channel,destination,"case-access-code",intake.encryptedJson("{\"code\":\""+code+"\"}"),"PENDING",0,5,timestamp(now),"case-access:"+id,timestamp(now)).update();audit("CASE_ACCESS_REQUESTED",link.caseId(),link.id().toString(),"REQUEST_ACCESS");return summary(link);}

    @Transactional(noRollbackFor=ApiException.class) public CaseAccessGrant verify(String token,String code){Link link=find(token);Instant now=clock.instant();Challenge challenge=jdbc.sql("SELECT id,code_hash,expires_at,attempts,max_attempts,consumed_at,revoked_at,delivery_channel FROM case_access_challenges WHERE link_id=? ORDER BY created_at DESC LIMIT 1").param(link.id()).query(this::challenge).optional().orElseThrow(this::invalid);if(challenge.consumedAt()!=null||challenge.revokedAt()!=null||!challenge.expiresAt().isAfter(now)||challenge.attempts()>=challenge.maxAttempts())throw invalid();boolean match=MessageDigest.isEqual(challenge.hash().getBytes(StandardCharsets.US_ASCII),intake.hash(code).getBytes(StandardCharsets.US_ASCII));if(!match){int next=challenge.attempts()+1;int changed=jdbc.sql("UPDATE case_access_challenges SET attempts=?,revoked_at=CASE WHEN ?>=max_attempts THEN ? ELSE revoked_at END WHERE id=? AND attempts=? AND consumed_at IS NULL AND revoked_at IS NULL").params(next,next,timestamp(now),challenge.id(),challenge.attempts()).update();if(changed!=1)throw invalid();audit("CASE_ACCESS_FAILED",link.caseId(),link.id().toString(),"VERIFY");throw invalid();}String grant=randomToken();Instant expires=now.plus(GRANT_TTL);int consumed=jdbc.sql("UPDATE case_access_challenges SET attempts=attempts+1,consumed_at=?,grant_hash=?,grant_expires_at=? WHERE id=? AND attempts=? AND consumed_at IS NULL AND revoked_at IS NULL AND expires_at>?").params(timestamp(now),intake.hash(grant),timestamp(expires),challenge.id(),challenge.attempts(),timestamp(now)).update();if(consumed!=1)throw invalid();markContactVerified(link.caseId(),challenge.channel(),now);audit("CASE_ACCESS_VERIFIED",link.caseId(),link.id().toString(),"VERIFY");return new CaseAccessGrant(grant,expires);}

    @Transactional(readOnly=true) public PublicCaseStatus view(String token,String grant){Link link=requireGrant(token,grant);Status status=jdbc.sql("SELECT case_number,status FROM medical_cases WHERE id=?").param(link.caseId()).query((rs,n)->new Status(rs.getString("case_number"),rs.getString("status"))).single();Labels labels=labels(status.status());return new PublicCaseStatus(status.caseNumber(),labels.en(),labels.ar(),"INFORMATION_RESPONSE".equals(link.purpose()));}

    @Transactional public UUID respond(String token,InformationResponseRequest request){Link link=requireGrant(token,request.grant());if(!"INFORMATION_RESPONSE".equals(link.purpose()))throw new ApiException(403,"LINK_PURPOSE_MISMATCH","This link cannot be used for that action");UUID id=UUID.randomUUID();Instant now=clock.instant();jdbc.sql("INSERT INTO case_messages(id,case_id,thread_type,sender_subject,sender_role,body,language,internal_only,created_at) VALUES(?,?,?,?,?,?,?,?,?)").params(id,link.caseId(),"PATIENT_COORDINATOR","SECURE_LINK","PATIENT",intake.encryptedJson(request.message()),request.language()==null?"en":request.language(),false,timestamp(now)).update();int changed=jdbc.sql("UPDATE medical_cases SET status='INTAKE_REVIEW',updated_at=?,version=version+1 WHERE id=? AND status='INFORMATION_REQUIRED'").params(timestamp(now),link.caseId()).update();if(changed!=1)throw new ApiException(409,"CASE_STATE_CONFLICT","The information request is no longer active");jdbc.sql("UPDATE case_tasks SET status='COMPLETED',completed_at=?,completion_evidence=?,updated_at=?,version=version+1 WHERE case_id=? AND visibility_scope='PATIENT_ACTION' AND blocking=TRUE AND status IN ('OPEN','IN_PROGRESS')").params(timestamp(now),intake.encryptedJson("Patient supplied the requested information"),timestamp(now),link.caseId()).update();jdbc.sql("INSERT INTO case_status_history(id,case_id,from_status,to_status,actor_subject,actor_role,reason,created_at) VALUES(?,?,?,?,?,?,?,?)").params(UUID.randomUUID(),link.caseId(),"INFORMATION_REQUIRED","INTAKE_REVIEW","SECURE_LINK","PATIENT","Patient supplied requested information",timestamp(now)).update();jdbc.sql("UPDATE case_access_links SET revoked_at=? WHERE id=? AND revoked_at IS NULL").params(timestamp(now),link.id()).update();audit("PATIENT_INFORMATION_RECEIVED",link.caseId(),id.toString(),"RESPOND");return id;}

    public DocumentDtos.PresignResponse presign(String token,String grant,DocumentDtos.PresignRequest request){Link link=requireGrant(token,grant);requireInformationPurpose(link);return documents.presignAdditional(link.caseId(),request);}
    public DocumentDtos.ConfirmResponse confirm(String token,String grant,DocumentDtos.ConfirmRequest request){Link link=requireGrant(token,grant);requireInformationPurpose(link);return documents.confirmAdditional(link.caseId(),request);}

    @Transactional public String issueInformationRequest(UUID caseId,String language){Instant now=clock.instant();UUID patientId=jdbc.sql("SELECT patient_id FROM medical_cases WHERE id=?").param(caseId).query(UUID.class).single();String safeTitle="ar".equals(language)?"معلومات مطلوبة لحالتك":"Information required for your case";jdbc.sql("INSERT INTO case_tasks(id,case_id,task_type,title,owner_role,visibility_scope,priority,status,blocking,created_by,created_at,updated_at,version) SELECT ?,?,'INFORMATION_REQUEST',?,'PATIENT','PATIENT_ACTION','HIGH','OPEN',TRUE,'SYSTEM',?,?,0 WHERE NOT EXISTS (SELECT 1 FROM case_tasks WHERE case_id=? AND task_type='INFORMATION_REQUEST' AND visibility_scope='PATIENT_ACTION' AND status IN ('OPEN','IN_PROGRESS'))").params(UUID.randomUUID(),caseId,intake.encryptedJson(safeTitle),timestamp(now),timestamp(now),caseId).update();jdbc.sql("UPDATE case_access_links SET revoked_at=? WHERE case_id=? AND purpose='INFORMATION_RESPONSE' AND revoked_at IS NULL").params(timestamp(now),caseId).update();String token=randomToken();UUID id=UUID.randomUUID();jdbc.sql("INSERT INTO case_access_links(id,case_id,patient_id,purpose,token_hash,expires_at,created_at) VALUES(?,?,?,?,?,?,?)").params(id,caseId,patientId,"INFORMATION_RESPONSE",intake.hash(token),timestamp(now.plus(Duration.ofDays(14))),timestamp(now)).update();Contact contact=contact(caseId);String channel=hasText(contact.whatsapp())?"WHATSAPP":"EMAIL";String destination="WHATSAPP".equals(channel)?contact.whatsapp():contact.email();if(hasText(destination))jdbc.sql("INSERT INTO notification_outbox(id,notification_type,channel,destination,template_key,template_data,status,attempts,max_attempts,next_attempt_at,idempotency_key,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)").params(UUID.randomUUID(),"PATIENT_ACTION",channel,destination,"patient-action-link",intake.encryptedJson("{\"token\":\""+token+"\",\"lang\":\""+("ar".equals(language)?"ar":"en")+"\"}"),"PENDING",0,5,timestamp(now),"patient-action:"+id,timestamp(now)).update();audit("PATIENT_ACTION_LINK_CREATED",caseId,id.toString(),"CREATE");return token;}

    @Transactional public String issueStatusLink(UUID caseId,String language,String template,String idempotencyKey){Instant now=clock.instant();UUID patientId=jdbc.sql("SELECT patient_id FROM medical_cases WHERE id=?").param(caseId).query(UUID.class).single();String token=randomToken();UUID id=UUID.randomUUID();jdbc.sql("INSERT INTO case_access_links(id,case_id,patient_id,purpose,token_hash,expires_at,created_at) VALUES(?,?,?,?,?,?,?)").params(id,caseId,patientId,"STATUS",intake.hash(token),timestamp(now.plus(Duration.ofDays(30))),timestamp(now)).update();Contact contact=contact(caseId);String channel=hasText(contact.whatsapp())?"WHATSAPP":"EMAIL";String destination="WHATSAPP".equals(channel)?contact.whatsapp():contact.email();if(hasText(destination))jdbc.sql("INSERT INTO notification_outbox(id,notification_type,channel,destination,template_key,template_data,status,attempts,max_attempts,next_attempt_at,idempotency_key,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)").params(UUID.randomUUID(),"SECURE_MESSAGE",channel,destination,template,intake.encryptedJson("{\"token\":\""+token+"\",\"lang\":\""+("ar".equals(language)?"ar":"en")+"\"}"),"PENDING",0,5,timestamp(now),idempotencyKey,timestamp(now)).update();audit("CASE_STATUS_LINK_CREATED",caseId,id.toString(),"CREATE");return token;}

    private void requireInformationPurpose(Link link){if(!"INFORMATION_RESPONSE".equals(link.purpose()))throw new ApiException(403,"LINK_PURPOSE_MISMATCH","This link cannot upload documents");}
    private Link requireGrant(String token,String grant){Link link=find(token);Integer ok=jdbc.sql("SELECT count(*) FROM case_access_challenges WHERE link_id=? AND grant_hash=? AND grant_expires_at>? AND consumed_at IS NOT NULL AND revoked_at IS NULL").params(link.id(),intake.hash(grant),timestamp(clock.instant())).query(Integer.class).single();if(ok==null||ok==0)throw new ApiException(401,"VERIFICATION_REQUIRED","Please verify your identity to continue");return link;}
    private Link find(String token){return jdbc.sql("SELECT id,case_id,patient_id,purpose,expires_at,revoked_at FROM case_access_links WHERE token_hash=?").param(intake.hash(token)).query((rs,n)->new Link(rs.getObject("id",UUID.class),rs.getObject("case_id",UUID.class),rs.getObject("patient_id",UUID.class),rs.getString("purpose"),instant(rs,"expires_at"),instantNullable(rs,"revoked_at"))).optional().filter(x->x.revokedAt()==null&&x.expiresAt().isAfter(clock.instant())).orElseThrow(()->new ApiException(404,"CASE_LINK_INVALID","This secure link is invalid or has expired"));}
    private CaseAccessSummary summary(Link link){Contact c=contact(link.caseId());String channel=hasText(c.whatsapp())?"WHATSAPP":"EMAIL";String destination="WHATSAPP".equals(channel)?c.whatsapp():c.email();return new CaseAccessSummary(c.caseNumber(),link.purpose(),channel,mask(destination));}
    private Contact contact(UUID caseId){return jdbc.sql("SELECT c.case_number,p.whatsapp_number,p.email FROM medical_cases c JOIN patient_profiles p ON p.id=c.patient_id WHERE c.id=?").param(caseId).query((rs,n)->new Contact(rs.getString("case_number"),rs.getString("whatsapp_number"),rs.getString("email"))).single();}
    private Challenge challenge(ResultSet rs,int n)throws SQLException{return new Challenge(rs.getObject("id",UUID.class),rs.getString("code_hash"),instant(rs,"expires_at"),rs.getInt("attempts"),rs.getInt("max_attempts"),instantNullable(rs,"consumed_at"),instantNullable(rs,"revoked_at"),rs.getString("delivery_channel"));}
    private String chooseChannel(String requested,String whatsapp,String email){if(requested==null||requested.isBlank())return hasText(whatsapp)?"WHATSAPP":"EMAIL";String c=requested.toUpperCase(Locale.ROOT);if(!"WHATSAPP".equals(c)&&!"EMAIL".equals(c))throw new ApiException(400,"INVALID_CONTACT_CHANNEL","Choose WhatsApp or email");String dest="WHATSAPP".equals(c)?whatsapp:email;if(!hasText(dest))throw new ApiException(409,"CONTACT_CHANNEL_UNAVAILABLE","That contact method is not on file for this case");return c;}
    /** Stamp ONLY the channel that carried the OTP: WhatsApp -> phone_verified_at, email -> email_verified_at. */
    private void markContactVerified(UUID caseId,String channel,Instant now){String column="WHATSAPP".equals(channel)?"phone_verified_at":"EMAIL".equals(channel)?"email_verified_at":null;if(column==null)return;jdbc.sql("UPDATE patient_profiles SET "+column+"=?,updated_at=? WHERE id=(SELECT patient_id FROM medical_cases WHERE id=?)").params(timestamp(now),timestamp(now),caseId).update();}
    private ApiException invalid(){return new ApiException(400,"VERIFICATION_INVALID","The verification code is invalid or has expired");}
    private String randomToken(){return UUID.randomUUID().toString().replace("-","")+UUID.randomUUID().toString().replace("-","");}
    private boolean samePhone(String left,String right){return normalizePhone(left).equals(normalizePhone(right));}
    private String normalizePhone(String value){String digits=value==null?"":value.replaceAll("\\D","");return digits.startsWith("00")?digits.substring(2):digits;}
    private boolean hasText(String value){return value!=null&&!value.isBlank();}
    private String mask(String value){if(value==null)return "***";String clean=value.replaceAll("\\s","");if(clean.contains("@")){int at=clean.indexOf('@');return (at==0?"*":clean.charAt(0)+"***")+clean.substring(at);}return clean.length()<4?"***":"***"+clean.substring(clean.length()-4);}
    private Labels labels(String status){return switch(status){case "RECEIVED"->new Labels("Case received","تم استلام الحالة");case "INTAKE_REVIEW"->new Labels("Reviewing your information","جارٍ مراجعة معلوماتك");case "INFORMATION_REQUIRED"->new Labels("Action required from you","مطلوب إجراء منك");case "READY_FOR_CONSULTANT","CONSULTANT_ASSIGNMENT_PENDING"->new Labels("Matching your consultant","جارٍ اختيار الاستشاري المناسب");case "CONSULTANT_REVIEW"->new Labels("Under consultant review","قيد مراجعة الاستشاري");case "CLINICAL_RECOMMENDATION_READY"->new Labels("Treatment recommendation ready","توصية العلاج جاهزة");case "PROPOSAL_PREPARATION","PROPOSAL_INTERNAL_APPROVAL"->new Labels("Preparing your proposal","جارٍ إعداد عرضك");case "PATIENT_DECISION"->new Labels("Waiting for your decision","بانتظار قرارك");case "ACCEPTED","TRAVEL_COORDINATION","ARRIVAL_CONFIRMED"->new Labels("Coordinating your journey","جارٍ تنسيق رحلتك");case "TREATMENT_IN_PROGRESS","DISCHARGED"->new Labels("Treatment in progress","العلاج جارٍ");case "FOLLOW_UP"->new Labels("Follow-up","المتابعة");case "CLOSED"->new Labels("Journey completed","اكتملت الرحلة");case "DECLINED"->new Labels("Proposal declined by patient","تم رفض العرض من المريض");case "EXPIRED"->new Labels("Proposal expired","انتهت صلاحية العرض");case "CLINICALLY_NOT_SUITABLE"->new Labels("Your coordinator will contact you","سيتواصل معك منسق حالتك");default->new Labels("Your case is being coordinated","جارٍ تنسيق حالتك");};}
    private void audit(String type,UUID caseId,String entityId,String action){jdbc.sql("INSERT INTO audit_events(id,event_type,actor_subject,actor_role,case_id,entity_type,entity_id,action,outcome,occurred_at) VALUES(?,?,?,?,?,?,?,?,?,?)").params(UUID.randomUUID(),type,"SECURE_LINK","PATIENT",caseId,"CaseAccess",entityId,action,"SUCCESS",timestamp(clock.instant())).update();}
    private static Instant instant(ResultSet rs,String column)throws SQLException{return rs.getObject(column,OffsetDateTime.class).toInstant();}
    private static Instant instantNullable(ResultSet rs,String column)throws SQLException{OffsetDateTime v=rs.getObject(column,OffsetDateTime.class);return v==null?null:v.toInstant();}
    private record Link(UUID id,UUID caseId,UUID patientId,String purpose,Instant expiresAt,Instant revokedAt){}
    private record Challenge(UUID id,String hash,Instant expiresAt,int attempts,int maxAttempts,Instant consumedAt,Instant revokedAt,String channel){}
    private record Contact(String caseNumber,String whatsapp,String email){}
    private record RecoveryContact(UUID caseId,UUID patientId,String whatsapp,String language){}
    private record Status(String caseNumber,String status){}
    private record Labels(String en,String ar){}
}
