package com.rehletshifaa.provider.domain;

public enum ClinicianOnboardingStatus {
    INVITED, PROFILE_INCOMPLETE, DOCUMENTS_SUBMITTED, UNDER_VERIFICATION,
    MORE_INFORMATION_REQUIRED, VERIFIED, REJECTED, OPERATIONAL_SETUP,
    ACTIVE, SUSPENDED, OFFBOARDED, LEGACY_UNREVIEWED
}
