"use client";

import { useEffect, useState } from "react";
import { CheckCircle2, FileUp, LockKeyhole } from "lucide-react";
import type { Locale } from "@/lib/i18n";

type Summary={caseNumber:string;purpose:"STATUS"|"INFORMATION_RESPONSE";channel:string;destinationHint:string};
type Status={caseNumber:string;statusEn:string;statusAr:string;actionRequired:boolean};
type Presign={documentId:string;uploadUrl:string;requiredHeaders:Record<string,string>};
const API=process.env.NEXT_PUBLIC_API_BASE_URL??"http://localhost:8080";
const text={
 en:{title:"Track your case securely",loading:"Checking your secure link…",send:"Send verification code",sent:"We sent a 6-digit code to",code:"Verification code",verify:"Verify and continue",status:"Current update",action:"Your coordinator needs more information",message:"Add a short note",files:"Add supporting documents",choose:"Choose files",submit:"Send information",done:"Thank you — your information was sent securely.",invalid:"This secure link is invalid or has expired.",error:"The request could not be completed. Please try again.",private:"Your medical information is shown only after contact verification."},
 ar:{title:"متابعة حالتك بأمان",loading:"جارٍ التحقق من الرابط الآمن…",send:"إرسال رمز التحقق",sent:"أرسلنا رمزًا مكوّنًا من 6 أرقام إلى",code:"رمز التحقق",verify:"تحقق وتابع",status:"آخر تحديث",action:"يحتاج منسق حالتك إلى معلومات إضافية",message:"أضف ملاحظة قصيرة",files:"إضافة مستندات داعمة",choose:"اختيار الملفات",submit:"إرسال المعلومات",done:"شكرًا — تم إرسال معلوماتك بأمان.",invalid:"هذا الرابط الآمن غير صالح أو انتهت صلاحيته.",error:"تعذر إكمال الطلب. يرجى المحاولة مرة أخرى.",private:"لا تظهر معلوماتك الطبية إلا بعد التحقق من جهة الاتصال."}
};

export function CaseStatusAccess({locale,token}:{locale:Locale;token:string}){
 const t=text[locale];const[summary,setSummary]=useState<Summary|null>(null);const[status,setStatus]=useState<Status|null>(null);const[phase,setPhase]=useState<"loading"|"summary"|"code"|"view"|"done"|"invalid">("loading");const[code,setCode]=useState("");const[grant,setGrant]=useState("");const[message,setMessage]=useState("");const[files,setFiles]=useState<File[]>([]);const[busy,setBusy]=useState(false);const[error,setError]=useState("");
 useEffect(()=>{void fetch(`${API}/api/v1/public/cases/${token}`,{cache:"no-store"}).then(async r=>{if(!r.ok)throw new Error();return r.json() as Promise<Summary>;}).then(s=>{setSummary(s);setPhase("summary");}).catch(()=>setPhase("invalid"));},[token]);
 const request=async()=>{setBusy(true);setError("");try{const r=await fetch(`${API}/api/v1/public/cases/${token}/request-access`,{method:"POST"});if(!r.ok)throw new Error(await apiError(r,t.error));setSummary(await r.json() as Summary);setPhase("code");}catch(e){setError(e instanceof Error?e.message:t.error);}finally{setBusy(false);}};
 const verify=async()=>{setBusy(true);setError("");try{const r=await fetch(`${API}/api/v1/public/cases/${token}/verify`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({code:code.trim()})});if(!r.ok)throw new Error(await apiError(r,t.error));const access=await r.json() as {grant:string};setGrant(access.grant);const view=await fetch(`${API}/api/v1/public/cases/${token}/view`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({grant:access.grant})});if(!view.ok)throw new Error(await apiError(view,t.error));setStatus(await view.json() as Status);setPhase("view");}catch(e){setError(e instanceof Error?e.message:t.error);}finally{setBusy(false);}};
 const respond=async()=>{setBusy(true);setError("");try{for(const file of files){const pre=await fetch(`${API}/api/v1/public/cases/${token}/documents/presign`,{method:"POST",headers:{"Content-Type":"application/json","X-Case-Grant":grant},body:JSON.stringify({originalFileName:file.name,contentType:file.type,sizeBytes:file.size})});if(!pre.ok)throw new Error(await apiError(pre,t.error));const p=await pre.json() as Presign;const upload=await fetch(p.uploadUrl,{method:"PUT",headers:p.requiredHeaders,body:file});if(!upload.ok)throw new Error(t.error);const confirm=await fetch(`${API}/api/v1/public/cases/${token}/documents/confirm`,{method:"POST",headers:{"Content-Type":"application/json","X-Case-Grant":grant},body:JSON.stringify({documentId:p.documentId})});if(!confirm.ok)throw new Error(await apiError(confirm,t.error));}const response=await fetch(`${API}/api/v1/public/cases/${token}/respond`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({grant,message,language:locale})});if(!response.ok)throw new Error(await apiError(response,t.error));setPhase("done");}catch(e){setError(e instanceof Error?e.message:t.error);}finally{setBusy(false);}};
 if(phase==="loading")return <Frame t={t}><p>{t.loading}</p></Frame>;
 if(phase==="invalid")return <Frame t={t}><p role="alert" className="rounded-xl bg-alert-50 p-4 text-alert-800">{t.invalid}</p></Frame>;
 if(phase==="done")return <Frame t={t}><div className="flex items-center gap-3 rounded-xl bg-brand-50 p-5 text-brand-800"><CheckCircle2/><strong>{t.done}</strong></div></Frame>;
 return <Frame t={t}>{summary&&<p className="mb-5 font-bold text-brand-800">{summary.caseNumber}</p>}{phase==="summary"&&<><p className="text-ink-600"><LockKeyhole className="me-2 inline" size={17}/>{t.private}</p><button className="btn-primary mt-6" disabled={busy} onClick={()=>void request()}>{t.send}</button></>}{phase==="code"&&<div><p className="mb-4 text-ink-600">{t.sent} {summary?.destinationHint}</p><label className="block text-sm font-bold">{t.code}<input className="field mt-2" dir="ltr" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,""))}/></label><button className="btn-primary mt-5" disabled={busy||code.length!==6} onClick={()=>void verify()}>{t.verify}</button></div>}{phase==="view"&&status&&<div><p className="text-sm font-bold text-brand-700">{t.status}</p><h2 className="mt-2 text-2xl font-bold text-brand-900">{locale==="ar"?status.statusAr:status.statusEn}</h2>{status.actionRequired&&<form className="mt-7 space-y-4" onSubmit={e=>{e.preventDefault();void respond();}}><h3 className="title">{t.action}</h3><label className="block text-sm font-bold">{t.message}<textarea className="field mt-2 min-h-28" maxLength={10000} required value={message} onChange={e=>setMessage(e.target.value)}/></label><label className="flex cursor-pointer items-center gap-3 rounded-lg border border-dashed border-line-strong p-4"><FileUp/><span>{files.length?`${files.length} ${t.files}`:t.choose}</span><input className="sr-only" type="file" multiple accept=".pdf,.jpg,.jpeg,.png,application/pdf,image/jpeg,image/png" onChange={e=>setFiles(Array.from(e.target.files??[]))}/></label><button className="btn-primary" disabled={busy||!message.trim()}>{t.submit}</button></form>}</div>}{error&&<p role="alert" className="mt-5 rounded-xl bg-alert-50 p-4 text-alert-800">{error}</p>}</Frame>;
}

function Frame({t,children}:{t:typeof text.en;children:React.ReactNode}){return <section className="section bg-mist"><div className="container-site max-w-2xl"><div className="card p-6 md:p-9"><p className="eyebrow">RehletShifaa</p><h1 className="headline mt-3">{t.title}</h1><div className="mt-7">{children}</div></div></div></section>}
async function apiError(response:Response,fallback:string){const body=await response.json().catch(()=>({}));return typeof body.message==="string"?body.message:fallback;}
