package com.rehletshifaa.access.domain;

public enum ActorType { GOVERNANCE, PRACTICE_OPERATIONS, CONSULTANT, ASSOCIATE_DOCTOR, CLINICAL_SUPPORT, COORDINATOR, OPERATIONS, FINANCE, PATIENT, REPRESENTATIVE, SERVICE }
