package com.rehletshifaa.access.domain;

public enum RelationshipType { MANAGES, ASSISTS, SUPERVISES, COORDINATES, ASSIGNED_TO, REPRESENTS, VERIFIES, PREFERRED_COORDINATOR, PREFERRED_COORDINATOR_TEAM }
