package com.rehletshifaa.coordination;

import com.rehletshifaa.coordination.application.*;
import com.rehletshifaa.coordination.domain.Routing.*;
import com.rehletshifaa.coordination.infrastructure.CoordinationRepository;
import com.rehletshifaa.provider.application.ProviderOperationalSetupService;
import com.rehletshifaa.shared.api.ApiException;
import com.rehletshifaa.shared.crypto.CryptoService;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.oauth2.jwt.Jwt;
import org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationToken;
import org.springframework.transaction.annotation.Transactional;
import java.time.*;
import java.util.*;
import static org.assertj.core.api.Assertions.*;

@SpringBootTest(properties="spring.task.scheduling.enabled=false")
@Transactional
class CoordinationIntegrationTest {
    @Autowired AssignmentEngine engine; @Autowired CoordinationConfigurationService config;
    @Autowired CoordinationRepository repo; @Autowired JdbcTemplate jdbc; @Autowired CryptoService crypto;
    @Autowired ProviderOperationalSetupService setup;
    UUID org,consultant,caseId,team;Instant past=Instant.now().minusSeconds(300),future=Instant.now().plusSeconds(86400);
    static final UUID MANAGER=UUID.fromString("36000001-0000-0000-0000-000000000008"),RECEIVER=UUID.fromString("36000001-0000-0000-0000-000000000016");
    @BeforeEach void seed(){org=organization();actor("routing-manager",org,MANAGER);signIn("routing-manager");consultant=clinician(org);caseId=medicalCase(consultant);team=config.saveTeam(org,null,"Coordination",new TeamConfig(true,"Care coordination",Set.of(),Set.of(),"Asia/Dubai",null),0,"Initial setup").id();candidate("routing-a",team,10,true);candidate("routing-b",team,10,true);config.savePolicy(org,0,past,future,policy(team),"Initial policy");}
    @AfterEach void clear(){SecurityContextHolder.clearContext();}
    @Test void shadowIsNonMutatingThenActivationAssignsAndIsIdempotent(){
        Decision shadow=command("SHADOW",0,null);assertThat(shadow.selectedOwner()).isEqualTo("routing-a");assertThat(repo.owner(caseId)).isNull();assertThat(count("SELECT COUNT(*) FROM notification_outbox WHERE idempotency_key LIKE 'work-email:routing:%'")).isZero();
        Decision live=command("ACTIVATE",1,null);assertThat(repo.owner(caseId)).isEqualTo("routing-a");assertThat(live.policyVersion()).isEqualTo(1);assertThat(live.explanation()).contains("team");assertThat(live.candidates()).hasSize(2);
        Command retry=new Command("same",2,"AUTO",null,null,null,"TEST");Decision first=engine.execute(org,caseId,retry);assertThat(engine.execute(org,caseId,retry)).isEqualTo(first);assertThat(first.path()).isEqualTo("CONTINUITY");
        assertThatThrownBy(()->engine.execute(org,caseId,new Command("same",2,"AUTO",null,null,null,"CHANGED"))).isInstanceOf(ApiException.class).hasMessageContaining("different input");assertThat(count("SELECT COUNT(*) FROM case_assignments WHERE case_id=? AND assignee_role='COORDINATOR' AND status='ACTIVE'",caseId)).isEqualTo(1);
        assertThatThrownBy(()->engine.guardLegacyWrite(caseId)).hasMessageContaining("authorized coordination");
    }
    @Test void preferredCoordinatorAndInactiveFallback(){preference("routing-b",team,null);assertThat(command("SHADOW",0,null).path()).isEqualTo("PREFERRED_COORDINATOR");jdbc.update("UPDATE access_subjects SET active=FALSE WHERE subject='routing-b'");Decision next=command("SHADOW",1,null);assertThat(next.selectedOwner()).isEqualTo("routing-a");assertThat(next.path()).isEqualTo("PREFERRED_TEAM");assertThat(next.candidates().stream().filter(c->c.subject().equals("routing-b")).findFirst().orElseThrow().exclusions()).contains("ACCESS_OR_MEMBERSHIP_DENIED");}
    @Test void preferredUnavailableFallsThrough(){preference("routing-b",team,null);capacity("routing-b",10,false);assertThat(command("SHADOW",0,null).selectedOwner()).isEqualTo("routing-a");}
    @Test void preferredAtCapacityFallsThrough(){preference("routing-b",team,null);capacity("routing-b",0,true);assertThat(command("SHADOW",0,null).selectedOwner()).isEqualTo("routing-a");}
    @Test void continuitySurvivesPreferenceAndCapacityIsNotDoubleCounted(){assignOwner(caseId,"routing-a");capacity("routing-a",1,true);preference("routing-b",team,null);Decision d=command("SHADOW",0,null);assertThat(d.path()).isEqualTo("CONTINUITY");assertThat(d.selectedOwner()).isEqualTo("routing-a");}
    @Test void noCandidateQueuesAlertsAndManualResolutionPreservesOtherWork(){capacity("routing-a",0,true);capacity("routing-b",0,true);command("SHADOW",0,null);Decision queued=command("ACTIVATE",1,null);assertThat(queued.selectedOwner()).isNull();assertThat(engine.queue(org)).hasSize(1);assertThat(engine.queue(org).getFirst().team()).isEqualTo(team);assertThat(engine.queue(org).getFirst().dueAt()).isAfter(Instant.now());assertThat(count("SELECT COUNT(*) FROM staff_notifications WHERE recipient_subject='routing-manager' AND event_type='COORDINATION_QUEUED'")).isEqualTo(1);assertThat(count("SELECT COUNT(*) FROM notification_outbox WHERE idempotency_key LIKE 'work-email:routing:%'")).isEqualTo(1);
        capacity("routing-a",10,true);UUID operations=task("OPERATIONS","operations");Decision assigned=command("ASSIGN",2,"routing-a");assertThat(assigned.path()).isEqualTo("MANUAL_ASSIGN");assertThat(engine.queue(org)).isEmpty();assertThat(jdbc.queryForObject("SELECT owner_subject FROM case_tasks WHERE id=?",String.class,operations)).isEqualTo("operations");assertThat(jdbc.queryForObject("SELECT status FROM medical_cases WHERE id=?",String.class,caseId)).isEqualTo("READY_FOR_CONSULTANT");}
    @Test void manualReassignmentRequiresReasonScopeAndRevision(){command("SHADOW",0,null);command("ACTIVATE",1,null);UUID coordinatorTask=task("COORDINATOR","routing-a");assertThatThrownBy(()->engine.execute(org,caseId,new Command("bad",2,"REASSIGN","routing-b",null," ","TEST"))).hasMessageContaining("reason");assertThatThrownBy(()->command("REASSIGN",2,"foreign")).hasMessageContaining("not eligible");Decision reassigned=command("REASSIGN",2,"routing-b");assertThat(reassigned.previousOwner()).isEqualTo("routing-a");assertThat(repo.owner(caseId)).isEqualTo("routing-b");assertThat(jdbc.queryForObject("SELECT owner_subject FROM case_tasks WHERE id=?",String.class,coordinatorTask)).isEqualTo("routing-b");assertThatThrownBy(()->command("AUTO",2,null)).hasMessageContaining("changed");assertThat(count("SELECT COUNT(*) FROM case_assignments WHERE case_id=? AND assignee_role='COORDINATOR' AND status='ENDED'",caseId)).isEqualTo(1);}
    @Test void crossTenantAndUnresolvedCaseFailClosed(){UUID foreign=organization();assertThatThrownBy(()->engine.execute(foreign,caseId,new Command("x",0,"SHADOW",null,null,null,"TEST"))).hasMessageContaining("not allowed");UUID otherConsultant=clinician(foreign),otherCase=medicalCase(otherConsultant);assertThatThrownBy(()->engine.execute(org,otherCase,new Command("x",0,"SHADOW",null,null,null,"TEST"))).hasMessageContaining("unique stored");assertThatThrownBy(()->config.saveMember(org,team,new Member("unknown",past,null,true,false,-1),"Add member")).isInstanceOf(ApiException.class);assertThatThrownBy(()->config.savePreference(org,otherConsultant,0,past,future,"routing-a",team,null,"Preference")).hasMessageContaining("not found");}
    @Test void dormantRoleMissingStaffAndRevokedMembershipCannotReceiveOrManage(){jdbc.update("UPDATE role_assignments SET version_id='31000001-0000-0000-0000-000000000016' WHERE subject='routing-a'");assertThat(command("SHADOW",0,null).selectedOwner()).isEqualTo("routing-b");jdbc.update("DELETE FROM staff_members WHERE external_subject='routing-b'");Decision noStaff=command("SHADOW",1,null);assertThat(noStaff.selectedOwner()).isNull();assertThat(noStaff.candidates().stream().filter(c->c.subject().equals("routing-b")).findFirst().orElseThrow().exclusions()).contains("STAFF_DISABLED");jdbc.update("UPDATE access_memberships SET status='REVOKED' WHERE organization_id=? AND subject='routing-b'",org);assertThat(command("SHADOW",2,null).selectedOwner()).isNull();jdbc.update("UPDATE role_assignments SET version_id='31000001-0000-0000-0000-000000000008' WHERE subject='routing-manager'");assertThatThrownBy(()->config.teams(org)).hasMessageContaining("not allowed");}
    @Test void immutablePolicyPreferenceAndReadiness(){assertThat(setup.evaluate(org,consultant).routingComplete()).isTrue();assertThat(setup.evaluate(org,consultant).commercialAcceptanceComplete()).isFalse();assertThatThrownBy(()->config.savePolicy(org,0,future,future.plusSeconds(1000),policy(team),"Stale")).hasMessageContaining("changed");assertThatThrownBy(()->config.savePolicy(org,1,past,future,policy(team),"Overlap")).hasMessageContaining("overlap");Policy next=config.savePolicy(org,1,future,future.plusSeconds(1000),policy(team),"Next interval");assertThat(next.version()).isEqualTo(2);assertThat(config.policies(org)).hasSize(2);preference("routing-b",team,null);assertThatThrownBy(()->preference("routing-a",team,null)).hasMessageContaining("changed");}
    @Test void adoptionRequiresFreshShadowAndLegacyComparisonDoesNotMutateOwner(){engine.guardLegacyWrite(caseId);assignOwner(caseId,"routing-b");engine.compareLegacy(caseId,"legacy-1");assertThat(repo.owner(caseId)).isEqualTo("routing-b");assertThat(engine.history(org,caseId)).hasSize(1);capacity("routing-b",0,true);assertThatThrownBy(()->command("ACTIVATE",1,null)).hasMessageContaining("fresh matching");assertThat(repo.facts(caseId).mode()).isEqualTo("SHADOW");}
    @Test void queueManualMoveAndResolutionHistoryAreAudited(){command("SHADOW",0,null);command("ACTIVATE",1,null);Decision d=command("QUEUE",2,null);assertThat(d.path()).isEqualTo("MANUAL_QUEUE");assertThat(repo.owner(caseId)).isNull();Decision assigned=command("ASSIGN",3,"routing-b");assertThat(engine.history(org,caseId)).hasSize(4);String decision=assigned.id().toString();assertThat(count("SELECT COUNT(*) FROM audit_events WHERE entity_id=? AND action='COORDINATOR_ASSIGNMENT_DECIDED'",decision)).isEqualTo(1);assertThat(count("SELECT COUNT(*) FROM audit_events WHERE entity_id=? AND action='COORDINATION_QUEUE_RESOLVED'",decision)).isEqualTo(1);}
    Decision command(String action,long revision,String target){return engine.execute(org,caseId,new Command(UUID.randomUUID().toString(),revision,action,target,action.equals("QUEUE")?team:null,"Reviewed assignment","TEST"));}
    PolicyConfig policy(UUID team){return new PolicyConfig(80,20,true,false,team,Map.of(),team,null,24);}
    void preference(String subject,UUID t,UUID fallback){config.savePreference(org,consultant,0,past,future,subject,t,fallback,"Consultant preference");}
    void capacity(String subject,int max,boolean duty){Capacity c=config.capacities(org).stream().filter(x->x.subject().equals(subject)).findFirst().orElseThrow();config.saveCapacity(org,new Capacity(subject,max,duty,c.languages(),c.careAreas(),c.revision()),"Capacity update");}
    void candidate(String subject,UUID t,int max,boolean duty){actor(subject,org,RECEIVER);config.saveMember(org,t,new Member(subject,past,null,true,false,-1),"Team member");config.saveCapacity(org,new Capacity(subject,max,duty,Set.of("en"),Set.of(),-1),"Initial capacity");}
    UUID organization(){UUID id=UUID.randomUUID();jdbc.update("INSERT INTO provider_organizations(id,legal_name,display_name,organization_type,status,country_code,time_zone,default_currency,legacy_mapping_status,created_by,updated_by,created_at,updated_at,version) VALUES(?,'Test','Test','CLINIC','ONBOARDING','AE','Asia/Dubai','EGP','REVIEWED','TEST','TEST',?,?,0)",id,past,past);return id;}
    UUID clinician(UUID organization){UUID id=UUID.randomUUID();String subject=id.toString();jdbc.update("INSERT INTO practitioner_profiles(id,external_subject,legal_name,display_name,credentialing_status,practitioner_type,availability_status,created_at,updated_at,version) VALUES(?,?,?,?,'UNDER_REVIEW','CONSULTANT','UNAVAILABLE',?,?,0)",id,subject,subject,subject,past,past);jdbc.update("INSERT INTO clinician_onboardings(organization_id,practitioner_id,clinician_type,status,jurisdiction,created_by,updated_by,created_at,updated_at,version) VALUES(?,?,'CONSULTANT','OPERATIONAL_SETUP','AE','TEST','TEST',?,?,0)",organization,id,past,past);return id;}
    UUID medicalCase(UUID doctor){UUID id=UUID.randomUUID();jdbc.update("INSERT INTO medical_cases(id,case_number,full_name,country,whatsapp_number,preferred_language,status,consent_timestamp,created_at,updated_at,version,care_category) VALUES(?,?,'Test','AE','000','en','READY_FOR_CONSULTANT',?,?,?,0,'cardiology')",id,"R-"+id.toString().substring(0,10),past,past,past);jdbc.update("INSERT INTO case_assignments(id,case_id,assignee_subject,assignee_role,assignment_type,status,reason,assigned_by,assigned_at,version) VALUES(?,?,?,'DOCTOR','PRIMARY','ACTIVE','Fixture assignment','TEST',?,0)",UUID.randomUUID(),id,doctor.toString(),past);return id;}
    void actor(String subject,UUID organization,UUID version){jdbc.update("INSERT INTO access_subjects(subject,active,revision) SELECT ?,TRUE,0 WHERE NOT EXISTS(SELECT 1 FROM access_subjects WHERE subject=?)",subject,subject);jdbc.update("INSERT INTO access_memberships(subject,organization_id,status,effective_from,revision,created_by,reason) VALUES(?,?,'ACTIVE',?,0,'TEST','Test')",subject,organization,past);jdbc.update("INSERT INTO role_assignments(id,subject,version_id,organization_id,scope_type,effective_from,status,source,assigned_by,reason,revision) VALUES(?,?,?,?,'ORGANIZATION',?,'ACTIVE','TEST','TEST','Test',0)",UUID.randomUUID(),subject,version,organization,past);jdbc.update("INSERT INTO staff_members(id,external_subject,staff_role,display_name_encrypted,email_encrypted,created_at,updated_at,version) SELECT ?,?,'COORDINATOR',?,?,?, ?,0 WHERE NOT EXISTS(SELECT 1 FROM staff_members WHERE external_subject=?)",UUID.randomUUID(),subject,crypto.encrypt(subject),crypto.encrypt(subject+"@example.test"),past,past,subject);}
    void assignOwner(UUID id,String subject){jdbc.update("INSERT INTO case_assignments(id,case_id,assignee_subject,assignee_role,assignment_type,status,reason,assigned_by,assigned_at,accepted_at,version) VALUES(?,?,?,'COORDINATOR','PRIMARY','ACTIVE','Fixture assignment','TEST',?,?,0)",UUID.randomUUID(),id,subject,past,past);}
    UUID task(String role,String subject){UUID id=UUID.randomUUID();jdbc.update("INSERT INTO case_tasks(id,case_id,task_type,title,owner_subject,owner_role,visibility_scope,priority,status,blocking,created_by,created_at,updated_at,version) VALUES(?,?,'EXISTING',?,?,?,'INTERNAL','NORMAL','OPEN',FALSE,'TEST',?,?,0)",id,caseId,crypto.encrypt("Existing work"),subject,role,past,past);return id;}
    long count(String sql,Object...args){return jdbc.queryForObject(sql,Long.class,args);}
    static void signIn(String subject){Jwt jwt=Jwt.withTokenValue("test").header("alg","none").subject(subject).claim("auth_time",Instant.now().getEpochSecond()).issuedAt(Instant.now()).expiresAt(Instant.now().plusSeconds(3600)).build();SecurityContextHolder.getContext().setAuthentication(new JwtAuthenticationToken(jwt,List.of(),subject));}
}
