package com.rehletshifaa.provider.application;

import com.rehletshifaa.access.application.*;
import com.rehletshifaa.access.domain.*;
import com.rehletshifaa.access.infrastructure.AccessAuditRepository;
import com.rehletshifaa.document.application.*;
import com.rehletshifaa.provider.domain.ClinicianOnboardingStatus;
import com.rehletshifaa.shared.api.ApiException;
import com.rehletshifaa.shared.crypto.CryptoService;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.*;
import java.util.*;
import static com.rehletshifaa.shared.persistence.SqlValues.timestamp;

@Service
public class ProviderCredentialService {
    private final JdbcClient jdbc; private final AuthorizationService authorization; private final StoragePort storage;
    private final DocumentInspectionPort inspector; private final CryptoService crypto; private final AccessAuditRepository audit;
    private final OperationalSetupReadinessPort operational; private final Clock clock; private final long maxBytes;
    private final Set<String> allowedTypes;
    public ProviderCredentialService(JdbcClient jdbc,AuthorizationService authorization,StoragePort storage,
            DocumentInspectionPort inspector,CryptoService crypto,AccessAuditRepository audit,
            OperationalSetupReadinessPort operational,Clock clock,@Value("${app.storage.max-bytes}")long maxBytes,
            @Value("${app.storage.allowed-types}")String allowedTypes){this.jdbc=jdbc;this.authorization=authorization;this.storage=storage;
        this.inspector=inspector;this.crypto=crypto;this.audit=audit;this.operational=operational;this.clock=clock;this.maxBytes=maxBytes;
        this.allowedTypes=Set.of(allowedTypes.split(","));}

    public OnboardingView onboarding(UUID organization,UUID practitioner){var c=clinician(organization,practitioner,false);authorizeAny("provider.view",context(c));return c;}

    @Transactional
    public OnboardingView completeProfile(UUID organization,UUID practitioner,ProfileCommand command){var c=clinician(organization,practitioner,true);
        var actor=authorizeAny("provider.update",context(c));required(command.registrationNumber(),100,"registration number");required(command.specialty(),120,"specialty");
        required(command.qualifications(),4000,"qualifications");String jurisdiction=jurisdiction(command.jurisdiction());
        if(c.status()==ClinicianOnboardingStatus.OFFBOARDED)conflict("OFFBOARDED_ONBOARDING","An offboarded clinician cannot resume onboarding");
        jdbc.sql("UPDATE practitioner_profiles SET registration_number=?,specialty=?,subspecialty=?,qualifications=?,updated_at=?,version=version+1 WHERE id=?")
                .params(command.registrationNumber().trim(),command.specialty().trim(),clean(command.subspecialty()),command.qualifications().trim(),timestamp(clock.instant()),practitioner).update();
        int changed=jdbc.sql("UPDATE clinician_onboardings SET jurisdiction=?,profile_completed_at=?,status=CASE WHEN status IN ('INVITED','PROFILE_INCOMPLETE','LEGACY_UNREVIEWED') THEN 'PROFILE_INCOMPLETE' ELSE status END,updated_by=?,updated_at=?,version=version+1 WHERE organization_id=? AND practitioner_id=? AND version=?")
                .params(jurisdiction,timestamp(clock.instant()),actor.subject(),timestamp(clock.instant()),organization,practitioner,command.version()).update();
        if(changed!=1)conflict("STALE_ONBOARDING","Onboarding changed; reload before saving the profile");
        audit.record(actor.subject(),practitioner.toString(),"CLINICIAN_PROFILE_COMPLETED","SUCCESS","organization="+organization);
        return clinician(organization,practitioner,false);
    }

    public List<Requirement> requirements(UUID organization,UUID practitioner){var c=clinician(organization,practitioner,false);authorizeAny("credential.view",context(c));return policy(c).requirements();}

    @Transactional
    public EvidenceUpload presign(UUID organization,UUID practitioner,EvidenceCommand command){var c=clinician(organization,practitioner,true);var actor=authorizeAny("credential.submit",context(c));
        required(command.fileName(),255,"file name");if(!allowedTypes.contains(command.contentType())||command.sizeBytes()<=0||command.sizeBytes()>maxBytes)throw new ApiException(422,"INVALID_CREDENTIAL_EVIDENCE","Upload a supported credential document within the size limit");
        long count=jdbc.sql("SELECT COUNT(*) FROM provider_credential_evidence WHERE organization_id=? AND practitioner_id=? AND scan_status IN ('PENDING','QUARANTINED','CLEAN')").params(organization,practitioner).query(Long.class).single();
        if(count>=25)conflict("CREDENTIAL_EVIDENCE_QUOTA","This credential dossier has reached its document limit");
        UUID id=UUID.randomUUID();String key="provider-credential-staging/"+organization+"/"+UUID.randomUUID();String safe=safeName(command.fileName());Instant now=clock.instant();
        jdbc.sql("INSERT INTO provider_credential_evidence(id,organization_id,practitioner_id,staging_object_key,safe_file_name,declared_content_type,expected_size,scan_status,uploaded_by,created_at,version) VALUES(?,?,?,?,?,?,?,'PENDING',?,?,0)")
                .params(id,organization,practitioner,key,safe,command.contentType(),command.sizeBytes(),actor.subject(),timestamp(now)).update();
        var upload=storage.presign(key,command.contentType(),command.sizeBytes());audit.record(actor.subject(),id.toString(),"CREDENTIAL_EVIDENCE_UPLOAD_STARTED","SUCCESS","organization="+organization);
        return new EvidenceUpload(id,upload.url(),upload.requiredHeaders(),upload.expiresInSeconds(),"PENDING");
    }

    @Transactional(noRollbackFor=EvidenceRejectedException.class)
    public EvidenceView confirm(UUID organization,UUID evidenceId,long version){Evidence e=evidence(organization,evidenceId,true);var c=clinician(organization,e.practitionerId(),false);var actor=authorizeAny("credential.submit",context(c));
        if(e.status().equals("CLEAN"))return evidenceView(e);if(!e.status().equals("PENDING"))conflict("EVIDENCE_NOT_CONFIRMABLE","Credential evidence cannot be confirmed in its current state");
        var metadata=storage.verify(e.stagingKey());if(metadata.sizeBytes()!=e.expectedSize()||!e.contentType().equalsIgnoreCase(metadata.contentType()))conflict("UPLOAD_METADATA_MISMATCH","Uploaded credential evidence does not match the declared metadata");
        byte[] bytes=storage.read(e.stagingKey(),maxBytes);var inspection=inspector.inspect(bytes,e.contentType());
        if(inspection.retryable())throw new ApiException(503,"EVIDENCE_SCAN_UNAVAILABLE","Credential evidence inspection is temporarily unavailable; retry shortly"); // stays PENDING with its staged upload
        if(!inspection.clean()){jdbc.sql("UPDATE provider_credential_evidence SET scan_status='REJECTED',scan_reason=?,scanned_at=?,version=version+1 WHERE id=? AND version=?").params(limit(inspection.reasonCode(),100),timestamp(clock.instant()),evidenceId,version).update();storage.delete(e.stagingKey());throw new EvidenceRejectedException();}
        String finalKey="provider-credential-evidence/"+organization+"/"+UUID.randomUUID();storage.seal(finalKey,bytes,metadata.contentType());String digest=sha256(bytes);Instant now=clock.instant();
        int changed=jdbc.sql("UPDATE provider_credential_evidence SET staging_object_key=NULL,sealed_object_key=?,actual_content_type=?,actual_size=?,sha256=?,scan_status='CLEAN',scan_reason='CLEAN',scanned_at=?,sealed_at=?,version=version+1 WHERE id=? AND version=? AND scan_status='PENDING'")
                .params(finalKey,metadata.contentType(),metadata.sizeBytes(),digest,timestamp(now),timestamp(now),evidenceId,version).update();
        if(changed!=1){storage.delete(finalKey);conflict("STALE_EVIDENCE","Credential evidence changed; reload before confirming");}storage.delete(e.stagingKey());audit.record(actor.subject(),evidenceId.toString(),"CREDENTIAL_EVIDENCE_SEALED","SUCCESS","organization="+organization+"; sha256="+digest);
        return evidenceView(evidence(organization,evidenceId,false));
    }

    public DocumentAccess viewEvidence(UUID organization,UUID evidenceId){Evidence e=evidence(organization,evidenceId,false);var c=clinician(organization,e.practitionerId(),false);var actor=authorizeAny("credential.view",context(c));if(!e.status().equals("CLEAN"))throw new ApiException(404,"EVIDENCE_NOT_FOUND","Credential evidence is not available");
        var value=storage.presignView(e.sealedKey(),e.safeName());audit.record(actor.subject(),evidenceId.toString(),"CREDENTIAL_EVIDENCE_VIEWED","SUCCESS","organization="+organization);return new DocumentAccess(value.url(),value.expiresInSeconds());}

    @Transactional
    public RevisionView submit(UUID organization,UUID practitioner,SubmissionCommand command,String idempotencyKey){var c=clinician(organization,practitioner,true);var actor=authorizeAny("credential.submit",context(c));required(idempotencyKey,160,"idempotency key");required(command.credentialType(),60,"credential type");
        required(command.issuer(),300,"issuer");required(command.referenceNumber(),200,"reference number");var policy=policy(c);Requirement requirement=policy.require(command.credentialType());
        if(requirement.expiryRequired()&&(command.expiresAt()==null||!command.expiresAt().isAfter(clock.instant())))throw new ApiException(400,"VALID_EXPIRY_REQUIRED","A future expiry date is required for this credential");
        Evidence e=evidence(organization,command.evidenceId(),true);if(!e.practitionerId().equals(practitioner)||!e.status().equals("CLEAN"))throw new ApiException(404,"EVIDENCE_NOT_FOUND","Clean evidence for this clinician was not found");
        String hash=sha256((command.toString()).getBytes(StandardCharsets.UTF_8));var replay=replay(organization,actor.subject(),"CREDENTIAL_SUBMIT",idempotencyKey,hash);if(replay.isPresent())return revision(UUID.fromString(replay.get()),organization,false);
        UUID dossier=jdbc.sql("SELECT id FROM provider_credential_dossiers WHERE organization_id=? AND practitioner_id=? AND credential_type=? FOR UPDATE").params(organization,practitioner,command.credentialType()).query(UUID.class).optional().orElseGet(()->{UUID id=UUID.randomUUID();Instant now=clock.instant();jdbc.sql("INSERT INTO provider_credential_dossiers(id,organization_id,practitioner_id,credential_type,status,created_by,created_at,updated_at,version) VALUES(?,?,?,?,'OPEN',?,?,?,0)").params(id,organization,practitioner,command.credentialType(),actor.subject(),timestamp(now),timestamp(now)).update();return id;});
        int number=jdbc.sql("SELECT COALESCE(MAX(revision_number),0)+1 FROM provider_credential_revisions WHERE dossier_id=?").param(dossier).query(Integer.class).single();UUID id=UUID.randomUUID();Instant now=clock.instant();
        jdbc.sql("INSERT INTO provider_credential_revisions(id,dossier_id,revision_number,policy_version_id,issuer_encrypted,reference_number_encrypted,jurisdiction,issued_at,expires_at,status,submitted_by,submitted_at,version) VALUES(?,?,?,?,?,?,?,?,?,'SUBMITTED',?,?,0)")
                .params(id,dossier,number,policy.id(),crypto.encrypt(command.issuer().trim()),crypto.encrypt(command.referenceNumber().trim()),c.jurisdiction(),timestamp(command.issuedAt()),timestamp(command.expiresAt()),actor.subject(),timestamp(now)).update();
        jdbc.sql("INSERT INTO provider_credential_revision_evidence(revision_id,evidence_id) VALUES(?,?)").params(id,e.id()).update();
        jdbc.sql("UPDATE clinician_onboardings SET status='DOCUMENTS_SUBMITTED',updated_by=?,updated_at=?,version=version+1 WHERE organization_id=? AND practitioner_id=? AND status NOT IN ('SUSPENDED','OFFBOARDED')").params(actor.subject(),timestamp(now),organization,practitioner).update();
        remember(organization,actor.subject(),"CREDENTIAL_SUBMIT",practitioner.toString(),idempotencyKey,hash,id.toString(),"SUBMITTED");event(organization,"CREDENTIAL_REVISION",id,"CREDENTIAL_SUBMITTED","credential-submitted:"+id,actor.subject());audit.record(actor.subject(),id.toString(),number==1?"CREDENTIAL_SUBMITTED":"CREDENTIAL_REPLACEMENT_SUBMITTED","SUCCESS","organization="+organization+"; type="+command.credentialType()+"; revision="+number);
        return revision(id,organization,false);
    }

    public List<RevisionView> list(UUID organization,UUID practitioner){var c=clinician(organization,practitioner,false);authorizeAny("credential.view",context(c));return jdbc.sql("SELECT r.id FROM provider_credential_revisions r JOIN provider_credential_dossiers d ON d.id=r.dossier_id WHERE d.organization_id=? AND d.practitioner_id=? ORDER BY r.submitted_at DESC").params(organization,practitioner).query(UUID.class).list().stream().map(id->revision(id,organization,false)).toList();}
    public RevisionView reviewDetail(UUID organization,UUID revisionId){RevisionView r=revision(revisionId,organization,false);authorizeAny("credential.view",context(clinician(organization,r.practitionerId(),false)));return r;}
    public List<RevisionView> queue(UUID organization){organization(organization);authorizeAny("credential.review",new ResourceContext(organization,true,"PROVIDER_ORGANIZATION",organization.toString(),null,false));return jdbc.sql("SELECT r.id FROM provider_credential_revisions r JOIN provider_credential_dossiers d ON d.id=r.dossier_id WHERE d.organization_id=? AND r.status IN ('SUBMITTED','UNDER_REVIEW') ORDER BY r.submitted_at").param(organization).query(UUID.class).list().stream().map(id->revision(id,organization,false)).toList();}

    @Transactional
    public RevisionView decide(UUID organization,UUID revisionId,DecisionCommand command,String idempotencyKey){RevisionView current=revision(revisionId,organization,true);String permission=switch(command.decision()){case "START_REVIEW"->"credential.review";case "VERIFY"->"credential.verify";case "REQUEST_INFORMATION"->"credential.request_information";case "REJECT"->"credential.reject";case "SUSPEND","RESTORE"->"credential.suspend";default->throw new ApiException(400,"INVALID_CREDENTIAL_DECISION","Select a supported credential decision");};
        var actor=authorizeAny(permission,new ResourceContext(organization,true,"CREDENTIAL_REVISION",revisionId.toString(),current.ownerSubject(),false));
        if(actor.subject().equals(current.ownerSubject()))throw new ApiException(403,"SELF_VERIFICATION_PROHIBITED","A clinician cannot review their own credential");
        if(actor.subject().equals(current.submittedBy()))throw new ApiException(403,"SUBMITTER_REVIEW_PROHIBITED","The submitter cannot review this credential revision");required(idempotencyKey,160,"idempotency key");
        if(!command.decision().equals("START_REVIEW")&&(command.reason()==null||command.reason().isBlank()))throw new ApiException(400,"DECISION_REASON_REQUIRED","A review basis or reason is required");String hash=sha256(command.toString().getBytes(StandardCharsets.UTF_8));var replay=replay(organization,actor.subject(),"CREDENTIAL_"+command.decision(),idempotencyKey,hash);if(replay.isPresent())return revision(revisionId,organization,false);
        String target=switch(command.decision()){case "START_REVIEW"->"UNDER_REVIEW";case "VERIFY"->"VERIFIED";case "REQUEST_INFORMATION"->"MORE_INFORMATION_REQUIRED";case "REJECT"->"REJECTED";case "SUSPEND"->"SUSPENDED";case "RESTORE"->"VERIFIED";default->throw new IllegalStateException();};
        Set<String> allowed=switch(command.decision()){case "START_REVIEW"->Set.of("SUBMITTED");case "VERIFY","REQUEST_INFORMATION","REJECT"->Set.of("UNDER_REVIEW");case "SUSPEND"->Set.of("VERIFIED");case "RESTORE"->Set.of("SUSPENDED");default->Set.of();};if(!allowed.contains(current.status()))conflict("CREDENTIAL_STATE_CONFLICT","Credential revision is not in a state that permits this decision");
        int changed=jdbc.sql("UPDATE provider_credential_revisions SET status=?,reviewed_by=?,reviewed_at=?,review_reason_encrypted=?,version=version+1 WHERE id=? AND version=?")
                .params(target,actor.subject(),timestamp(clock.instant()),crypto.encrypt(clean(command.reason())),revisionId,command.version()).update();if(changed!=1)conflict("STALE_CREDENTIAL_REVISION","Credential revision changed; reload before deciding");
        UUID decisionId=UUID.randomUUID();jdbc.sql("INSERT INTO provider_credential_decisions(id,organization_id,dossier_id,revision_id,decision,actor_subject,reason_encrypted,policy_version_id,decided_at) VALUES(?,?,?,?,?,?,?,?,?)")
                .params(decisionId,organization,current.dossierId(),revisionId,decisionName(command.decision()),actor.subject(),crypto.encrypt(clean(command.reason())),current.policyVersionId(),timestamp(clock.instant())).update();
        if(command.decision().equals("RESTORE"))jdbc.sql("UPDATE provider_credential_dossiers SET status='VERIFIED',suspended_reason_encrypted=NULL,updated_at=?,version=version+1 WHERE id=?").params(timestamp(clock.instant()),current.dossierId()).update();
        else if(target.equals("VERIFIED"))jdbc.sql("UPDATE provider_credential_dossiers SET status='VERIFIED',updated_at=?,version=version+1 WHERE id=?").params(timestamp(clock.instant()),current.dossierId()).update();
        else if(target.equals("SUSPENDED"))jdbc.sql("UPDATE provider_credential_dossiers SET status='SUSPENDED',suspended_reason_encrypted=?,updated_at=?,version=version+1 WHERE id=?").params(crypto.encrypt(command.reason()),timestamp(clock.instant()),current.dossierId()).update();
        updateOnboardingAfterDecision(organization,current.practitionerId(),target,actor.subject());remember(organization,actor.subject(),"CREDENTIAL_"+command.decision(),revisionId.toString(),idempotencyKey,hash,revisionId.toString(),target);event(organization,"CREDENTIAL_REVISION",revisionId,"CREDENTIAL_"+decisionName(command.decision()),"credential-decision:"+decisionId,actor.subject());notifyClinician(current.practitionerId(),revisionId,target,decisionId);audit.record(actor.subject(),revisionId.toString(),"CREDENTIAL_"+decisionName(command.decision()),"SUCCESS","organization="+organization+"; status="+target);
        return revision(revisionId,organization,false);
    }

    public Readiness readiness(UUID organization,UUID practitioner){var c=clinician(organization,practitioner,false);authorizeAny("provider.view",context(c));return computeReadiness(c,true);}

    @Transactional
    public Readiness adoptLegacyMapping(UUID organization,UUID practitioner,long version,String reason,String idempotencyKey){var c=clinician(organization,practitioner,true);var actor=authorizeAny("provider.activate",context(c));required(reason,500,"adoption reason");required(idempotencyKey,160,"idempotency key");String hash=sha256((organization+":"+practitioner+":"+version+":"+reason.trim()).getBytes(StandardCharsets.UTF_8));var replay=replay(organization,actor.subject(),"LEGACY_CREDENTIAL_ADOPT",idempotencyKey,hash);if(replay.isPresent())return computeReadiness(clinician(organization,practitioner,false),true);
        var mapping=jdbc.sql("SELECT legacy_practitioner_id,legacy_mapping_status FROM provider_organizations WHERE id=? FOR UPDATE").param(organization).query((r,n)->new LegacyMapping(r.getObject(1,UUID.class),r.getString(2))).optional().orElseThrow();
        if(mapping.practitionerId()==null||!mapping.practitionerId().equals(practitioner))throw new ApiException(409,"LEGACY_MAPPING_NOT_APPLICABLE","This provider is not the reviewed legacy mapping for the clinician");
        if(!credentialRequirementsSatisfied(organization,practitioner))throw new ApiException(409,"LEGACY_ADOPTION_NOT_READY","Submit and independently verify every required credential before adopting the legacy mapping");
        int changed=jdbc.sql("UPDATE clinician_onboardings SET credential_policy_cutover_at=COALESCE(credential_policy_cutover_at,?),updated_by=?,updated_at=?,version=version+1 WHERE organization_id=? AND practitioner_id=? AND version=?").params(timestamp(clock.instant()),actor.subject(),timestamp(clock.instant()),organization,practitioner,version).update();if(changed!=1)conflict("STALE_ONBOARDING","Onboarding changed; reload before adopting the legacy mapping");
        jdbc.sql("UPDATE provider_organizations SET legacy_mapping_status='REVIEWED',updated_by=?,updated_at=?,version=version+1 WHERE id=? AND legacy_mapping_status='PENDING_REVIEW'").params(actor.subject(),timestamp(clock.instant()),organization).update();remember(organization,actor.subject(),"LEGACY_CREDENTIAL_ADOPT",practitioner.toString(),idempotencyKey,hash,practitioner.toString(),"REVIEWED");event(organization,"CLINICIAN",practitioner,"LEGACY_CREDENTIAL_POLICY_ADOPTED","legacy-credential-adopted:"+organization+":"+practitioner,actor.subject());audit.record(actor.subject(),practitioner.toString(),"LEGACY_CREDENTIAL_POLICY_ADOPTED","SUCCESS","organization="+organization+"; "+reason.trim());return computeReadiness(clinician(organization,practitioner,false),true);}

    @Transactional
    public ProviderActivation activateProvider(UUID organization,long version,String idempotencyKey){organization(organization);var resource=new ResourceContext(organization,true,"PROVIDER_ORGANIZATION",organization.toString(),null,false);var actor=authorizeAny("provider.activate",resource);required(idempotencyKey,160,"idempotency key");String hash=sha256((organization+":"+version).getBytes(StandardCharsets.UTF_8));var replay=replay(organization,actor.subject(),"PROVIDER_ACTIVATE",idempotencyKey,hash);if(replay.isPresent())return new ProviderActivation(organization,organizationStatus(organization),true);
        String status=jdbc.sql("SELECT status FROM provider_organizations WHERE id=? FOR UPDATE").param(organization).query(String.class).single();if(status.equals("ACTIVE"))return new ProviderActivation(organization,"ACTIVE",true);
        boolean owner=jdbc.sql("SELECT COUNT(*) FROM role_assignments a JOIN role_template_versions v ON v.id=a.version_id JOIN role_templates t ON t.id=v.template_id JOIN access_memberships m ON m.subject=a.subject AND m.organization_id=a.organization_id WHERE a.organization_id=? AND t.template_key='ORGANIZATION_OWNER' AND a.status='ACTIVE' AND m.status='ACTIVE'").param(organization).query(Long.class).single()>0;if(!owner)conflict("READINESS_BLOCKERS","Provider activation is blocked: an active Organization Owner is required.");
        List<UUID> clinicians=jdbc.sql("SELECT practitioner_id FROM clinician_onboardings WHERE organization_id=? AND status NOT IN ('SUSPENDED','OFFBOARDED')").param(organization).query(UUID.class).list();boolean eligible=clinicians.stream().map(id->computeReadiness(clinician(organization,id,false),true)).anyMatch(Readiness::readyForActivation);if(!eligible)conflict("READINESS_BLOCKERS","Provider activation is blocked: at least one clinician must satisfy credential and operational readiness.");
        int changed=jdbc.sql("UPDATE provider_organizations SET status='ACTIVE',updated_by=?,updated_at=?,version=version+1 WHERE id=? AND version=? AND status NOT IN ('SUSPENDED','OFFBOARDED','ACTIVE')").params(actor.subject(),timestamp(clock.instant()),organization,version).update();if(changed!=1)conflict("STALE_PROVIDER","Provider changed; reload before activation");remember(organization,actor.subject(),"PROVIDER_ACTIVATE",organization.toString(),idempotencyKey,hash,organization.toString(),"ACTIVE");event(organization,"PROVIDER_ORGANIZATION",organization,"PROVIDER_ACTIVATED","provider-activated:"+organization,actor.subject());audit.record(actor.subject(),organization.toString(),"PROVIDER_ACTIVATED","SUCCESS","readiness-gated activation");return new ProviderActivation(organization,"ACTIVE",false);}

    @Transactional
    public Readiness activateClinician(UUID organization,UUID practitioner,long version,String idempotencyKey){var c=clinician(organization,practitioner,true);var actor=authorizeAny("provider.activate",context(c));required(idempotencyKey,160,"idempotency key");String hash=sha256((organization+":"+practitioner+":"+version).getBytes(StandardCharsets.UTF_8));var replay=replay(organization,actor.subject(),"CLINICIAN_ACTIVATE",idempotencyKey,hash);if(replay.isPresent())return computeReadiness(clinician(organization,practitioner,false),true);Readiness ready=computeReadiness(c,true);if(!ready.readyForActivation())throw new ApiException(409,"READINESS_BLOCKERS","Clinician activation is blocked: "+ready.blockers().stream().map(Blocker::message).findFirst().orElse("requirements remain"));
        if(!"ACTIVE".equals(organizationStatus(organization)))conflict("PROVIDER_NOT_ACTIVE","The provider organization must be active before clinician activation");int changed=jdbc.sql("UPDATE clinician_onboardings SET status='ACTIVE',activated_at=?,updated_by=?,updated_at=?,version=version+1 WHERE organization_id=? AND practitioner_id=? AND version=? AND status<>'ACTIVE'").params(timestamp(clock.instant()),actor.subject(),timestamp(clock.instant()),organization,practitioner,version).update();if(changed==0&&c.status()!=ClinicianOnboardingStatus.ACTIVE)conflict("STALE_ONBOARDING","Onboarding changed; reload before activation");remember(organization,actor.subject(),"CLINICIAN_ACTIVATE",practitioner.toString(),idempotencyKey,hash,practitioner.toString(),"ACTIVE");event(organization,"CLINICIAN",practitioner,"CLINICIAN_ACTIVATED","clinician-activated:"+organization+":"+practitioner,actor.subject());audit.record(actor.subject(),practitioner.toString(),"CLINICIAN_ACTIVATED","SUCCESS","organization="+organization);return computeReadiness(clinician(organization,practitioner,false),true);}

    private Readiness computeReadiness(OnboardingView c,boolean includeOperational){List<Blocker> blockers=new ArrayList<>();boolean identity=c.ownerSubject()!=null&&!c.ownerSubject().isBlank();if(!identity)blockers.add(block("IDENTITY_NOT_PROVISIONED","Authentication identity has not been linked."));boolean member=jdbc.sql("SELECT COUNT(*) FROM access_memberships WHERE subject=? AND organization_id=? AND status='ACTIVE' AND effective_from<=? AND (effective_to IS NULL OR effective_to>?)").params(c.ownerSubject(),c.organizationId(),timestamp(clock.instant()),timestamp(clock.instant())).query(Long.class).single()>0;if(!member)blockers.add(block("MEMBERSHIP_INACTIVE","Organization membership is not active."));boolean providerComplete=jdbc.sql("SELECT COUNT(*) FROM provider_organizations WHERE id=? AND legal_name IS NOT NULL AND display_name IS NOT NULL AND country_code IS NOT NULL AND time_zone IS NOT NULL AND default_currency IS NOT NULL AND legacy_mapping_status IS DISTINCT FROM 'PENDING_REVIEW'").param(c.organizationId()).query(Long.class).single()>0;if(!providerComplete)blockers.add(block("PROVIDER_PROFILE_INCOMPLETE","Provider profile or legacy mapping review is incomplete."));
        boolean profile=jdbc.sql("SELECT COUNT(*) FROM practitioner_profiles WHERE id=? AND registration_number IS NOT NULL AND specialty IS NOT NULL AND qualifications IS NOT NULL").param(c.practitionerId()).query(Long.class).single()>0;if(!profile)blockers.add(block("CLINICIAN_PROFILE_INCOMPLETE","Clinician profile information is incomplete."));Policy p=null;try{p=policy(c);}catch(ApiException ex){blockers.add(block("CREDENTIAL_POLICY_UNCONFIGURED","Credential requirements are not configured for this clinician type and jurisdiction."));}
        boolean submitted=false,verified=false,unexpired=false;if(p!=null){submitted=true;verified=true;unexpired=true;for(Requirement req:p.requirements()){List<RevisionView> rows=revisionsFor(c,req.type());if(rows.isEmpty()){submitted=false;verified=false;unexpired=false;blockers.add(block("CREDENTIAL_MISSING",req.displayName()+" has not been submitted."));continue;}boolean ok=rows.stream().anyMatch(r->r.status().equals("VERIFIED")&&(r.expiresAt()==null||r.expiresAt().isAfter(clock.instant()))&&r.dossierStatus().equals("VERIFIED"));if(!ok){verified=false;if(rows.stream().anyMatch(r->r.status().equals("VERIFIED")&&r.expiresAt()!=null&&!r.expiresAt().isAfter(clock.instant()))){unexpired=false;blockers.add(block("CREDENTIAL_EXPIRED",req.displayName()+" has expired."));}else blockers.add(block("CREDENTIAL_AWAITING_VERIFICATION",req.displayName()+" is awaiting verification."));}}}
        boolean relationships=true;if(c.clinicianType().equals("ASSOCIATE_DOCTOR")){relationships=hasEligibleSupervisor(c);if(!relationships)blockers.add(block("SUPERVISION_REQUIRED","Associate Doctor requires an active, credential-ready supervising Consultant in this organization."));}
        var setup=operational.evaluate(c.organizationId(),c.practitionerId());if(includeOperational&&!setup.available())blockers.add(block("OPERATIONAL_SETUP_UNAVAILABLE",setup.blockers().isEmpty()?"Operational setup is not yet available.":setup.blockers().get(0)));else if(includeOperational){if(!setup.servicesAndPricingComplete())blockers.add(block("SERVICES_PRICING_INCOMPLETE","At least one active price is required for the clinician's enabled services."));if(setup.availabilityRequired()&&!setup.availabilityComplete())blockers.add(block("AVAILABILITY_INCOMPLETE","Clinician availability has not been configured."));if(!setup.routingComplete())blockers.add(block("ROUTING_INCOMPLETE","Routing preference or supported platform default is missing."));if(!setup.commercialAcceptanceComplete())blockers.add(block("COMMERCIAL_ACCEPTANCE_MISSING","Required commercial or legal acceptance is missing."));}
        boolean credentialReady=identity&&member&&profile&&submitted&&verified&&unexpired&&relationships&&c.status()!=ClinicianOnboardingStatus.SUSPENDED&&c.status()!=ClinicianOnboardingStatus.OFFBOARDED;boolean ready=credentialReady&&providerComplete&&setup.available()&&setup.servicesAndPricingComplete()&&(!setup.availabilityRequired()||setup.availabilityComplete())&&setup.routingComplete()&&setup.commercialAcceptanceComplete();return new Readiness(identity,member,providerComplete,profile,submitted,verified,unexpired,relationships,true,setup.servicesAndPricingComplete(),setup.availabilityRequired(),setup.availabilityComplete(),credentialReady,List.copyOf(blockers),ready,clock.instant());}

    private boolean hasEligibleSupervisor(OnboardingView associate){
        Instant now=clock.instant();
        List<UUID> supervisors=jdbc.sql("SELECT DISTINCT source_d.practitioner_id FROM resource_relationships r JOIN provider_membership_details source_d ON source_d.organization_id=r.organization_id AND source_d.subject=r.subject JOIN access_memberships source_m ON source_m.organization_id=r.organization_id AND source_m.subject=r.subject JOIN role_assignments a ON a.organization_id=r.organization_id AND a.subject=r.subject JOIN role_template_versions v ON v.id=a.version_id JOIN role_templates t ON t.id=v.template_id JOIN clinician_onboardings o ON o.organization_id=r.organization_id AND o.practitioner_id=source_d.practitioner_id WHERE r.organization_id=? AND r.target_type='CLINICIAN' AND r.target_id=? AND r.relationship_type='SUPERVISES' AND r.status='ACTIVE' AND r.effective_from<=? AND (r.effective_to IS NULL OR r.effective_to>?) AND source_m.status='ACTIVE' AND source_m.effective_from<=? AND (source_m.effective_to IS NULL OR source_m.effective_to>?) AND a.status='ACTIVE' AND a.effective_from<=? AND (a.effective_to IS NULL OR a.effective_to>?) AND v.status='PUBLISHED' AND v.effective_from<=? AND t.template_key='CONSULTANT' AND o.clinician_type='CONSULTANT'")
                .params(associate.organizationId(),associate.practitionerId().toString(),timestamp(now),timestamp(now),timestamp(now),timestamp(now),timestamp(now),timestamp(now),timestamp(now))
                .query(UUID.class).list();
        return supervisors.stream().map(id->computeReadiness(clinician(associate.organizationId(),id,false),false)).anyMatch(Readiness::credentialReady);
    }

    private void updateOnboardingAfterDecision(UUID org,UUID practitioner,String target,String actor){boolean satisfied=credentialRequirementsSatisfied(org,practitioner);String status=switch(target){case "UNDER_REVIEW"->"UNDER_VERIFICATION";case "MORE_INFORMATION_REQUIRED"->satisfied?"VERIFIED":"MORE_INFORMATION_REQUIRED";case "REJECTED"->satisfied?"VERIFIED":"REJECTED";case "SUSPENDED"->"SUSPENDED";case "VERIFIED"->satisfied?"VERIFIED":null;default->null;};if(status!=null)jdbc.sql("UPDATE clinician_onboardings SET status=?,verified_at=CASE WHEN ?='VERIFIED' THEN COALESCE(verified_at,?) ELSE verified_at END,suspended_at=CASE WHEN ?='SUSPENDED' THEN ? ELSE suspended_at END,updated_by=?,updated_at=?,version=version+1 WHERE organization_id=? AND practitioner_id=? AND status<>'OFFBOARDED'").params(status,status,timestamp(clock.instant()),status,timestamp(clock.instant()),actor,timestamp(clock.instant()),org,practitioner).update();}
    private boolean credentialRequirementsSatisfied(UUID org,UUID practitioner){OnboardingView c=clinician(org,practitioner,false);Policy p=policy(c);return p.requirements().stream().allMatch(req->revisionsFor(c,req.type()).stream().anyMatch(r->r.status().equals("VERIFIED")&&(r.expiresAt()==null||r.expiresAt().isAfter(clock.instant()))&&r.dossierStatus().equals("VERIFIED")));}
    private List<RevisionView> revisionsFor(OnboardingView c,String type){return jdbc.sql("SELECT r.id FROM provider_credential_revisions r JOIN provider_credential_dossiers d ON d.id=r.dossier_id WHERE d.organization_id=? AND d.practitioner_id=? AND d.credential_type=? ORDER BY r.revision_number DESC").params(c.organizationId(),c.practitionerId(),type).query(UUID.class).list().stream().map(id->revision(id,c.organizationId(),false)).toList();}
    private Policy policy(OnboardingView c){if(c.jurisdiction()==null)throw new ApiException(409,"CREDENTIAL_POLICY_UNCONFIGURED","Credential policy is not configured");return jdbc.sql("SELECT id FROM credential_policy_versions WHERE clinician_type=? AND jurisdiction=? AND status='PUBLISHED' AND effective_from<=? AND (retired_at IS NULL OR retired_at>?) ORDER BY version_number DESC LIMIT 1").params(c.clinicianType(),c.jurisdiction(),timestamp(clock.instant()),timestamp(clock.instant())).query(UUID.class).optional().map(id->new Policy(id,jdbc.sql("SELECT credential_type,display_name,mandatory,expiry_required FROM credential_policy_requirements WHERE policy_version_id=? ORDER BY credential_type").param(id).query((r,n)->new Requirement(r.getString(1),r.getString(2),r.getBoolean(3),r.getBoolean(4))).list())).orElseThrow(()->new ApiException(409,"CREDENTIAL_POLICY_UNCONFIGURED","Credential policy is not configured"));}
    private OnboardingView clinician(UUID org,UUID practitioner,boolean lock){organization(org);return jdbc.sql("SELECT o.organization_id,o.practitioner_id,o.clinician_type,o.status,o.jurisdiction,o.version,p.external_subject FROM clinician_onboardings o JOIN practitioner_profiles p ON p.id=o.practitioner_id WHERE o.organization_id=? AND o.practitioner_id=?"+(lock?" FOR UPDATE":"")).params(org,practitioner).query((r,n)->new OnboardingView(r.getObject(1,UUID.class),r.getObject(2,UUID.class),r.getString(3),ClinicianOnboardingStatus.valueOf(r.getString(4)),r.getString(5),r.getLong(6),r.getString(7))).optional().orElseThrow(()->new ApiException(404,"CLINICIAN_ONBOARDING_NOT_FOUND","Clinician onboarding was not found"));}
    private void organization(UUID org){if(jdbc.sql("SELECT COUNT(*) FROM provider_organizations WHERE id=? AND status<>'OFFBOARDED'").param(org).query(Long.class).single()==0)throw new ApiException(404,"PROVIDER_NOT_FOUND","Provider organization not found");}
    private String organizationStatus(UUID org){return jdbc.sql("SELECT status FROM provider_organizations WHERE id=?").param(org).query(String.class).single();}
    private Evidence evidence(UUID org,UUID id,boolean lock){return jdbc.sql("SELECT * FROM provider_credential_evidence WHERE organization_id=? AND id=?"+(lock?" FOR UPDATE":"")).params(org,id).query(this::mapEvidence).optional().orElseThrow(()->new ApiException(404,"EVIDENCE_NOT_FOUND","Credential evidence was not found"));}
    private Evidence mapEvidence(ResultSet r,int n)throws SQLException{return new Evidence(r.getObject("id",UUID.class),r.getObject("organization_id",UUID.class),r.getObject("practitioner_id",UUID.class),r.getString("staging_object_key"),r.getString("sealed_object_key"),r.getString("safe_file_name"),r.getString("declared_content_type"),r.getLong("expected_size"),r.getString("scan_status"),r.getLong("version"));}
    private RevisionView revision(UUID id,UUID org,boolean lock){return jdbc.sql("SELECT r.*,d.organization_id,d.practitioner_id,d.credential_type,d.status dossier_status,p.external_subject FROM provider_credential_revisions r JOIN provider_credential_dossiers d ON d.id=r.dossier_id JOIN practitioner_profiles p ON p.id=d.practitioner_id WHERE r.id=? AND d.organization_id=?"+(lock?" FOR UPDATE":"")).params(id,org).query((r,n)->new RevisionView(r.getObject("id",UUID.class),r.getObject("dossier_id",UUID.class),r.getObject("organization_id",UUID.class),r.getObject("practitioner_id",UUID.class),r.getString("external_subject"),r.getString("credential_type"),r.getInt("revision_number"),r.getObject("policy_version_id",UUID.class),r.getString("status"),r.getString("dossier_status"),instant(r,"expires_at"),r.getString("submitted_by"),instant(r,"submitted_at"),r.getLong("version"),evidenceIds(id))).optional().orElseThrow(()->new ApiException(404,"CREDENTIAL_REVISION_NOT_FOUND","Credential revision was not found"));}
    private List<UUID> evidenceIds(UUID revisionId){return jdbc.sql("SELECT evidence_id FROM provider_credential_revision_evidence WHERE revision_id=?").param(revisionId).query(UUID.class).list();}
    private AccessIdentity.Identity authorizeAny(String permission,ResourceContext context){ApiException last=null;for(var channel:new ChannelEntitlement[]{ChannelEntitlement.ADMIN_WEB,ChannelEntitlement.CONSULTANT_WEB,ChannelEntitlement.API})try{return authorization.require(permission,context,channel);}catch(ApiException ex){last=ex;}throw last;}
    private ResourceContext context(OnboardingView c){return new ResourceContext(c.organizationId(),true,"CLINICIAN",c.practitionerId().toString(),c.ownerSubject(),false);}
    private Optional<String> replay(UUID org,String actor,String operation,String key,String hash){return jdbc.sql("SELECT result_id,request_hash FROM provider_command_results WHERE organization_id=? AND actor_subject=? AND operation=? AND idempotency_key=? FOR UPDATE").params(org,actor,operation,key).query((r,n)->Map.entry(r.getString(1),r.getString(2))).optional().map(row->{if(!row.getValue().equals(hash))conflict("IDEMPOTENCY_CONFLICT","The idempotency key was already used for a different request");return row.getKey();});}
    private void remember(UUID org,String actor,String operation,String resource,String key,String hash,String result,String status){jdbc.sql("INSERT INTO provider_command_results(id,organization_id,actor_subject,operation,resource_id,idempotency_key,request_hash,result_id,result_status,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)").params(UUID.randomUUID(),org,actor,operation,resource,key,hash,result,status,timestamp(clock.instant())).update();}
    private void event(UUID org,String aggregate,UUID id,String type,String key,String actor){jdbc.sql("INSERT INTO provider_domain_events(id,organization_id,aggregate_type,aggregate_id,event_type,event_key,actor_subject,occurred_at) SELECT ?,?,?,?,?,?,?,? WHERE NOT EXISTS(SELECT 1 FROM provider_domain_events WHERE event_key=?)").params(UUID.randomUUID(),org,aggregate,id.toString(),type,key,actor,timestamp(clock.instant()),key).update();}
    private void notifyClinician(UUID practitioner,UUID revision,String status,UUID decision){jdbc.sql("SELECT email_encrypted FROM practitioner_profiles WHERE id=? AND email_encrypted IS NOT NULL").param(practitioner).query(String.class).optional().ifPresent(encrypted->{String key="provider-credential-status:"+decision;jdbc.sql("INSERT INTO notification_outbox(id,notification_type,channel,destination,template_key,template_data,status,attempts,max_attempts,next_attempt_at,idempotency_key,created_at) SELECT ?,'PROVIDER_CREDENTIAL','EMAIL',?,'provider-credential-status',?,'PENDING',0,5,?,?,? WHERE NOT EXISTS(SELECT 1 FROM notification_outbox WHERE idempotency_key=?)").params(UUID.randomUUID(),crypto.decrypt(encrypted),"enc:"+crypto.encrypt("{\"revision\":\""+revision+"\",\"status\":\""+status+"\"}"),timestamp(clock.instant()),key,timestamp(clock.instant()),key).update();});}
    private static String decisionName(String value){return switch(value){case "REQUEST_INFORMATION"->"MORE_INFORMATION_REQUIRED";case "START_REVIEW"->"REVIEW_STARTED";case "VERIFY"->"VERIFIED";case "REJECT"->"REJECTED";case "SUSPEND"->"SUSPENDED";case "RESTORE"->"RESTORED";default->value;};}
    private static EvidenceView evidenceView(Evidence e){return new EvidenceView(e.id(),e.practitionerId(),e.safeName(),e.contentType(),e.expectedSize(),e.status(),e.version());}
    private static Blocker block(String code,String message){return new Blocker(code,message);}
    private static String jurisdiction(String value){required(value,20,"jurisdiction");return value.trim().toUpperCase(Locale.ROOT);}
    private static String safeName(String value){String v=value.replaceAll("[^A-Za-z0-9._-]","_");return v.length()>120?v.substring(v.length()-120):v;}
    private static String clean(String value){return value==null?null:value.trim();}
    private static void required(String value,int max,String name){if(value==null||value.isBlank()||value.length()>max)throw new ApiException(400,"INVALID_PROVIDER_CREDENTIAL","Complete the "+name+" within the allowed length");}
    private static String limit(String value,int max){if(value==null)return null;return value.length()>max?value.substring(0,max):value;}
    private static void conflict(String code,String message){throw new ApiException(409,code,message);}
    private static final class EvidenceRejectedException extends ApiException {private EvidenceRejectedException(){super(422,"CREDENTIAL_EVIDENCE_REJECTED","Credential evidence did not pass security inspection");}}
    private static String sha256(byte[] value){try{return java.util.HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(value));}catch(Exception e){throw new IllegalStateException(e);}}
    private static Instant instant(ResultSet r,String column)throws SQLException{var t=r.getTimestamp(column);return t==null?null:t.toInstant();}

    private record Policy(UUID id,List<Requirement> requirements){Requirement require(String type){return requirements.stream().filter(r->r.type().equals(type)&&r.mandatory()).findFirst().orElseThrow(()->new ApiException(400,"CREDENTIAL_NOT_REQUIRED","This credential type is not part of the applicable policy"));}}
    private record LegacyMapping(UUID practitionerId,String status){}
    private record Evidence(UUID id,UUID organizationId,UUID practitionerId,String stagingKey,String sealedKey,String safeName,String contentType,long expectedSize,String status,long version){}
    public record OnboardingView(UUID organizationId,UUID practitionerId,String clinicianType,ClinicianOnboardingStatus status,String jurisdiction,long version,String ownerSubject){}
    public record ProfileCommand(String registrationNumber,String specialty,String subspecialty,String qualifications,String jurisdiction,long version){}
    public record Requirement(String type,String displayName,boolean mandatory,boolean expiryRequired){}
    public record EvidenceCommand(String fileName,String contentType,long sizeBytes){}
    public record EvidenceUpload(UUID evidenceId,String uploadUrl,Map<String,String> requiredHeaders,long expiresInSeconds,String status){}
    public record EvidenceView(UUID id,UUID practitionerId,String fileName,String contentType,long sizeBytes,String status,long version){}
    public record DocumentAccess(String url,long expiresInSeconds){}
    public record SubmissionCommand(String credentialType,String issuer,String referenceNumber,Instant issuedAt,Instant expiresAt,UUID evidenceId){}
    public record DecisionCommand(String decision,String reason,long version){}
    public record RevisionView(UUID id,UUID dossierId,UUID organizationId,UUID practitionerId,String ownerSubject,String credentialType,int revisionNumber,UUID policyVersionId,String status,String dossierStatus,Instant expiresAt,String submittedBy,Instant submittedAt,long version,List<UUID> evidenceIds){}
    public record Blocker(String code,String message){}
    public record Readiness(boolean identityProvisioned,boolean organizationMembershipActive,boolean providerProfileComplete,boolean clinicianProfileComplete,boolean requiredCredentialsSubmitted,boolean requiredCredentialsVerified,boolean mandatoryCredentialsUnexpired,boolean requiredRelationshipsComplete,boolean pricingSetupRequired,boolean pricingSetupComplete,boolean availabilitySetupRequired,boolean availabilitySetupComplete,boolean credentialReady,List<Blocker> blockers,boolean readyForActivation,Instant evaluatedAt){}
    public record ProviderActivation(UUID organizationId,String status,boolean replayed){}
}
