package com.rehletshifaa.provider.application;

import com.rehletshifaa.access.application.AuthorizationService;
import com.rehletshifaa.access.domain.ChannelEntitlement;
import com.rehletshifaa.access.domain.ResourceContext;
import com.rehletshifaa.access.infrastructure.AccessAuditRepository;
import com.rehletshifaa.access.application.AccessIdentity;
import com.rehletshifaa.shared.api.ApiException;
import com.rehletshifaa.shared.currency.CurrencyService;
import org.springframework.context.annotation.Primary;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.*;
import java.util.*;
import static com.rehletshifaa.shared.persistence.SqlValues.timestamp;

@Service
@Primary
public class ProviderOperationalSetupService implements OperationalSetupReadinessPort {
    private static final Set<String> SCOPES=Set.of("ORGANIZATION","CONSULTANT","ASSOCIATE_DOCTOR");
    private static final Set<String> EXCEPTIONS=Set.of("LEAVE","BLOCKED","CLINIC_CLOSURE","EXTRA_AVAILABILITY","SPECIAL_CLINIC");
    private final CoordinationReadinessPort routing; private final JdbcClient jdbc; private final AuthorizationService authorization; private final AccessAuditRepository audit;
    private final ProviderPricingCatalogPort catalog; private final CurrencyService currency; private final Clock clock;
    public ProviderOperationalSetupService(JdbcClient jdbc,AuthorizationService authorization,AccessAuditRepository audit,
            ProviderPricingCatalogPort catalog,CurrencyService currency,Clock clock,CoordinationReadinessPort routing){this.routing=routing;this.jdbc=jdbc;this.authorization=authorization;this.audit=audit;this.catalog=catalog;this.currency=currency;this.clock=clock;}

    public List<PriceView> prices(UUID org,UUID practitioner){Clinician c=clinician(org,practitioner);authorize("price_list.view",c);return jdbc.sql("SELECT * FROM provider_price_versions WHERE organization_id=? AND (clinician_id=? OR scope_type='ORGANIZATION') ORDER BY service_code,scope_type,version_number DESC").params(org,practitioner).query(this::price).list();}

    @Transactional public PriceView createPrice(UUID org,UUID practitioner,PriceCommand x){Clinician c=clinician(org,practitioner);var actor=authorize("price_list.manage",c);validatePrice(c,x);String scope=x.scopeType().trim().toUpperCase(Locale.ROOT);UUID scoped=scope.equals("ORGANIZATION")?null:practitioner;String key=scoped==null?"ORGANIZATION":scoped.toString();
        int next=jdbc.sql("SELECT COALESCE(MAX(version_number),0) FROM provider_price_versions WHERE organization_id=? AND service_code=? AND scope_type=? AND scope_key=?").params(org,x.serviceCode().trim(),scope,key).query(Integer.class).single()+1;UUID id=UUID.randomUUID();Instant now=clock.instant();
        jdbc.sql("INSERT INTO provider_price_versions(id,organization_id,service_code,service_name,category,scope_type,scope_key,clinician_id,amount,currency,effective_from,effective_to,status,version_number,consultant_approval_required,created_by,changed_by,created_at,updated_at,revision) VALUES(?,?,?,?,?,?,?,?,?,?,?,?, 'DRAFT',?,?,?,?,?,?,0)")
                .params(id,org,x.serviceCode().trim(),x.serviceName().trim(),clean(x.category()),scope,key,scoped,x.amount(),x.currency().trim().toUpperCase(Locale.ROOT),timestamp(x.effectiveFrom()),x.effectiveTo()==null?null:timestamp(x.effectiveTo()),next,x.consultantApprovalRequired(),actor.subject(),actor.subject(),timestamp(now),timestamp(now)).update();
        audit.record(actor.subject(),id.toString(),"PROVIDER_PRICE_VERSION_CREATED","SUCCESS","organization="+org);return price(org,id,false);}

    @Transactional public PriceView updateDraft(UUID org,UUID practitioner,UUID id,long revision,PriceCommand x){Clinician c=clinician(org,practitioner);var actor=authorize("price_list.manage",c);PriceView old=price(org,id,true);if(!"DRAFT".equals(old.status())||old.clinicianId()!=null&&!old.clinicianId().equals(practitioner))notFoundPrice();validatePrice(c,x);String scope=x.scopeType().trim().toUpperCase(Locale.ROOT);UUID scoped=scope.equals("ORGANIZATION")?null:practitioner;String key=scoped==null?"ORGANIZATION":scoped.toString();
        int changed=jdbc.sql("UPDATE provider_price_versions SET service_code=?,service_name=?,category=?,scope_type=?,scope_key=?,clinician_id=?,amount=?,currency=?,effective_from=?,effective_to=?,consultant_approval_required=?,changed_by=?,updated_at=?,revision=revision+1 WHERE organization_id=? AND id=? AND revision=? AND status='DRAFT'")
                .params(x.serviceCode().trim(),x.serviceName().trim(),clean(x.category()),scope,key,scoped,x.amount(),x.currency().trim().toUpperCase(Locale.ROOT),timestamp(x.effectiveFrom()),x.effectiveTo()==null?null:timestamp(x.effectiveTo()),x.consultantApprovalRequired(),actor.subject(),timestamp(clock.instant()),org,id,revision).update();if(changed!=1)conflict("STALE_PRICE_VERSION","Price version changed; reload before saving");audit.record(actor.subject(),id.toString(),"PROVIDER_PRICE_VERSION_CHANGED","SUCCESS","organization="+org);return price(org,id,false);}

    @Transactional public PriceView publish(UUID org,UUID practitioner,UUID id,long revision){Clinician c=clinician(org,practitioner);var actor=authorize("price_list.publish",c);PriceView p=price(org,id,true);if(p.clinicianId()!=null&&!p.clinicianId().equals(practitioner))notFoundPrice();if(!"DRAFT".equals(p.status()))conflict("PRICE_NOT_DRAFT","Only a draft price can be published");long overlaps=jdbc.sql("SELECT COUNT(*) FROM provider_price_versions WHERE organization_id=? AND service_code=? AND scope_type=? AND scope_key=? AND status='ACTIVE' AND effective_from < COALESCE(?,TIMESTAMP WITH TIME ZONE '9999-12-31 00:00:00+00') AND (effective_to IS NULL OR effective_to>?)")
                .params(org,p.serviceCode(),p.scopeType(),p.scopeKey(),p.effectiveTo()==null?null:timestamp(p.effectiveTo()),timestamp(p.effectiveFrom())).query(Long.class).single();if(overlaps>0)conflict("PRICE_PERIOD_OVERLAP","An active price already overlaps this effective period");
        if(p.consultantApprovalRequired()&&p.consultantApprovedBy()==null)conflict("CONSULTANT_APPROVAL_REQUIRED","Consultant approval is required before publication");Instant now=clock.instant();int changed=jdbc.sql("UPDATE provider_price_versions SET status='ACTIVE',published_by=?,published_at=?,changed_by=?,updated_at=?,revision=revision+1 WHERE organization_id=? AND id=? AND revision=? AND status='DRAFT'").params(actor.subject(),timestamp(now),actor.subject(),timestamp(now),org,id,revision).update();if(changed!=1)conflict("STALE_PRICE_VERSION","Price version changed; reload before publication");
        UUID legacy=null;if("CONSULTANT".equals(p.scopeType())){BigDecimal egp=toEgp(p.amount(),p.currency(),p.effectiveFrom());legacy=catalog.applyPublishedProviderPrice(practitioner,p.serviceCode(),p.serviceName(),p.category(),egp,actor.subject(),p.effectiveFrom(),p.effectiveTo());jdbc.sql("UPDATE provider_price_versions SET legacy_catalog_id=? WHERE id=?").params(legacy,id).update();}
        audit.record(actor.subject(),id.toString(),"PROVIDER_PRICE_VERSION_PUBLISHED","SUCCESS","organization="+org);return price(org,id,false);}

    @Transactional public PriceView approve(UUID org,UUID practitioner,UUID id,long revision){Clinician c=clinician(org,practitioner);var actor=authorize("price_list.manage",c);if(!actor.subject().equals(c.subject()))throw new ApiException(403,"CONSULTANT_APPROVAL_REQUIRED","Only the scoped clinician may record Consultant approval");PriceView p=price(org,id,true);if(!"DRAFT".equals(p.status())||!p.consultantApprovalRequired()||p.clinicianId()==null||!p.clinicianId().equals(practitioner))notFoundPrice();int changed=jdbc.sql("UPDATE provider_price_versions SET consultant_approved_by=?,consultant_approved_at=?,changed_by=?,updated_at=?,revision=revision+1 WHERE organization_id=? AND id=? AND revision=? AND status='DRAFT'").params(actor.subject(),timestamp(clock.instant()),actor.subject(),timestamp(clock.instant()),org,id,revision).update();if(changed!=1)conflict("STALE_PRICE_VERSION","Price version changed; reload before approval");audit.record(actor.subject(),id.toString(),"PROVIDER_PRICE_VERSION_APPROVED","SUCCESS","organization="+org);return price(org,id,false);}

    @Transactional public PriceView retire(UUID org,UUID practitioner,UUID id,long revision){Clinician c=clinician(org,practitioner);var actor=authorize("price_list.publish",c);PriceView p=price(org,id,true);if(!"ACTIVE".equals(p.status())||p.clinicianId()!=null&&!p.clinicianId().equals(practitioner))notFoundPrice();Instant now=clock.instant();int changed=jdbc.sql("UPDATE provider_price_versions SET status='RETIRED',effective_to=CASE WHEN effective_to IS NULL OR effective_to>? THEN ? ELSE effective_to END,changed_by=?,updated_at=?,revision=revision+1 WHERE organization_id=? AND id=? AND revision=? AND status='ACTIVE'").params(timestamp(now),timestamp(now),actor.subject(),timestamp(now),org,id,revision).update();if(changed!=1)conflict("STALE_PRICE_VERSION","Price version changed; reload before retirement");if(p.legacyCatalogId()!=null)catalog.retirePublishedProviderPrice(p.legacyCatalogId(),actor.subject());audit.record(actor.subject(),id.toString(),"PROVIDER_PRICE_VERSION_RETIRED","SUCCESS","organization="+org);return price(org,id,false);}

    public EffectivePrice resolve(UUID org,UUID practitioner,String serviceCode,Instant at){Clinician c=clinician(org,practitioner);authorize("price_list.view",c);Instant when=at==null?clock.instant():at;List<PriceView> rows=jdbc.sql("SELECT * FROM provider_price_versions WHERE organization_id=? AND service_code=? AND status='ACTIVE' AND effective_from<=? AND (effective_to IS NULL OR effective_to>?) AND (clinician_id=? OR scope_type='ORGANIZATION') ORDER BY CASE WHEN clinician_id=? THEN 0 ELSE 1 END,version_number DESC")
                .params(org,serviceCode,timestamp(when),timestamp(when),practitioner,practitioner).query(this::price).list();if(!rows.isEmpty()){PriceView p=rows.get(0);return new EffectivePrice(p.amount(),p.currency(),p.scopeType(),p.id(),p.versionNumber(),p.effectiveFrom(),p.effectiveTo());}
        if("CONSULTANT".equals(c.type())){return jdbc.sql("SELECT id,price_egp,created_at,valid_until FROM consultant_service_catalog WHERE practitioner_id=? AND service_code=? AND active AND (valid_until IS NULL OR valid_until>=?)").params(practitioner,serviceCode,when.atZone(ZoneOffset.UTC).toLocalDate()).query((r,n)->new EffectivePrice(r.getBigDecimal(2),"EGP","LEGACY_CONSULTANT",r.getObject(1,UUID.class),0,r.getTimestamp(3).toInstant(),null)).optional().orElseThrow(()->new ApiException(404,"EFFECTIVE_PRICE_NOT_FOUND","No effective price is configured for this service"));}
        throw new ApiException(404,"EFFECTIVE_PRICE_NOT_FOUND","No effective price is configured for this service");}

    public ScheduleView schedule(UUID org,UUID practitioner){Clinician c=clinician(org,practitioner);authorize("availability.view",c);return scheduleView(c);}
    @Transactional public SlotView saveSlot(UUID org,UUID practitioner,UUID id,SlotCommand x){Clinician c=clinician(org,practitioner);var actor=authorizeAvailability(c);validateZone(x.timeZone());if(x.dayOfWeek()<1||x.dayOfWeek()>7||x.startTime()==null||x.endTime()==null||!x.endTime().isAfter(x.startTime())||x.effectiveFrom()==null||x.effectiveTo()!=null&&x.effectiveTo().isBefore(x.effectiveFrom()))bad("INVALID_AVAILABILITY_SLOT","Enter a valid weekly availability interval");
        long overlap=jdbc.sql("SELECT COUNT(*) FROM clinician_availability_slots WHERE organization_id=? AND practitioner_id=? AND day_of_week=? AND status='ACTIVE' AND id<>? AND start_time<? AND end_time>? AND effective_from<=COALESCE(?,DATE '9999-12-31') AND (effective_to IS NULL OR effective_to>=?)").params(org,practitioner,x.dayOfWeek(),id==null?new UUID(0,0):id,x.endTime(),x.startTime(),x.effectiveTo(),x.effectiveFrom()).query(Long.class).single();if(overlap>0)conflict("AVAILABILITY_OVERLAP","Weekly availability intervals cannot overlap");Instant now=clock.instant();UUID slot=id==null?UUID.randomUUID():id;
        if(id==null)jdbc.sql("INSERT INTO clinician_availability_slots(id,organization_id,practitioner_id,day_of_week,start_time,end_time,time_zone,service_code,consultation_mode,location,effective_from,effective_to,status,created_by,changed_by,created_at,updated_at,revision) VALUES(?,?,?,?,?,?,?,?,?,?,?,?, 'ACTIVE',?,?,?,?,0)").params(slot,org,practitioner,x.dayOfWeek(),x.startTime(),x.endTime(),x.timeZone(),clean(x.serviceCode()),clean(x.consultationMode()),clean(x.location()),x.effectiveFrom(),x.effectiveTo(),actor.subject(),actor.subject(),timestamp(now),timestamp(now)).update();
        else {int changed=jdbc.sql("UPDATE clinician_availability_slots SET day_of_week=?,start_time=?,end_time=?,time_zone=?,service_code=?,consultation_mode=?,location=?,effective_from=?,effective_to=?,changed_by=?,updated_at=?,revision=revision+1 WHERE id=? AND organization_id=? AND practitioner_id=? AND revision=?").params(x.dayOfWeek(),x.startTime(),x.endTime(),x.timeZone(),clean(x.serviceCode()),clean(x.consultationMode()),clean(x.location()),x.effectiveFrom(),x.effectiveTo(),actor.subject(),timestamp(now),id,org,practitioner,x.revision()).update();if(changed!=1)conflict("STALE_AVAILABILITY","Availability changed; reload before saving");}
        audit.record(actor.subject(),slot.toString(),id==null?"AVAILABILITY_CREATED":"AVAILABILITY_CHANGED","SUCCESS","organization="+org);return slot(org,practitioner,slot);}

    @Transactional public ExceptionView addException(UUID org,UUID practitioner,ExceptionCommand x){Clinician c=clinician(org,practitioner);var actor=authorizeAvailability(c);String type=x.type()==null?"":x.type().trim().toUpperCase(Locale.ROOT);if(!EXCEPTIONS.contains(type)||x.startsAt()==null||x.endsAt()==null||!x.endsAt().isAfter(x.startsAt()))bad("INVALID_AVAILABILITY_EXCEPTION","Enter a valid availability exception");validateZone(x.timeZone());long overlap=jdbc.sql("SELECT COUNT(*) FROM clinician_availability_exceptions WHERE organization_id=? AND practitioner_id=? AND starts_at<? AND ends_at>?").params(org,practitioner,timestamp(x.endsAt()),timestamp(x.startsAt())).query(Long.class).single();if(overlap>0)conflict("AVAILABILITY_EXCEPTION_OVERLAP","Availability exceptions cannot overlap");UUID id=UUID.randomUUID();Instant now=clock.instant();jdbc.sql("INSERT INTO clinician_availability_exceptions(id,organization_id,practitioner_id,exception_type,starts_at,ends_at,time_zone,service_code,consultation_mode,location,reason,created_by,changed_by,created_at,updated_at,revision) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,0)").params(id,org,practitioner,type,timestamp(x.startsAt()),timestamp(x.endsAt()),x.timeZone(),clean(x.serviceCode()),clean(x.consultationMode()),clean(x.location()),clean(x.reason()),actor.subject(),actor.subject(),timestamp(now),timestamp(now)).update();audit.record(actor.subject(),id.toString(),"AVAILABILITY_EXCEPTION_ADDED","SUCCESS","organization="+org);return exception(org,practitioner,id);}
    @Transactional public ExceptionView updateException(UUID org,UUID practitioner,UUID id,long revision,ExceptionCommand x){Clinician c=clinician(org,practitioner);var actor=authorizeAvailability(c);exception(org,practitioner,id);String type=x.type()==null?"":x.type().trim().toUpperCase(Locale.ROOT);if(!EXCEPTIONS.contains(type)||x.startsAt()==null||x.endsAt()==null||!x.endsAt().isAfter(x.startsAt()))bad("INVALID_AVAILABILITY_EXCEPTION","Enter a valid availability exception");validateZone(x.timeZone());long overlap=jdbc.sql("SELECT COUNT(*) FROM clinician_availability_exceptions WHERE organization_id=? AND practitioner_id=? AND id<>? AND starts_at<? AND ends_at>?").params(org,practitioner,id,timestamp(x.endsAt()),timestamp(x.startsAt())).query(Long.class).single();if(overlap>0)conflict("AVAILABILITY_EXCEPTION_OVERLAP","Availability exceptions cannot overlap");int changed=jdbc.sql("UPDATE clinician_availability_exceptions SET exception_type=?,starts_at=?,ends_at=?,time_zone=?,service_code=?,consultation_mode=?,location=?,reason=?,changed_by=?,updated_at=?,revision=revision+1 WHERE id=? AND organization_id=? AND practitioner_id=? AND revision=?").params(type,timestamp(x.startsAt()),timestamp(x.endsAt()),x.timeZone(),clean(x.serviceCode()),clean(x.consultationMode()),clean(x.location()),clean(x.reason()),actor.subject(),timestamp(clock.instant()),id,org,practitioner,revision).update();if(changed!=1)conflict("STALE_AVAILABILITY","Availability exception changed; reload before saving");audit.record(actor.subject(),id.toString(),"AVAILABILITY_EXCEPTION_CHANGED","SUCCESS","organization="+org);return exception(org,practitioner,id);}
    @Transactional public void removeException(UUID org,UUID practitioner,UUID id,long revision){Clinician c=clinician(org,practitioner);var actor=authorizeAvailability(c);int changed=jdbc.sql("DELETE FROM clinician_availability_exceptions WHERE id=? AND organization_id=? AND practitioner_id=? AND revision=?").params(id,org,practitioner,revision).update();if(changed!=1)throw new ApiException(404,"AVAILABILITY_EXCEPTION_NOT_FOUND","Availability exception was not found or changed");audit.record(actor.subject(),id.toString(),"AVAILABILITY_EXCEPTION_REMOVED","SUCCESS","organization="+org);}
    public EffectiveAvailability effective(UUID org,UUID practitioner,Instant at){Clinician c=clinician(org,practitioner);authorize("availability.view",c);Instant when=at==null?clock.instant():at;List<ExceptionView> exceptions=jdbc.sql("SELECT * FROM clinician_availability_exceptions WHERE organization_id=? AND practitioner_id=? AND starts_at<=? AND ends_at>?").params(org,practitioner,timestamp(when),timestamp(when)).query(this::exception).list();if(!exceptions.isEmpty()){ExceptionView e=exceptions.get(0);boolean extra=e.type().equals("EXTRA_AVAILABILITY")||e.type().equals("SPECIAL_CLINIC");return new EffectiveAvailability(extra,"EXCEPTION_"+e.type(),e.id(),when);}
        List<SlotView> slots=jdbc.sql("SELECT * FROM clinician_availability_slots WHERE organization_id=? AND practitioner_id=? AND status='ACTIVE'").params(org,practitioner).query(this::slot).list();for(SlotView s:slots){ZonedDateTime local=when.atZone(ZoneId.of(s.timeZone()));LocalDate date=local.toLocalDate();if(local.getDayOfWeek().getValue()==s.dayOfWeek()&&!date.isBefore(s.effectiveFrom())&&(s.effectiveTo()==null||!date.isAfter(s.effectiveTo()))&&!local.toLocalTime().isBefore(s.startTime())&&local.toLocalTime().isBefore(s.endTime()))return new EffectiveAvailability(true,"RECURRING",s.id(),when);}return new EffectiveAvailability(false,"UNAVAILABLE",null,when);}

    @Override public SetupReadiness evaluate(UUID org,UUID practitioner){Clinician c=clinicianUnchecked(org,practitioner);if(c==null)return new SetupReadiness(false,true,false,false,false,true,List.of("Clinician operational setup was not found."));Instant now=clock.instant();boolean pricing=jdbc.sql("SELECT COUNT(*) FROM provider_price_versions WHERE organization_id=? AND status='ACTIVE' AND effective_from<=? AND (effective_to IS NULL OR effective_to>?) AND (scope_type='ORGANIZATION' OR clinician_id=?)").params(org,timestamp(now),timestamp(now),practitioner).query(Long.class).single()>0;
        if(!pricing&&"CONSULTANT".equals(c.type()))pricing=jdbc.sql("SELECT COUNT(*) FROM consultant_service_catalog WHERE practitioner_id=? AND active AND (valid_until IS NULL OR valid_until>=?)").params(practitioner,LocalDate.now(clock)).query(Long.class).single()>0;boolean availability=jdbc.sql("SELECT COUNT(*) FROM clinician_availability_slots WHERE organization_id=? AND practitioner_id=? AND status='ACTIVE' AND effective_from<=? AND (effective_to IS NULL OR effective_to>=?)").params(org,practitioner,LocalDate.now(clock),LocalDate.now(clock)).query(Long.class).single()>0;List<String> blockers=new ArrayList<>();if(!pricing)blockers.add("At least one active price is required for the clinician's enabled services.");if(!availability)blockers.add("Clinician availability has not been configured.");boolean routingReady=routing.ready(org,practitioner);if(!routingReady)blockers.add("Routing preference or supported platform default is missing.");blockers.add("Required commercial or legal acceptance is missing.");return new SetupReadiness(pricing,true,availability,routingReady,false,true,List.copyOf(blockers));}

    private Clinician clinician(UUID org,UUID practitioner){Clinician c=clinicianUnchecked(org,practitioner);if(c==null)throw new ApiException(404,"CLINICIAN_ONBOARDING_NOT_FOUND","Clinician was not found in this provider organization");return c;}
    private Clinician clinicianUnchecked(UUID org,UUID practitioner){return jdbc.sql("SELECT p.external_subject,o.clinician_type FROM clinician_onboardings o JOIN practitioner_profiles p ON p.id=o.practitioner_id JOIN provider_organizations po ON po.id=o.organization_id AND po.status<>'OFFBOARDED' WHERE o.organization_id=? AND o.practitioner_id=? AND o.status<>'OFFBOARDED'").params(org,practitioner).query((r,n)->new Clinician(org,practitioner,r.getString(1),r.getString(2))).optional().orElse(null);}
    private AccessIdentity.Identity authorize(String permission,Clinician c){ApiException last=null;for(ChannelEntitlement channel:new ChannelEntitlement[]{ChannelEntitlement.CONSULTANT_WEB,ChannelEntitlement.API})try{return authorization.require(permission,new ResourceContext(c.org(),true,"CLINICIAN",c.id().toString(),c.subject(),false),channel);}catch(ApiException e){last=e;}throw last;}
    private AccessIdentity.Identity authorizeAvailability(Clinician c){try{return authorize("availability.manage",c);}catch(ApiException denied){return authorize("availability.manage_self",c);}}
    private void validatePrice(Clinician c,PriceCommand x){if(x==null||x.serviceCode()==null||x.serviceCode().isBlank()||x.serviceCode().length()>60||x.serviceName()==null||x.serviceName().isBlank()||x.serviceName().length()>500||x.amount()==null||x.amount().signum()<0||x.amount().scale()>2||x.effectiveFrom()==null||x.effectiveTo()!=null&&!x.effectiveTo().isAfter(x.effectiveFrom()))bad("INVALID_PRICE","Enter a valid service, amount and effective period");String scope=x.scopeType()==null?"":x.scopeType().trim().toUpperCase(Locale.ROOT);if(!SCOPES.contains(scope)||scope.equals("CONSULTANT")&&!c.type().equals("CONSULTANT")||scope.equals("ASSOCIATE_DOCTOR")&&!c.type().equals("ASSOCIATE_DOCTOR"))bad("INVALID_PRICE_SCOPE","Price scope does not match the clinician relationship");String code=x.currency()==null?"":x.currency().trim().toUpperCase(Locale.ROOT);if(!currency.supportedCurrencies().contains(code))bad("CURRENCY_NOT_SUPPORTED","Currency is not supported: "+code);}
    private BigDecimal toEgp(BigDecimal amount,String code,Instant at){if(CurrencyService.BASE.equals(code))return amount;return amount.divide(currency.effectiveRate(code,at.atZone(ZoneOffset.UTC).toLocalDate()),2,RoundingMode.HALF_UP);}
    private void validateZone(String zone){try{if(zone==null)throw new DateTimeException("missing");ZoneId.of(zone);}catch(DateTimeException e){bad("INVALID_TIME_ZONE","Use an explicit IANA time zone");}}
    private ScheduleView scheduleView(Clinician c){List<SlotView> slots=jdbc.sql("SELECT * FROM clinician_availability_slots WHERE organization_id=? AND practitioner_id=? ORDER BY day_of_week,start_time").params(c.org(),c.id()).query(this::slot).list();List<ExceptionView> exceptions=jdbc.sql("SELECT * FROM clinician_availability_exceptions WHERE organization_id=? AND practitioner_id=? ORDER BY starts_at").params(c.org(),c.id()).query(this::exception).list();return new ScheduleView(c.org(),c.id(),slots,exceptions);}
    private PriceView price(UUID org,UUID id,boolean lock){return jdbc.sql("SELECT * FROM provider_price_versions WHERE organization_id=? AND id=?"+(lock?" FOR UPDATE":"")).params(org,id).query(this::price).optional().orElseThrow(()->new ApiException(404,"PRICE_VERSION_NOT_FOUND","Price version was not found"));}
    private PriceView price(ResultSet r,int n)throws SQLException{return new PriceView(r.getObject("id",UUID.class),r.getObject("organization_id",UUID.class),r.getString("service_code"),r.getString("service_name"),r.getString("category"),r.getString("scope_type"),r.getString("scope_key"),r.getObject("clinician_id",UUID.class),r.getBigDecimal("amount"),r.getString("currency"),instant(r,"effective_from"),instant(r,"effective_to"),r.getString("status"),r.getInt("version_number"),r.getBoolean("consultant_approval_required"),r.getString("consultant_approved_by"),r.getObject("legacy_catalog_id",UUID.class),r.getLong("revision"));}
    private SlotView slot(UUID org,UUID practitioner,UUID id){return jdbc.sql("SELECT * FROM clinician_availability_slots WHERE organization_id=? AND practitioner_id=? AND id=?").params(org,practitioner,id).query(this::slot).single();}
    private SlotView slot(ResultSet r,int n)throws SQLException{return new SlotView(r.getObject("id",UUID.class),r.getInt("day_of_week"),r.getTime("start_time").toLocalTime(),r.getTime("end_time").toLocalTime(),r.getString("time_zone"),r.getString("service_code"),r.getString("consultation_mode"),r.getString("location"),r.getObject("effective_from",LocalDate.class),r.getObject("effective_to",LocalDate.class),r.getString("status"),r.getLong("revision"));}
    private ExceptionView exception(UUID org,UUID practitioner,UUID id){return jdbc.sql("SELECT * FROM clinician_availability_exceptions WHERE organization_id=? AND practitioner_id=? AND id=?").params(org,practitioner,id).query(this::exception).single();}
    private ExceptionView exception(ResultSet r,int n)throws SQLException{return new ExceptionView(r.getObject("id",UUID.class),r.getString("exception_type"),instant(r,"starts_at"),instant(r,"ends_at"),r.getString("time_zone"),r.getString("service_code"),r.getString("consultation_mode"),r.getString("location"),r.getString("reason"),r.getLong("revision"));}
    private static Instant instant(ResultSet r,String col)throws SQLException{var v=r.getTimestamp(col);return v==null?null:v.toInstant();} private static String clean(String s){return s==null||s.isBlank()?null:s.trim();}
    private static void bad(String code,String message){throw new ApiException(400,code,message);}private static void conflict(String code,String message){throw new ApiException(409,code,message);}private static void notFoundPrice(){throw new ApiException(404,"PRICE_VERSION_NOT_FOUND","Price version was not found for this clinician");}
    private record Clinician(UUID org,UUID id,String subject,String type){}
    public record PriceCommand(String serviceCode,String serviceName,String category,String scopeType,BigDecimal amount,String currency,Instant effectiveFrom,Instant effectiveTo,boolean consultantApprovalRequired){}
    public record PriceView(UUID id,UUID organizationId,String serviceCode,String serviceName,String category,String scopeType,String scopeKey,UUID clinicianId,BigDecimal amount,String currency,Instant effectiveFrom,Instant effectiveTo,String status,int versionNumber,boolean consultantApprovalRequired,String consultantApprovedBy,UUID legacyCatalogId,long revision){}
    public record EffectivePrice(BigDecimal amount,String currency,String sourceLevel,UUID priceId,int version,Instant effectiveFrom,Instant effectiveTo){}
    public record SlotCommand(int dayOfWeek,LocalTime startTime,LocalTime endTime,String timeZone,String serviceCode,String consultationMode,String location,LocalDate effectiveFrom,LocalDate effectiveTo,long revision){}
    public record SlotView(UUID id,int dayOfWeek,LocalTime startTime,LocalTime endTime,String timeZone,String serviceCode,String consultationMode,String location,LocalDate effectiveFrom,LocalDate effectiveTo,String status,long revision){}
    public record ExceptionCommand(String type,Instant startsAt,Instant endsAt,String timeZone,String serviceCode,String consultationMode,String location,String reason){}
    public record ExceptionView(UUID id,String type,Instant startsAt,Instant endsAt,String timeZone,String serviceCode,String consultationMode,String location,String reason,long revision){}
    public record ScheduleView(UUID organizationId,UUID practitionerId,List<SlotView> recurring,List<ExceptionView> exceptions){}
    public record EffectiveAvailability(boolean available,String source,UUID sourceId,Instant evaluatedAt){}
}
