package com.rehletshifaa.casemanagement.domain;
public enum CaseStatus { DRAFT, NEW, COORDINATOR_REVIEW, READY_FOR_CONSULTANT, CONSULTANT_REVIEW, RECOMMENDATION_READY, PATIENT_DECISION, TREATMENT_COORDINATION, CLOSED }
