import type { Metadata } from "next";
import { Check, CircleDot, HeartPulse, Stethoscope } from "lucide-react";
import { notFound } from "next/navigation";
import { PageHero } from "@/components/PageHero";
import { CtaPanel } from "@/components/CtaPanel";
import { TrackedLink } from "@/components/TrackedLink";
import { getDictionary } from "@/lib/dictionary";
import { isLocale } from "@/lib/i18n";
import { pageMetadata } from "@/lib/metadata";
type Props = { params: Promise<{ locale: string }> };
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { locale } = await params; if (!isLocale(locale)) return {}; const d = getDictionary(locale); return pageMetadata(locale, "cardiology", d.cardiology.title, d.cardiology.intro); }
function ItemList({ items }: { items: string[] }) { return <ul className="grid gap-3 sm:grid-cols-2">{items.map(item => <li className="flex gap-3 leading-7 text-ink-700" key={item}><Check className="mt-1.5 shrink-0 text-accent-700" size={17} />{item}</li>)}</ul>; }
export default async function Cardiology({ params }: Props) { const { locale } = await params; if (!isLocale(locale)) notFound(); const d = getDictionary(locale); const sections = [{ icon: Stethoscope, title: d.cardiology.coronaryTitle, items: d.cardiology.coronaryItems, examples: d.cardiology.coronaryExamples }, { icon: HeartPulse, title: d.cardiology.structuralTitle, items: d.cardiology.structuralItems }, { icon: CircleDot, title: d.cardiology.rhythmTitle, items: d.cardiology.rhythmItems, examples: d.cardiology.rhythmExamples }]; return <><PageHero eyebrow={d.cardiology.eyebrow} title={d.cardiology.title} intro={d.cardiology.intro}><TrackedLink event="send_case_cta_clicked" className="btn-primary" href={`/${locale}/send-my-case`}>{d.common.send}</TrackedLink></PageHero><div className="container-site py-16 md:py-24">{sections.map((section, i) => { const Icon = section.icon; return <section className={`grid gap-9 py-12 md:grid-cols-[.72fr_1.28fr] md:py-16 ${i ? "border-t border-line" : ""}`} key={section.title}><div><Icon className="text-accent-700" size={30} /><h2 className="mt-6 text-3xl font-bold tracking-[-.035em] text-brand-900">{section.title}</h2></div><div><ItemList items={section.items} />{section.examples && <div className="mt-9 rounded-lg bg-brand-50 p-6"><h3 className="font-bold text-brand-900">{d.cardiology.examples}</h3><ul className="mt-4 space-y-2 text-sm leading-6 text-ink-500">{section.examples.map(x => <li key={x}>— {x}</li>)}</ul></div>}{i === 1 && <p className="mt-8 border-s-4 border-accent-700 bg-wash-aqua p-5 font-bold leading-7 text-accent-800">{d.cardiology.suitability}</p>}</div></section>; })}</div><CtaPanel locale={locale} title={d.cardiology.finalTitle} body={d.cardiology.finalBody} button={d.common.send} /></>; }

