import type { Locale } from "@/lib/i18n";

/**
 * Coordination Setup copy. Configuration and governance of platform-wide care-coordination routing.
 * Arabic is a draft pending the native healthcare-operations review (V-9); new terms are listed in the UX-7 record.
 */
export const coordCopy = {
  en: {
    navCoordination: "Coordination Setup", organization: "Organization", orgListIntro: "Choose the organization whose coordinator teams, clinician preferences and routing rules you want to set up.", noOrganizations: "No organizations are set up for care coordination yet.", search: "Find an organization", opening: "Opening Coordination Setup…",
    loading: "Loading…", denied: "You don't have access to Coordination Setup.", signin: "Sign in securely", cancel: "Cancel", save: "Save", close: "Close", none: "None", unnamed: "Name not recorded",
    reason: "Reason for this change", reasonHint: "Kept in the audit record.", reasonLabel: "Reason",
    intro: "Configure how coordination work is routed: team routing profiles, coordinator capacity, consultant preferences and routing rules.",
    sections: { teams: "Teams & People", preferences: "Consultant Preferences", rules: "Rules", advanced: "Advanced" },
    sectionsLabel: "Coordination Setup sections",
    mode: {
      evaluation: "Evaluation mode", evaluationBody: "Routing recommendations are measured but are not applied to live assignments. Coordinators take and transfer cases in the Staff Portal.",
      live: (n: number) => `Routing is in effect · ${n} case${n === 1 ? "" : "s"} routed so far`, liveBody: "When a case needs coordinator work and has no coordinator, routing assigns one under these rules, or queues it for the Care Coordination Manager.",
      noPolicy: "No routing rules are in effect", noPolicyBody: "Until a rules version is in effect, cases without a coordinator stay unassigned; coordinators can still take them from the intake queue.",
    },

    // Teams & People
    teamsTitle: "Coordinator teams", teamsIntro: "Teams group the coordinators routing can consider. Removing someone from a team changes future routing only — past assignments stay as they were.",
    peopleTitle: "People", peopleIntro: "RehletShifaa coordinators, their teams and how much work they can take.",
    newTeam: "New team", editTeam: "Edit team", noTeams: "No coordinator teams yet.", noTeamsHint: "Create a team, then add coordinators to it.",
    teamName: "Team name", teamPurpose: "What this team handles", teamActive: "Active", teamInactive: "Inactive", teamStatus: "Team status",
    careAreas: "Care areas", careAreasHint: "Leave all unticked for a team that takes every care area.", allCareAreas: "All care areas",
    languages: "Languages", timeZone: "Time zone", timeZoneHint: "An IANA time zone, for example Asia/Dubai.", fallbackTeam: "If nobody here is available, try", members: (n: number) => `${n} active member${n === 1 ? "" : "s"}`,
    noMembers: "Nobody in this team yet.", lead: "Team lead", addPerson: "Add person", addPersonTo: (team: string) => `Add a person to ${team}`,
    choosePerson: "Coordinator", findPerson: "Find by name", noCandidates: "Everyone who can join is already in this team.", noMatch: "Nobody matches that name.",
    onlyCoordinators: "Only RehletShifaa coordinators with an active account can join a team.",
    startsOn: "Starts on", asLead: "Team lead",
    removeFromTeam: "Remove from team", removeTitle: (p: string, t: string) => `Remove ${p} from ${t}?`,
    done: { team: "Team saved.", added: "Added to the team. Routing can consider them from the start date.", removed: "Removed from the team. Future routing no longer considers them for it.", capacity: "Capacity saved.", preference: "Preference saved.", rules: "New rules version published." },
    removeChanges: "Routing stops considering them for this team.", removeKeeps: "Cases they already own and their open work stay with them. Assignment history is unchanged.",
    removeNotify: "Nobody is notified.",
    person: { account: "Account", active: "Active", disabled: "Disabled", noAccount: "Not a coordinator account", notMember: "No longer a member of this organization", teams: "Teams", noTeams: "No team" },
    caseload: (load: number, max: number | null) => max === null ? `${load} active case${load === 1 ? "" : "s"}` : `${load} of ${max} cases`,
    onDuty: "On duty", offDuty: "Off duty", noCapacity: "No capacity set — routing cannot consider them yet.",
    capacityEdit: "Set capacity", capacityTitle: (p: string) => `Capacity for ${p}`, maximum: "Maximum active cases", maximumHint: "Routing skips them once they own this many active cases.",
    onDutyLabel: "On duty now", capacityLanguages: "Languages they coordinate in", capacityCareAreas: "Care areas they cover", capacityCareAreasHint: "Leave all unticked to cover every care area.",
    noPeople: "No coordinators yet.", noPeopleHint: "A person appears here once they hold the Coordinator role.",

    // Clinician Preferences
    prefIntro: "A preference tells routing whom to try first for a clinician's cases. It never guarantees the assignment: the coordinator must still be eligible (access, team, capacity, language and on-duty rules).",
    prefNone: "No preference — routing uses the rules.", prefCoordinator: "Preferred coordinator", prefTeam: "Preferred team", prefFallback: "Then try team",
    prefUntil: (d: string) => `In effect until ${d}`, prefScheduled: (d: string) => `A new version starts ${d}`, editPreference: "Change preference", preferenceFor: (c: string) => `Routing preference for ${c}`,
    prefKind: "Preference", prefKindNone: "No preference (use the rules)", prefKindCoordinator: "A specific coordinator", prefKindTeam: "A team",
    effectiveFrom: "Starts on", effectiveTo: "Ends on", versionedHint: "Preferences and rules are versioned: each version has a start and an end date, and versions cannot overlap.",
    nextStartsAfter: (d: string) => `The current version ends ${d}. The new one can start then or later.`,
    noConsultants: "No consultants yet.", history: "Earlier versions", noHistory: "No earlier versions.",

    // Rules
    rulesIntro: "Rules decide, in order, whom routing recommends for a case. Hard requirements always apply first; the order below is fixed.",
    rulesInEffect: (v: number, from: string, to: string) => `Version ${v} · in effect ${from} – ${to}`, rulesNone: "No rules version is in effect.",
    rulesScheduled: (v: number, from: string) => `Version ${v} starts ${from}`, rulesExpired: "The latest version has ended.",
    requirements: "Hard requirements", requirementsIntro: "A coordinator who fails one of these is never recommended.",
    reqAccess: "Holds the Coordinator role, has an active account and belongs to an active care-coordination team", reqCapacity: "Is below their maximum active cases",
    reqOnDuty: "Is on duty", reqLanguage: "Coordinates in the patient's language", reqCareArea: "Covers the case's care area (when their capacity lists care areas)",
    required: "Required", notRequired: "Not required",
    order: "Order of preference", orderIntro: "Routing takes the first step that finds an eligible coordinator.",
    ruleContinuity: "Keep the current coordinator", ruleContinuityWhy: "Continuity: a case keeps its coordinator while they remain eligible.",
    rulePreferred: "Clinician's preferred coordinator", rulePreferredWhy: "Set under Clinician Preferences.",
    ruleTeams: "Teams, in this order", ruleTeamsWhy: "Clinician's preferred team, then the teams below, then each team's own fallback.",
    ruleBest: "Best available coordinator", ruleBestWhy: "Most spare capacity, with a language match counting in their favour.",
    ruleNobody: "Nobody eligible", ruleNobodyWhy: (h: number) => `The case waits for a coordination manager; the deadline is ${h} hour${h === 1 ? "" : "s"}. Applies only to live-routed cases.`,
    providerTeam: "Organization team", careAreaTeams: "Care-area teams", defaultTeam: "Default team", policyFallback: "Last-resort team", notSet: "Not set",
    publish: "Publish new version", publishTitle: "New rules version", queueHours: "Deadline for waiting cases (hours)",
    weights: "Balance between capacity and language", weightsHint: "Two weights that must add up to 100.", capacityWeight: "Spare capacity", languageWeight: "Language match",
    weightsInvalid: "The two weights must add up to 100.", advancedSettings: "Advanced settings",

    // Advanced
    advancedIntro: "Diagnostics for people who configure routing. Nothing here assigns, reassigns or transfers work.",
    previewTitle: "Preview routing recommendation", previewCopy: "Evaluation only — this will not change the case owner or the person assigned to this work.",
    previewIntro: "See whom routing would recommend today for a clinician, care area and patient language, using the rules and teams in effect. This is the engine's routing simulation; it is never saved.",
    previewClinician: "Clinician", previewAnyClinician: "No specific clinician", previewCareArea: "Care area", previewLanguage: "Patient language", previewAny: "Not specified",
    whatIf: "What if…", whatIfHint: "Try a preferred coordinator or team that is not saved.", whatIfCoordinator: "Preferred coordinator", whatIfTeam: "Preferred team",
    runPreview: "Preview recommendation", recommended: "Recommended", noRecommendation: "Nobody is eligible", why: "Why", viaTeam: (t: string) => `through ${t}`,
    otherCandidates: "Other eligible coordinators", notEligible: "Not eligible", caseloadLabel: "Caseload", languageMatch: "Speaks the patient's language", noLanguageMatch: "Different language",
    previewRules: (v: number) => `Evaluated against rules version ${v}.`,
    historyTitle: "Routing decision history", historyIntro: "Every routing decision, newest first.",
    historyEmpty: "No routing decisions have been recorded yet.",
    entry: { recommendation: "Recommendation recorded", evaluationOnly: "Evaluation only — nothing changed", applied: "Applied to the case", manual: "Manual assignment", automatic: "Assigned by routing", queued: "Moved to the waiting queue" },
    matched: "Matched the current coordinator", differed: "Differed from the current coordinator", recommendedPerson: "Recommended", from: "From", to: "To", by: "By", nobody: "Nobody",
    liveQueueTitle: "Cases waiting for a coordinator",
    liveQueueIntro: "Cases routing could not place (nobody eligible) or that were parked. The Care Coordination Manager assigns them here.",
    liveQueueEmpty: "No live-routed case is waiting.", waitingSince: "Waiting since", deadline: "Deadline", assign: "Assign coordinator",
    assignTitle: (c: string) => `Assign a coordinator to case ${c}`,
    assignChanges: "The coordinator becomes the case owner, open coordinator work on the case moves to them, and they are notified in the Staff Portal and by email.",
    assignKeeps: "Consultant, Operations and Finance work is unchanged. The decision is added to the routing decision history.",
    assignEligible: "Eligible coordinators (from the latest routing evaluation)", assignNone: "Routing found nobody eligible. Change teams or capacity first.", assignConfirm: "Assign coordinator", assignDone: "Coordinator assigned.",
    technicalTitle: "Technical configuration", technicalIntro: "The stored rules configuration and internal identifiers, for support.",
    stale: "This changed since you opened it. Refresh and try again — nothing was saved.",

    exclusions: {
      ACCESS_OR_MEMBERSHIP_DENIED: "No access to receive coordination work here", STAFF_DISABLED: "Coordinator account disabled",
      NO_ACTIVE_TEAM: "Not in an active team for this care area", CARE_AREA_MISMATCH: "Doesn't cover this care area", LANGUAGE_MISMATCH: "Doesn't speak the patient's language",
      OFF_DUTY: "Off duty", AT_CAPACITY: "At maximum caseload",
    } as Record<string, string>,
    paths: {
      CONTINUITY: "Keeps the current coordinator (continuity)", PREFERRED_COORDINATOR: "The clinician's preferred coordinator", PREFERRED_TEAM: "From the clinician's preferred team",
      PROVIDER_TEAM: "From the organization team", CARE_AREA_TEAM: "From the care-area team", DEFAULT_TEAM: "From the default team",
      CONSULTANT_FALLBACK_TEAM: "From the clinician's fallback team", FALLBACK_TEAM: "From the last-resort team", TEAM_FALLBACK: "From a team's own fallback team",
      SCORED_POOL: "Best available coordinator across teams", NO_ELIGIBLE_COORDINATOR: "Nobody was eligible",
      MANUAL_ASSIGN: "Assigned by a coordination manager", MANUAL_REASSIGN: "Reassigned by a coordination manager", MANUAL_QUEUE: "Moved to the waiting queue by a coordination manager",
    } as Record<string, string>,
  },
  ar: {
    navCoordination: "إعداد التنسيق", organization: "الجهة", orgListIntro: "اختر الجهة التي تريد إعداد فرق المنسقين وتفضيلات الأطباء وقواعد التوجيه لها.", noOrganizations: "لا توجد جهات مُعدّة لتنسيق الرعاية بعد.", search: "البحث عن جهة", opening: "جارٍ فتح إعداد التنسيق…",
    loading: "جارٍ التحميل…", denied: "ليس لديك وصول إلى إعداد التنسيق.", signin: "تسجيل الدخول الآمن", cancel: "إلغاء", save: "حفظ", close: "إغلاق", none: "لا يوجد", unnamed: "اسم غير مسجّل",
    reason: "سبب هذا التغيير", reasonHint: "يُحفظ في سجل التدقيق.", reasonLabel: "السبب",
    intro: "اضبط توجيه عمل التنسيق: ملفات توجيه الفرق وسعة المنسقين وتفضيلات الاستشاريين وقواعد التوجيه.",
    sections: { teams: "الفرق والأشخاص", preferences: "تفضيلات الاستشاريين", rules: "القواعد", advanced: "متقدم" },
    sectionsLabel: "أقسام إعداد التنسيق",
    mode: {
      evaluation: "وضع التقييم", evaluationBody: "تُقاس توصيات التوجيه لكنها لا تُطبَّق على التعيينات الفعلية. يستلم المنسقون الحالات وينقلونها في بوابة الموظفين.",
      live: (n: number) => `التوجيه ساري · وُجّهت ${n} حالة حتى الآن`, liveBody: "عندما تحتاج حالة بلا منسق إلى عمل تنسيق، يعيّن التوجيه منسقًا وفق هذه القواعد، أو يضعها في قائمة انتظار مدير التنسيق.",
      noPolicy: "لا توجد قواعد توجيه سارية", noPolicyBody: "حتى يسري إصدار من القواعد تبقى الحالات بلا منسق غير معيّنة، ويمكن للمنسقين استلامها من قائمة الاستقبال.",
    },

    teamsTitle: "فرق المنسقين", teamsIntro: "تجمع الفرق المنسقين الذين يمكن للتوجيه أخذهم في الاعتبار. إزالة شخص من فريق تغيّر التوجيه المستقبلي فقط — تبقى التعيينات السابقة كما هي.",
    peopleTitle: "الأشخاص", peopleIntro: "منسقو رحلة شفاء، وفرقهم، وحجم العمل الذي يمكنهم تحمله.",
    newTeam: "فريق جديد", editTeam: "تعديل الفريق", noTeams: "لا توجد فرق منسقين بعد.", noTeamsHint: "أنشئ فريقًا ثم أضف إليه المنسقين.",
    teamName: "اسم الفريق", teamPurpose: "ما يتولاه هذا الفريق", teamActive: "نشط", teamInactive: "غير نشط", teamStatus: "حالة الفريق",
    careAreas: "مجالات الرعاية", careAreasHint: "اترك الكل دون تحديد لفريق يتولى كل مجالات الرعاية.", allCareAreas: "كل مجالات الرعاية",
    languages: "اللغات", timeZone: "المنطقة الزمنية", timeZoneHint: "منطقة زمنية بصيغة IANA، مثل Asia/Dubai.", fallbackTeam: "إن لم يتوفر أحد هنا، جرّب", members: (n: number) => `${n} عضو نشط`,
    noMembers: "لا يوجد أحد في هذا الفريق بعد.", lead: "قائد الفريق", addPerson: "إضافة شخص", addPersonTo: (team: string) => `إضافة شخص إلى ${team}`,
    choosePerson: "المنسق", findPerson: "ابحث بالاسم", noCandidates: "كل من يمكنه الانضمام موجود بالفعل في هذا الفريق.", noMatch: "لا يوجد أحد بهذا الاسم.",
    onlyCoordinators: "يمكن الانضمام إلى الفريق فقط لمنسقي رحلة شفاء أصحاب الحسابات النشطة.",
    startsOn: "يبدأ في", asLead: "قائد الفريق",
    removeFromTeam: "إزالة من الفريق", removeTitle: (p: string, t: string) => `إزالة ${p} من ${t}؟`,
    done: { team: "تم حفظ الفريق.", added: "أُضيف إلى الفريق. يمكن للتوجيه أخذه في الاعتبار من تاريخ البدء.", removed: "أُزيل من الفريق. لم يعد التوجيه المستقبلي يأخذه في الاعتبار له.", capacity: "تم حفظ السعة.", preference: "تم حفظ التفضيل.", rules: "نُشر إصدار قواعد جديد." },
    removeChanges: "يتوقف التوجيه عن أخذه في الاعتبار لهذا الفريق.", removeKeeps: "تبقى الحالات التي يملكها وعمله المفتوح معه. لا يتغير سجل التعيينات.",
    removeNotify: "لا يُرسَل إشعار لأحد.",
    person: { account: "الحساب", active: "نشط", disabled: "معطّل", noAccount: "ليس حساب منسق", notMember: "لم يعد عضوًا في هذه الجهة", teams: "الفرق", noTeams: "بلا فريق" },
    caseload: (load: number, max: number | null) => max === null ? `${load} حالة نشطة` : `${load} من ${max} حالات`,
    onDuty: "في الخدمة", offDuty: "خارج الخدمة", noCapacity: "لم تُحدَّد السعة — لا يستطيع التوجيه أخذه في الاعتبار بعد.",
    capacityEdit: "تحديد السعة", capacityTitle: (p: string) => `سعة ${p}`, maximum: "الحد الأقصى للحالات النشطة", maximumHint: "يتخطاه التوجيه عندما يملك هذا العدد من الحالات النشطة.",
    onDutyLabel: "في الخدمة الآن", capacityLanguages: "اللغات التي ينسّق بها", capacityCareAreas: "مجالات الرعاية التي يغطيها", capacityCareAreasHint: "اترك الكل دون تحديد لتغطية كل مجالات الرعاية.",
    noPeople: "لا يوجد منسقون بعد.", noPeopleHint: "يظهر الشخص هنا عندما يحمل دور المنسق.",

    prefIntro: "يخبر التفضيلُ التوجيهَ بمن يبدأ لحالات الطبيب. لا يضمن التعيين أبدًا: يجب أن يظل المنسق مؤهلًا (الوصول، الفريق، السعة، اللغة، الخدمة).",
    prefNone: "لا يوجد تفضيل — يستخدم التوجيه القواعد.", prefCoordinator: "المنسق المفضّل", prefTeam: "الفريق المفضّل", prefFallback: "ثم جرّب الفريق",
    prefUntil: (d: string) => `ساري حتى ${d}`, prefScheduled: (d: string) => `يبدأ إصدار جديد في ${d}`, editPreference: "تغيير التفضيل", preferenceFor: (c: string) => `تفضيل التوجيه لـ ${c}`,
    prefKind: "التفضيل", prefKindNone: "لا تفضيل (استخدم القواعد)", prefKindCoordinator: "منسق محدد", prefKindTeam: "فريق",
    effectiveFrom: "يبدأ في", effectiveTo: "ينتهي في", versionedHint: "للتفضيلات والقواعد إصدارات: لكل إصدار تاريخ بداية ونهاية، ولا تتداخل الإصدارات.",
    nextStartsAfter: (d: string) => `ينتهي الإصدار الحالي في ${d}. يمكن أن يبدأ الجديد حينها أو بعدها.`,
    noConsultants: "لا يوجد استشاريون بعد.", history: "الإصدارات السابقة", noHistory: "لا توجد إصدارات سابقة.",

    rulesIntro: "تحدد القواعد بالترتيب من يوصي به التوجيه للحالة. تُطبَّق المتطلبات الإلزامية أولًا دائمًا؛ والترتيب أدناه ثابت.",
    rulesInEffect: (v: number, from: string, to: string) => `الإصدار ${v} · ساري ${from} – ${to}`, rulesNone: "لا يوجد إصدار قواعد ساري.",
    rulesScheduled: (v: number, from: string) => `يبدأ الإصدار ${v} في ${from}`, rulesExpired: "انتهى أحدث إصدار.",
    requirements: "متطلبات إلزامية", requirementsIntro: "لا يُوصى أبدًا بمنسق لا يستوفي أحدها.",
    reqAccess: "يحمل دور المنسق، ولديه حساب نشط، وينتمي إلى فريق تنسيق نشط", reqCapacity: "أقل من الحد الأقصى لحالاته النشطة",
    reqOnDuty: "في الخدمة", reqLanguage: "ينسّق بلغة المريض", reqCareArea: "يغطي مجال رعاية الحالة (عندما تحدد سعته مجالات رعاية)",
    required: "إلزامي", notRequired: "غير إلزامي",
    order: "ترتيب الأفضلية", orderIntro: "يأخذ التوجيه أول خطوة تجد منسقًا مؤهلًا.",
    ruleContinuity: "الإبقاء على المنسق الحالي", ruleContinuityWhy: "الاستمرارية: تحتفظ الحالة بمنسقها ما دام مؤهلًا.",
    rulePreferred: "المنسق المفضّل لدى الطبيب", rulePreferredWhy: "يُحدَّد في تفضيلات الأطباء.",
    ruleTeams: "الفرق بهذا الترتيب", ruleTeamsWhy: "الفريق المفضّل لدى الطبيب، ثم الفرق أدناه، ثم الفريق الاحتياطي لكل فريق.",
    ruleBest: "أفضل منسق متاح", ruleBestWhy: "الأكثر سعة متبقية، مع ترجيح من يتحدث لغة المريض.",
    ruleNobody: "لا يوجد مؤهل", ruleNobodyWhy: (h: number) => `تنتظر الحالة مدير التنسيق؛ المهلة ${h} ساعة. ينطبق على حالات التوجيه الفعلي فقط.`,
    providerTeam: "فريق الجهة", careAreaTeams: "فرق مجالات الرعاية", defaultTeam: "الفريق الافتراضي", policyFallback: "فريق الملاذ الأخير", notSet: "غير محدد",
    publish: "نشر إصدار جديد", publishTitle: "إصدار قواعد جديد", queueHours: "مهلة الحالات المنتظرة (ساعات)",
    weights: "التوازن بين السعة واللغة", weightsHint: "وزنان مجموعهما 100.", capacityWeight: "السعة المتبقية", languageWeight: "تطابق اللغة",
    weightsInvalid: "يجب أن يكون مجموع الوزنين 100.", advancedSettings: "إعدادات متقدمة",

    advancedIntro: "أدوات تشخيص لمن يضبطون التوجيه. لا شيء هنا يعيّن العمل أو يعيد تعيينه أو ينقله.",
    previewTitle: "معاينة توصية التوجيه", previewCopy: "تقييم فقط — لن يغيّر هذا مالك الحالة ولا الشخص المكلّف بهذا العمل.",
    previewIntro: "اعرف من سيوصي به التوجيه اليوم لطبيب ومجال رعاية ولغة مريض، وفق القواعد والفرق السارية. هذه محاكاة التوجيه في المحرك؛ لا تُحفظ أبدًا.",
    previewClinician: "الطبيب", previewAnyClinician: "بلا طبيب محدد", previewCareArea: "مجال الرعاية", previewLanguage: "لغة المريض", previewAny: "غير محدد",
    whatIf: "ماذا لو…", whatIfHint: "جرّب منسقًا أو فريقًا مفضّلًا غير محفوظ.", whatIfCoordinator: "المنسق المفضّل", whatIfTeam: "الفريق المفضّل",
    runPreview: "معاينة التوصية", recommended: "الموصى به", noRecommendation: "لا يوجد مؤهل", why: "السبب", viaTeam: (t: string) => `عبر ${t}`,
    otherCandidates: "منسقون مؤهلون آخرون", notEligible: "غير مؤهلين", caseloadLabel: "عبء الحالات", languageMatch: "يتحدث لغة المريض", noLanguageMatch: "لغة مختلفة",
    previewRules: (v: number) => `قُيّم وفق إصدار القواعد ${v}.`,
    historyTitle: "سجل قرارات التوجيه", historyIntro: "كل قرارات التوجيه، الأحدث أولًا.",
    historyEmpty: "لم تُسجَّل قرارات توجيه بعد.",
    entry: { recommendation: "سُجّلت توصية", evaluationOnly: "تقييم فقط — لم يتغير شيء", applied: "طُبّق على الحالة", manual: "تعيين يدوي", automatic: "عيّنه التوجيه", queued: "نُقل إلى قائمة الانتظار" },
    matched: "طابق المنسق الحالي", differed: "اختلف عن المنسق الحالي", recommendedPerson: "الموصى به", from: "من", to: "إلى", by: "بواسطة", nobody: "لا أحد",
    liveQueueTitle: "حالات التوجيه الفعلي بانتظار منسق",
    liveQueueIntro: "الحالات التي لم يجد لها التوجيه أحدًا مؤهلًا أو التي أُوقفت. يعيّنها مدير التنسيق هنا.",
    liveQueueEmpty: "لا توجد حالة توجيه فعلي منتظرة.", waitingSince: "تنتظر منذ", deadline: "المهلة", assign: "تعيين منسق",
    assignTitle: (c: string) => `تعيين منسق للحالة ${c}`,
    assignChanges: "يصبح المنسق مالك الحالة، وينتقل إليه عمل التنسيق المفتوح عليها، ويُشعَر في بوابة الموظفين وبالبريد.",
    assignKeeps: "لا يتغير عمل الاستشاري والعمليات والمالية. يُضاف القرار إلى سجل قرارات التوجيه.",
    assignEligible: "المنسقون المؤهلون (من أحدث تقييم توجيه)", assignNone: "لم يجد التوجيه أحدًا مؤهلًا. غيّر الفرق أو السعة أولًا.", assignConfirm: "تعيين المنسق", assignDone: "تم تعيين المنسق.",
    technicalTitle: "الإعداد التقني", technicalIntro: "إعداد القواعد المخزّن والمعرّفات الداخلية، لفريق الدعم.",
    stale: "تغيّر هذا منذ فتحته. حدّث الصفحة وحاول مجددًا — لم يُحفظ شيء.",

    exclusions: {
      ACCESS_OR_MEMBERSHIP_DENIED: "لا صلاحية لاستقبال عمل التنسيق هنا", STAFF_DISABLED: "حساب المنسق معطّل",
      NO_ACTIVE_TEAM: "ليس في فريق نشط لهذا المجال", CARE_AREA_MISMATCH: "لا يغطي مجال الرعاية هذا", LANGUAGE_MISMATCH: "لا يتحدث لغة المريض",
      OFF_DUTY: "خارج الخدمة", AT_CAPACITY: "بلغ الحد الأقصى للحالات",
    } as Record<string, string>,
    paths: {
      CONTINUITY: "يبقى المنسق الحالي (الاستمرارية)", PREFERRED_COORDINATOR: "المنسق المفضّل لدى الطبيب", PREFERRED_TEAM: "من الفريق المفضّل لدى الطبيب",
      PROVIDER_TEAM: "من فريق الجهة", CARE_AREA_TEAM: "من فريق مجال الرعاية", DEFAULT_TEAM: "من الفريق الافتراضي",
      CONSULTANT_FALLBACK_TEAM: "من الفريق الاحتياطي للطبيب", FALLBACK_TEAM: "من فريق الملاذ الأخير", TEAM_FALLBACK: "من الفريق الاحتياطي لفريق",
      SCORED_POOL: "أفضل منسق متاح عبر الفرق", NO_ELIGIBLE_COORDINATOR: "لم يكن أحد مؤهلًا",
      MANUAL_ASSIGN: "عيّنه مدير التنسيق", MANUAL_REASSIGN: "أعاد تعيينه مدير التنسيق", MANUAL_QUEUE: "نقله مدير التنسيق إلى قائمة الانتظار",
    } as Record<string, string>,
  },
};

export type CoordCopy = (typeof coordCopy)["en"];
export const exclusionLabel = (code: string, locale: Locale): string => coordCopy[locale].exclusions[code] ?? code;
export const pathLabel = (code: string, locale: Locale): string => coordCopy[locale].paths[code] ?? code;
export const LANGUAGES: Record<string, [string, string]> = { en: ["English", "الإنجليزية"], ar: ["Arabic", "العربية"] };
export const languageLabel = (code: string, locale: Locale) => LANGUAGES[code.toLowerCase()]?.[locale === "ar" ? 1 : 0] ?? code;
