package com.rehletshifaa.coordination.infrastructure;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.rehletshifaa.coordination.domain.Routing.*;
import com.rehletshifaa.shared.api.ApiException;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Repository;
import java.time.*;
import java.util.*;
import java.sql.*;
import static com.rehletshifaa.shared.persistence.SqlValues.timestamp;

@Repository
public class CoordinationRepository {
    private final JdbcClient jdbc;
    private final ObjectMapper json;
    public CoordinationRepository(JdbcClient jdbc,ObjectMapper json){this.jdbc=jdbc;this.json=json;}
    public String encode(Object value){try{return json.writeValueAsString(value);}catch(Exception e){throw new IllegalStateException(e);}}
    public <T> T decode(String value,Class<T> type){try{return json.readValue(value,type);}catch(Exception e){throw new IllegalStateException("Invalid persisted routing data",e);}}
    public void lock(){jdbc.sql("SELECT id FROM access_bootstrap WHERE id=1 FOR UPDATE").query(Integer.class).single();}
    public boolean organization(UUID org,boolean lock){return jdbc.sql("SELECT id FROM provider_organizations WHERE id=? AND status NOT IN ('SUSPENDED','OFFBOARDED')"+(lock?" FOR UPDATE":"")).param(org).query(UUID.class).optional().isPresent();}
    public void lockCase(UUID id){jdbc.sql("SELECT id FROM medical_cases WHERE id=? FOR UPDATE").param(id).query(UUID.class).optional().orElseThrow(()->new ApiException(404,"CASE_NOT_FOUND","Case was not found"));}
    public boolean consultant(UUID org,UUID id){return count("SELECT COUNT(*) FROM clinician_onboardings WHERE organization_id=? AND practitioner_id=? AND clinician_type='CONSULTANT' AND status NOT IN ('OFFBOARDED','SUSPENDED')",org,id)>0;}
    public List<Team> teams(UUID org){return jdbc.sql("SELECT * FROM coordinator_teams WHERE organization_id=? ORDER BY name,id").param(org).query((r,n)->new Team(r.getObject("id",UUID.class),org,r.getString("name"),decode(r.getString("configuration"),TeamConfig.class),r.getLong("revision"))).list();}
    public void team(Team t,boolean create){if(create)update("INSERT INTO coordinator_teams(id,organization_id,name,configuration,revision) VALUES(?,?,?,?,0)",t.id(),t.organizationId(),t.name(),encode(t.configuration()));else stale(update("UPDATE coordinator_teams SET name=?,configuration=?,revision=revision+1 WHERE id=? AND organization_id=? AND revision=?",t.name(),encode(t.configuration()),t.id(),t.organizationId(),t.revision()));}
    public List<Member> members(UUID team){return jdbc.sql("SELECT * FROM coordinator_memberships WHERE team_id=? ORDER BY subject").param(team).query((r,n)->new Member(r.getString("subject"),instant(r,"effective_from"),instant(r,"effective_to"),r.getBoolean("active"),r.getBoolean("team_lead"),r.getLong("revision"))).list();}
    public void member(UUID team,Member m){if(count("SELECT COUNT(*) FROM coordinator_memberships WHERE team_id=? AND subject=?",team,m.subject())==0){if(m.revision()!=-1)stale(0);update("INSERT INTO coordinator_memberships(team_id,subject,effective_from,effective_to,active,team_lead) VALUES(?,?,?,?,?,?)",team,m.subject(),timestamp(m.effectiveFrom()),timestamp(m.effectiveTo()),m.active(),m.lead());}else stale(update("UPDATE coordinator_memberships SET effective_from=?,effective_to=?,active=?,team_lead=?,revision=revision+1 WHERE team_id=? AND subject=? AND revision=?",timestamp(m.effectiveFrom()),timestamp(m.effectiveTo()),m.active(),m.lead(),team,m.subject(),m.revision()));}
    public List<Capacity> capacities(UUID org){return jdbc.sql("SELECT * FROM coordinator_capacity WHERE organization_id=? ORDER BY subject").param(org).query((r,n)->new Capacity(r.getString("subject"),r.getInt("maximum"),r.getBoolean("on_duty"),split(r.getString("languages")),split(r.getString("care_areas")),r.getLong("revision"))).list();}
    public void capacity(UUID org,Capacity c){if(count("SELECT COUNT(*) FROM coordinator_capacity WHERE organization_id=? AND subject=?",org,c.subject())==0){if(c.revision()!=-1)stale(0);update("INSERT INTO coordinator_capacity(organization_id,subject,maximum,on_duty,languages,care_areas) VALUES(?,?,?,?,?,?)",org,c.subject(),c.maximum(),c.onDuty(),join(c.languages()),join(c.careAreas()));}else stale(update("UPDATE coordinator_capacity SET maximum=?,on_duty=?,languages=?,care_areas=?,revision=revision+1 WHERE organization_id=? AND subject=? AND revision=?",c.maximum(),c.onDuty(),join(c.languages()),join(c.careAreas()),org,c.subject(),c.revision()));}
    public List<Policy> policies(UUID org){return jdbc.sql("SELECT * FROM coordination_policy_versions WHERE organization_id=? ORDER BY version_number DESC").param(org).query((r,n)->new Policy(r.getObject("id",UUID.class),org,r.getInt("version_number"),instant(r,"effective_from"),instant(r,"effective_to"),decode(r.getString("configuration"),PolicyConfig.class))).list();}
    public void policy(Policy p,String actor,Instant now){update("INSERT INTO coordination_policy_versions(id,organization_id,version_number,effective_from,effective_to,configuration,created_by,created_at) VALUES(?,?,?,?,?,?,?,?)",p.id(),p.organizationId(),p.version(),timestamp(p.effectiveFrom()),timestamp(p.effectiveTo()),encode(p.configuration()),actor,timestamp(now));}
    public List<Preference> preferences(UUID org,UUID consultant){return jdbc.sql("SELECT * FROM consultant_routing_preferences WHERE organization_id=? AND consultant_id=? ORDER BY version_number DESC").params(org,consultant).query((r,n)->new Preference(r.getObject("id",UUID.class),org,consultant,r.getInt("version_number"),instant(r,"effective_from"),instant(r,"effective_to"),r.getString("coordinator_subject"),r.getObject("team_id",UUID.class),r.getObject("fallback_team_id",UUID.class))).list();}
    public void preference(Preference p,String actor){update("INSERT INTO consultant_routing_preferences(id,organization_id,consultant_id,version_number,effective_from,effective_to,coordinator_subject,team_id,fallback_team_id,created_by) VALUES(?,?,?,?,?,?,?,?,?,?)",p.id(),p.organizationId(),p.consultantId(),p.version(),timestamp(p.effectiveFrom()),timestamp(p.effectiveTo()),p.coordinator(),p.team(),p.fallbackTeam(),actor);}
    public List<UUID[]> provenance(UUID caseId){return jdbc.sql("SELECT DISTINCT o.organization_id,o.practitioner_id FROM case_assignments a JOIN practitioner_profiles p ON p.external_subject=a.assignee_subject JOIN clinician_onboardings o ON o.practitioner_id=p.id WHERE a.case_id=? AND a.assignee_role='DOCTOR' AND a.status IN ('ACTIVE','PENDING') AND o.clinician_type='CONSULTANT' AND o.status NOT IN ('OFFBOARDED','SUSPENDED')").param(caseId).query((r,n)->new UUID[]{r.getObject(1,UUID.class),r.getObject(2,UUID.class)}).list();}
    public boolean bound(UUID id){return count("SELECT COUNT(*) FROM coordination_case_routing WHERE case_id=?",id)>0;}
    public void bind(UUID id,UUID org,UUID consultant){update("INSERT INTO coordination_case_routing(case_id,organization_id,consultant_id,mode) VALUES(?,?,?,'SHADOW')",id,org,consultant);}
    public CaseFacts facts(UUID id){return jdbc.sql("SELECT r.*,c.care_category,c.preferred_language,c.status FROM coordination_case_routing r JOIN medical_cases c ON c.id=r.case_id WHERE r.case_id=?").param(id).query((r,n)->new CaseFacts(id,r.getObject("organization_id",UUID.class),r.getObject("consultant_id",UUID.class),r.getString("care_category"),r.getString("preferred_language"),owner(id),r.getString("mode"),r.getLong("revision"),r.getString("status"))).optional().orElseThrow(()->new ApiException(404,"ROUTING_NOT_FOUND","Routing scope was not found"));}
    public String owner(UUID id){return jdbc.sql("SELECT assignee_subject FROM case_assignments WHERE case_id=? AND assignee_role='COORDINATOR' AND assignment_type='PRIMARY' AND status='ACTIVE' ORDER BY assigned_at DESC,id LIMIT 1").param(id).query(String.class).optional().orElse(null);}
    public long workload(String subject,UUID excludedCase){return count("SELECT COUNT(DISTINCT a.case_id) FROM case_assignments a JOIN medical_cases c ON c.id=a.case_id WHERE a.assignee_subject=? AND a.assignee_role='COORDINATOR' AND a.assignment_type='PRIMARY' AND a.status='ACTIVE' AND c.status NOT IN ('CLOSED','CANCELLED') AND a.case_id<>?",subject,excludedCase);}
    public boolean staffEnabled(String subject){return count("SELECT COUNT(*) FROM staff_members WHERE external_subject=? AND staff_role IN ('COORDINATOR','COORDINATOR_LEAD') AND disabled_at IS NULL AND (invitation_status IS NULL OR invitation_status<>'DISABLED')",subject)>0;}
    public boolean queued(UUID caseId){return count("SELECT COUNT(*) FROM case_tasks WHERE case_id=? AND task_type='COORDINATION_ROUTING' AND status IN ('OPEN','IN_PROGRESS') AND owner_subject IS NULL",caseId)>0;}
    public List<UUID> queuedCases(){return jdbc.sql("SELECT DISTINCT r.case_id FROM coordination_case_routing r JOIN case_tasks t ON t.case_id=r.case_id WHERE r.mode='LIVE' AND t.task_type='COORDINATION_ROUTING' AND t.status IN ('OPEN','IN_PROGRESS') AND t.owner_subject IS NULL AND t.coordination_queue_reason<>'MANUAL_QUEUE' ORDER BY r.case_id LIMIT 100").query(UUID.class).list();}
    public Instant lastAutomatic(String subject){return jdbc.sql("SELECT MAX(assigned_at) FROM case_assignments WHERE assignee_subject=? AND assignee_role='COORDINATOR' AND assigned_by='ROUTING_ENGINE'").param(subject).query((r,n)->instant(r,1)).optional().orElse(null);}
    public Optional<Decision> replay(UUID id,String actor,String key,String payload){return jdbc.sql("SELECT request_data,result_data FROM coordination_decisions WHERE case_id=? AND actor_subject=? AND command_key=?").params(id,actor,key).query((r,n)->{if(!r.getString(1).equals(payload))throw new ApiException(409,"IDEMPOTENCY_CONFLICT","Command key was already used for different input");return decode(r.getString(2),Decision.class);}).optional();}
    public List<Decision> history(UUID org,UUID id){return jdbc.sql("SELECT result_data FROM coordination_decisions WHERE organization_id=? AND case_id=? ORDER BY created_at DESC,id DESC").params(org,id).query((r,n)->decode(r.getString(1),Decision.class)).list();}
    public void decision(Decision d,UUID org,String actor,String key,String request){update("INSERT INTO coordination_decisions(id,case_id,organization_id,actor_subject,command_key,request_data,policy_id,result_data,created_at) VALUES(?,?,?,?,?,?,?,?,?)",d.id(),d.caseId(),org,actor,key,request,d.policyId(),encode(d),timestamp(d.evaluatedAt()));}
    public void advance(CaseFacts c,String mode){stale(update("UPDATE coordination_case_routing SET mode=?,revision=revision+1 WHERE case_id=? AND revision=?",mode,c.id(),c.revision()));}
    public void owner(CaseFacts c,String selected,String actor,String reason,Instant now){if(Objects.equals(c.owner(),selected))return;update("UPDATE case_assignments SET status='ENDED',ended_at=?,version=version+1 WHERE case_id=? AND assignee_role='COORDINATOR' AND assignment_type='PRIMARY' AND status IN ('ACTIVE','PENDING')",timestamp(now),c.id());if(selected!=null)update("INSERT INTO case_assignments(id,case_id,assignee_subject,assignee_role,assignment_type,status,reason,assigned_by,assigned_at,accepted_at,version) VALUES(?,?,?,'COORDINATOR','PRIMARY','ACTIVE',?,?,?,?,0)",UUID.randomUUID(),c.id(),selected,reason,actor,timestamp(now),timestamp(now));
        update("UPDATE case_tasks SET owner_subject=?,updated_at=?,version=version+1 WHERE case_id=? AND owner_role='COORDINATOR' AND visibility_scope='INTERNAL' AND status IN ('OPEN','IN_PROGRESS') AND (owner_subject IS NULL OR owner_subject=?)",selected,timestamp(now),c.id(),c.owner());
    }
    public void queue(UUID task,UUID team,String reason,Instant now){update("UPDATE case_tasks SET coordination_team_id=?,coordination_queue_reason=?,coordination_queued_at=COALESCE(coordination_queued_at,?) WHERE id=?",team,reason,timestamp(now),task);}
    public List<QueueItem> queue(UUID org){return jdbc.sql("SELECT t.*,r.revision routing_revision FROM case_tasks t JOIN coordination_case_routing r ON r.case_id=t.case_id WHERE r.organization_id=? AND t.task_type='COORDINATION_ROUTING' AND t.status IN ('OPEN','IN_PROGRESS') AND t.owner_subject IS NULL ORDER BY t.due_at,t.id").param(org).query((r,n)->new QueueItem(r.getObject("case_id",UUID.class),r.getObject("id",UUID.class),r.getObject("coordination_team_id",UUID.class),r.getString("coordination_queue_reason"),instant(r,"coordination_queued_at"),instant(r,"due_at"),r.getLong("routing_revision"))).list();}
    public List<String> subjects(UUID org){return jdbc.sql("SELECT subject FROM access_memberships WHERE organization_id=? ORDER BY subject").param(org).query(String.class).list();}
    private int update(String sql,Object... args){return jdbc.sql(sql).params(args).update();}
    private long count(String sql,Object... args){return jdbc.sql(sql).params(args).query(Long.class).single();}
    private static Set<String> split(String s){return s.isBlank()?Set.of():Set.copyOf(Arrays.asList(s.split(",")));}
    private static String join(Set<String> s){return String.join(",",new TreeSet<>(s));}
    private static Instant instant(ResultSet r,String key)throws SQLException{Timestamp t=r.getTimestamp(key);return t==null?null:t.toInstant();}
    private static Instant instant(ResultSet r,int key)throws SQLException{Timestamp t=r.getTimestamp(key);return t==null?null:t.toInstant();}
    private static void stale(int changed){if(changed!=1)throw new ApiException(409,"STALE_ROUTING","Routing configuration changed; reload before saving");}
}
