package com.rehletshifaa.security;

public enum ActorRole {
    PATIENT, PATIENT_REPRESENTATIVE, COORDINATOR, COORDINATOR_LEAD, DOCTOR,
    OPERATIONS, FINANCE, CREDENTIALING_ADMIN, SYSTEM_ADMIN, AUDITOR
}
