"use client";

import { useState, type FormEvent } from "react";
import type { Locale } from "@/lib/i18n";

type CaseSummary={id:string;status:string;version:number};
type VerifiedDoctor={subject:string;displayName:string;specialty?:string;subspecialty?:string;availabilityStatus?:string;careCategory?:string};
type CareCategory={slug:string;nameEn:string;nameAr:string};
type StaffMember={subject:string;name:string;role:string};
type CaseDocument={documentId:string;fileName:string;status:string};
type Mutate=(path:string,body?:unknown,method?:string)=>Promise<unknown>;
const transitions:Record<string,string[]>={RECEIVED:["INTAKE_REVIEW","CANCELLED"],INTAKE_REVIEW:["INFORMATION_REQUIRED","READY_FOR_CONSULTANT","CANCELLED"],INFORMATION_REQUIRED:["INTAKE_REVIEW","READY_FOR_CONSULTANT","CANCELLED"],READY_FOR_CONSULTANT:["CANCELLED"]};
const STATE_LABELS:Record<string,{en:string;ar:string}>={INTAKE_REVIEW:{en:"Move to intake review",ar:"مراجعة الاستقبال"},INFORMATION_REQUIRED:{en:"Request more information",ar:"طلب معلومات إضافية"},CANCELLED:{en:"Cancel case",ar:"إلغاء الحالة"},PROPOSAL_PREPARATION:{en:"Prepare proposal",ar:"تحضير المقترح"},TRAVEL_COORDINATION:{en:"Start travel coordination",ar:"بدء تنسيق السفر"},ARRIVAL_CONFIRMED:{en:"Confirm arrival",ar:"تأكيد الوصول"},CLOSED:{en:"Close case",ar:"إغلاق الحالة"}};
const stateLabel=(target:string,locale:Locale)=>STATE_LABELS[target]?.[locale]??target.replaceAll("_"," ");
const words={en:{title:"Workflow controls",transition:"Change case state",reason:"Reason",assign:"Assign care-team member",subject:"OIDC account subject",selectDoctor:"Select a verified doctor",category:"Specialty / category",selectCategory:"Select a category",selectConsultant:"Select a consultant",noDoctors:"No verified consultants available — enter an account subject.",assignBtn:"Assign",reasonOptional:"Reason (optional)",selectAction:"Select an action",actAssign:"Assign to consultant",task:"Create task",taskTitle:"Task title",travel:"Update travel plan",arrival:"Planned arrival",facility:"Facility",treatment:"Record treatment episode",procedures:"Procedures / milestones",follow:"Schedule follow-up",due:"Due date",instructions:"Instructions",save:"Save"},ar:{title:"إدارة مسار العمل",transition:"تغيير حالة الطلب",reason:"سبب التغيير",assign:"تعيين عضو في فريق الرعاية",subject:"معرّف حساب الهوية",selectDoctor:"اختر طبيبًا معتمدًا",category:"التخصص / الفئة",selectCategory:"اختر الفئة",selectConsultant:"اختر الاستشاري",noDoctors:"لا يوجد استشاريون معتمدون متاحون — أدخل معرّف الحساب.",assignBtn:"تعيين",reasonOptional:"السبب (اختياري)",selectAction:"اختر إجراءً",actAssign:"تعيين استشاري",task:"إنشاء مهمة",taskTitle:"عنوان المهمة",travel:"تحديث خطة السفر",arrival:"موعد الوصول المخطط",facility:"المنشأة الطبية",treatment:"تسجيل مرحلة العلاج",procedures:"الإجراءات والمراحل",follow:"جدولة المتابعة",due:"موعد الاستحقاق",instructions:"التعليمات",save:"حفظ"}};

export function CaseWorkflowActions({locale,role,caseSummary,mutate,doctors=[],categories=[],staff=[],documents=[],canRebalance=false}:{locale:Locale;role:string;caseSummary:CaseSummary;mutate:Mutate;doctors?:VerifiedDoctor[];categories?:CareCategory[];staff?:StaffMember[];documents?:CaseDocument[];canRebalance?:boolean}){const t=words[locale];if(role==="patient"||role==="finance"||role==="admin")return null;return <section className="card mt-6 p-5"><h3 className="title mb-4">{t.title}</h3><div className="grid gap-5 lg:grid-cols-2">
 {role==="coordinator"&&<><CoordinatorFlow caseId={caseSummary.id} status={caseSummary.status} version={caseSummary.version} doctors={doctors} categories={categories} staff={staff} canRebalance={canRebalance} locale={locale} t={t} mutate={mutate}/>
 <form className="space-y-3" onSubmit={event=>submit(event,data=>mutate(`/coordinator/cases/${caseSummary.id}/tasks`,{taskType:data.get("taskType"),title:data.get("title"),description:data.get("description"),ownerSubject:data.get("ownerSubject")||null,ownerRole:data.get("ownerRole")||null,priority:data.get("priority"),blocking:data.get("blocking")==="on",dueAt:data.get("dueAt")?new Date(String(data.get("dueAt"))).toISOString():null}))}><h4 className="font-bold">{t.task}</h4><select className="field" name="taskType"><option>INFORMATION_REQUEST</option><option>DOCUMENT_REVIEW</option><option>CLINICAL_REVIEW</option><option>PROPOSAL</option><option>TRAVEL</option><option>TREATMENT</option><option>FOLLOW_UP</option><option>OTHER</option></select><input className="field" name="title" placeholder={t.taskTitle} required/><textarea className="field" name="description" placeholder={t.instructions}/><input className="field" name="ownerSubject" placeholder={t.subject}/><select className="field" name="ownerRole"><option value="">Assign to me</option><option>PATIENT</option><option>COORDINATOR</option><option>DOCTOR</option><option>OPERATIONS</option><option>FINANCE</option></select><select className="field" name="priority"><option>NORMAL</option><option>HIGH</option><option>URGENT</option><option>LOW</option></select><input className="field" name="dueAt" type="datetime-local"/><label className="flex gap-2"><input name="blocking" type="checkbox"/> Blocking</label><button className="btn-primary">{t.save}</button></form></>}
 {role==="operations"&&["ACCEPTED","TRAVEL_COORDINATION"].includes(caseSummary.status)&&<form className="space-y-3" onSubmit={event=>submit(event,data=>mutate(`/operations/cases/${caseSummary.id}/travel`,{plannedArrival:date(data.get("arrival")),confirmedArrival:data.get("confirmedArrival")?date(data.get("confirmedArrival")):null,visaStatus:data.get("visaStatus"),flightDetails:data.get("flightDetails"),facility:data.get("facility"),status:data.get("status")},"PUT"))}><h4 className="font-bold">{t.travel}</h4><input className="field" name="arrival" type="datetime-local" aria-label={t.arrival}/><input className="field" name="confirmedArrival" type="datetime-local" aria-label="Confirmed arrival"/><input className="field" name="visaStatus" placeholder="Visa status"/><input className="field" name="flightDetails" placeholder="Flight details"/><input className="field" name="facility" placeholder={t.facility}/><select className="field" name="status"><option>PLANNING</option><option>CONFIRMED</option><option>ARRIVED</option></select><button className="btn-primary">{t.save}</button></form>}
 {role==="doctor"&&<>{["ARRIVAL_CONFIRMED","TREATMENT_IN_PROGRESS"].includes(caseSummary.status)&&<form className="space-y-3" onSubmit={event=>submit(event,data=>mutate(`/doctor/cases/${caseSummary.id}/treatment-episodes`,{facility:data.get("facility"),startAt:date(data.get("startAt")),endAt:data.get("endAt")?date(data.get("endAt")):null,status:data.get("status"),plannedProcedures:data.get("procedures"),actualProcedures:data.get("procedures"),milestones:data.get("milestones"),complications:data.get("complications"),dischargeReady:data.get("dischargeReady")==="on",dischargeDocumentId:data.get("dischargeDocumentId")||null}))}><h4 className="font-bold">{t.treatment}</h4><input className="field" name="facility" placeholder={t.facility} required/><input className="field" name="startAt" type="datetime-local" required/><input className="field" name="endAt" type="datetime-local"/><select className="field" name="status"><option>PLANNED</option><option>IN_PROGRESS</option><option>COMPLETED</option></select><textarea className="field" name="procedures" placeholder={t.procedures}/><textarea className="field" name="milestones" placeholder="Milestones"/><textarea className="field" name="complications" placeholder="Complications"/><select className="field" name="dischargeDocumentId"><option value="">{locale==="ar"?"اختر مستند الخروج عند إكمال العلاج":"Select discharge document when completing treatment"}</option>{documents.filter(document=>document.status==="CLEAN").map(document=><option key={document.documentId} value={document.documentId}>{document.fileName}</option>)}</select><label className="flex gap-2"><input name="dischargeReady" type="checkbox"/> {locale==="ar"?"جاهز للخروج":"Discharge ready"}</label><button className="btn-primary">{t.save}</button></form>}
 {caseSummary.status==="DISCHARGED"&&<form className="space-y-3" onSubmit={event=>submit(event,data=>mutate(`/doctor/cases/${caseSummary.id}/follow-ups`,{dueAt:date(data.get("dueAt")),mode:data.get("mode"),requiredTests:data.get("tests"),instructions:data.get("instructions")}))}><h4 className="font-bold">{t.follow}</h4><input className="field" name="dueAt" type="datetime-local" aria-label={t.due} required/><select className="field" name="mode"><option>VIDEO</option><option>PHONE</option><option>IN_PERSON</option></select><textarea className="field" name="tests" placeholder="Required tests"/><textarea className="field" name="instructions" placeholder={t.instructions}/><button className="btn-primary">{t.save}</button></form>}</>}
 </div></section>}

function CoordinatorFlow({caseId,status,version,doctors,categories,staff,canRebalance,locale,t,mutate}:{caseId:string;status:string;version:number;doctors:VerifiedDoctor[];categories:CareCategory[];staff:StaffMember[];canRebalance:boolean;locale:Locale;t:typeof words.en;mutate:Mutate}){
 const[action,setAction]=useState("");
 const[reason,setReason]=useState("");
 const[category,setCategory]=useState("");
 const[consultant,setConsultant]=useState("");
 const canAssign=["INTAKE_REVIEW","INFORMATION_REQUIRED","READY_FOR_CONSULTANT"].includes(status);
 const options=(transitions[status]??[]).filter(s=>s!=="CONSULTANT_ASSIGNMENT_PENDING"&&s!=="READY_FOR_CONSULTANT");
 const isAssign=action==="ASSIGN_CONSULTANT";
 const consultants=doctors.filter(doc=>doc.careCategory===category);
 const categoryName=(cat:CareCategory)=>locale==="ar"?cat.nameAr:cat.nameEn;
 const reset=()=>{setAction("");setReason("");setCategory("");setConsultant("");};
 const doTransition=()=>{if(!action||isAssign)return;void mutate(`/coordinator/cases/${caseId}/transition`,{targetStatus:action,reason:reason||undefined,expectedVersion:version}).then(r=>{if(r)reset();});};
 const doAssign=()=>{if(!consultant)return;void mutate(`/coordinator/cases/${caseId}/assignments`,{assigneeSubject:consultant,assigneeRole:"DOCTOR",assignmentType:"PRIMARY",pod:null,reason:reason||"Assigned to consultant"}).then(r=>{if(r)reset();});};
 return <><div className="space-y-3"><h4 className="font-bold">{t.transition}</h4>
   <select className="field" value={action} onChange={event=>setAction(event.target.value)}><option value="">{t.selectAction}</option>{options.map(s=><option key={s} value={s}>{stateLabel(s,locale)}</option>)}{canAssign&&<option value="ASSIGN_CONSULTANT">{t.actAssign}</option>}</select>
   <input className="field" value={reason} onChange={event=>setReason(event.target.value)} placeholder={t.reasonOptional}/>
   <button className="btn-primary" disabled={!action||isAssign} onClick={doTransition}>{t.save}</button>
  </div>
  {isAssign&&<div className="space-y-3"><h4 className="font-bold">{t.assign}</h4>
   {doctors.length
     ?<><select className="field" aria-label={t.category} value={category} onChange={event=>{setCategory(event.target.value);setConsultant("");}} required><option value="" disabled>{t.selectCategory}</option>{categories.map(cat=><option key={cat.slug} value={cat.slug}>{categoryName(cat)}</option>)}</select>
        <select className="field" value={consultant} onChange={event=>setConsultant(event.target.value)} disabled={!category} required><option value="" disabled>{t.selectConsultant}</option>{consultants.map(doc=><option key={doc.subject} value={doc.subject}>{doc.displayName}{doc.subspecialty?` — ${doc.subspecialty}`:""}{doc.availabilityStatus?` (${doc.availabilityStatus})`:""}</option>)}</select>
        <button className="btn-primary" disabled={!consultant} onClick={doAssign}>{t.assignBtn}</button></>
     :<p className="text-sm text-ink-500">{t.noDoctors}</p>}
  </div>}
  {canRebalance&&<div className="space-y-3"><h4 className="font-bold">{locale==="ar"?"إعادة تعيين منسق الحالة":"Reassign case coordinator"}</h4><select className="field" defaultValue="" onChange={event=>{const subject=event.target.value;if(subject)void mutate(`/coordinator/cases/${caseId}/coordinator-assignment`,{assigneeSubject:subject,reason:"Coordinator lead reassignment"}).then(()=>{event.target.value="";});}}><option value="">{locale==="ar"?"اختر منسقًا":"Select coordinator"}</option>{staff.filter(person=>person.role==="COORDINATOR"||person.role==="COORDINATOR_LEAD").map(person=><option key={person.subject} value={person.subject}>{person.name}</option>)}</select></div>}
  {["PROPOSAL_PREPARATION","ACCEPTED","TRAVEL_COORDINATION"].includes(status)&&<div className="space-y-3"><h4 className="font-bold">Operations & finance</h4>{(status==="PROPOSAL_PREPARATION"?["OPERATIONS","FINANCE"]:["OPERATIONS"]).map(role=><select key={role} className="field" defaultValue="" onChange={event=>{const subject=event.target.value;if(subject)void mutate(`/coordinator/cases/${caseId}/assignments`,{assigneeSubject:subject,assigneeRole:role,assignmentType:"PRIMARY",pod:null,reason:`Assigned to ${role.toLowerCase()}`}).then(()=>{event.target.value="";});}}><option value="">Assign {role.toLowerCase()}</option>{staff.filter(person=>person.role===role).map(person=><option key={person.subject} value={person.subject}>{person.name}</option>)}</select>)}</div>}
 </>;
}
function submit(event:FormEvent<HTMLFormElement>,action:(data:FormData)=>Promise<unknown>){event.preventDefault();const form=event.currentTarget;void action(new FormData(form)).then(result=>{if(result)form.reset();});}
function date(value:FormDataEntryValue|null){return value?new Date(String(value)).toISOString():null;}
