"use client";

import { useState, type FormEvent } from "react";
import type { Locale } from "@/lib/i18n";

type CaseSummary={id:string;status:string;version:number;careCategory?:string};
type VerifiedDoctor={subject:string;displayName:string;specialty?:string;subspecialty?:string;availabilityStatus?:string;careCategory?:string};
type CareCategory={slug:string;nameEn:string;nameAr:string};
type StaffMember={subject:string;name:string;role:string};
type CaseDocument={documentId:string;fileName:string;status:string};
type Mutate=(path:string,body?:unknown,method?:string)=>Promise<unknown>;
const transitions:Record<string,string[]>={RECEIVED:["INTAKE_REVIEW","CANCELLED"],INTAKE_REVIEW:["INFORMATION_REQUIRED","READY_FOR_CONSULTANT","CANCELLED"],INFORMATION_REQUIRED:["INTAKE_REVIEW","READY_FOR_CONSULTANT","CANCELLED"],READY_FOR_CONSULTANT:["CANCELLED"]};
const STATE_LABELS:Record<string,{en:string;ar:string}>={INTAKE_REVIEW:{en:"Move to intake review",ar:"مراجعة الاستقبال"},INFORMATION_REQUIRED:{en:"Request more information",ar:"طلب معلومات إضافية"},CANCELLED:{en:"Cancel case",ar:"إلغاء الحالة"},PROPOSAL_PREPARATION:{en:"Prepare proposal",ar:"تحضير المقترح"},TRAVEL_COORDINATION:{en:"Start travel coordination",ar:"بدء تنسيق السفر"},ARRIVAL_CONFIRMED:{en:"Confirm arrival",ar:"تأكيد الوصول"},CLOSED:{en:"Close case",ar:"إغلاق الحالة"}};
const stateLabel=(target:string,locale:Locale)=>STATE_LABELS[target]?.[locale]??target.replaceAll("_"," ");
const words={en:{title:"Workflow controls",transition:"Change case state",reason:"Reason",assign:"Assign care-team member",assignHelp:"Confirm or correct the case care area. Only matching available verified consultants will be shown.",subject:"OIDC account subject",selectDoctor:"Select a verified doctor",category:"Case care area",selectCategory:"Select a care area",selectConsultant:"Select a matching consultant",noDoctors:"No verified consultants are currently available for this care area.",saveCategory:"Save care area",categorySaved:"Saved care area",assignBtn:"Assign consultant",reasonOptional:"Reason (optional)",selectAction:"Select an action",task:"Create task",taskTitle:"Task title",travel:"Update travel plan",arrival:"Planned arrival",facility:"Facility",treatment:"Record treatment episode",procedures:"Procedures / milestones",follow:"Schedule follow-up",due:"Due date",instructions:"Instructions",save:"Save"},ar:{title:"إدارة مسار العمل",transition:"تغيير حالة الطلب",reason:"سبب التغيير",assign:"تعيين عضو في فريق الرعاية",assignHelp:"أكّد مجال رعاية الحالة أو صححه. سيظهر فقط الاستشاريون المعتمدون والمتاحون المطابقون للمجال.",subject:"معرّف حساب الهوية",selectDoctor:"اختر طبيبًا معتمدًا",category:"مجال رعاية الحالة",selectCategory:"اختر مجال الرعاية",selectConsultant:"اختر استشاريًا مطابقًا",noDoctors:"لا يوجد استشاريون معتمدون متاحون لهذا المجال حاليًا.",saveCategory:"حفظ مجال الرعاية",categorySaved:"مجال الرعاية المحفوظ",assignBtn:"تعيين الاستشاري",reasonOptional:"السبب (اختياري)",selectAction:"اختر إجراءً",task:"إنشاء مهمة",taskTitle:"عنوان المهمة",travel:"تحديث خطة السفر",arrival:"موعد الوصول المخطط",facility:"المنشأة الطبية",treatment:"تسجيل مرحلة العلاج",procedures:"الإجراءات والمراحل",follow:"جدولة المتابعة",due:"موعد الاستحقاق",instructions:"التعليمات",save:"حفظ"}};

export function CaseWorkflowActions({locale,role,caseSummary,mutate,doctors=[],categories=[],staff=[],documents=[]}:{locale:Locale;role:string;caseSummary:CaseSummary;mutate:Mutate;doctors?:VerifiedDoctor[];categories?:CareCategory[];staff?:StaffMember[];documents?:CaseDocument[]}){const t=words[locale];const guide=locale==="ar"?{title:"الخطوة التالية لهذه الحالة",intro:"تظهر هنا فقط الإجراءات المسموح بها في المرحلة الحالية من رحلة الرعاية. كل إجراء يحدّث حالة الطلب وسجل التدقيق.",current:"المرحلة الحالية"}:{title:"Next step for this case",intro:"Only actions permitted at the current care-journey stage appear here. Each action updates the case status and audit history.",current:"Current stage"};if(role==="patient"||role==="finance"||role==="admin")return null;return <section className="card mt-6 overflow-hidden"><div className="border-b border-line bg-brand-50 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="title">{guide.title}</h3><span className="rounded-full bg-white px-3 py-1 text-xs font-bold text-brand-700">{guide.current}: {stateLabel(caseSummary.status,locale)}</span></div><p className="mt-2 max-w-3xl text-sm text-ink-600">{guide.intro}</p></div><div className="grid gap-6 p-5 lg:grid-cols-2">
 {role==="coordinator"&&<CoordinatorFlow caseId={caseSummary.id} status={caseSummary.status} version={caseSummary.version} careCategory={caseSummary.careCategory} doctors={doctors} categories={categories} staff={staff} locale={locale} t={t} mutate={mutate}/>}
 {role==="operations"&&["ACCEPTED","TRAVEL_COORDINATION"].includes(caseSummary.status)&&<form className="space-y-3" onSubmit={event=>submit(event,data=>mutate(`/operations/cases/${caseSummary.id}/travel`,{plannedArrival:date(data.get("arrival")),confirmedArrival:data.get("confirmedArrival")?date(data.get("confirmedArrival")):null,visaStatus:data.get("visaStatus"),flightDetails:data.get("flightDetails"),facility:data.get("facility"),status:data.get("status")},"PUT"))}><h4 className="font-bold">{t.travel}</h4><input className="field" name="arrival" type="datetime-local" aria-label={t.arrival}/><input className="field" name="confirmedArrival" type="datetime-local" aria-label="Confirmed arrival"/><input className="field" name="visaStatus" placeholder="Visa status"/><input className="field" name="flightDetails" placeholder="Flight details"/><input className="field" name="facility" placeholder={t.facility}/><select className="field" name="status"><option>PLANNING</option><option>CONFIRMED</option><option>ARRIVED</option></select><button className="btn-primary">{t.save}</button></form>}
 {role==="doctor"&&<>{["ARRIVAL_CONFIRMED","TREATMENT_IN_PROGRESS"].includes(caseSummary.status)&&<form className="space-y-3" onSubmit={event=>submit(event,data=>mutate(`/doctor/cases/${caseSummary.id}/treatment-episodes`,{facility:data.get("facility"),startAt:date(data.get("startAt")),endAt:data.get("endAt")?date(data.get("endAt")):null,status:data.get("status"),plannedProcedures:data.get("procedures"),actualProcedures:data.get("procedures"),milestones:data.get("milestones"),complications:data.get("complications"),dischargeReady:data.get("dischargeReady")==="on",dischargeDocumentId:data.get("dischargeDocumentId")||null}))}><h4 className="font-bold">{t.treatment}</h4><input className="field" name="facility" placeholder={t.facility} required/><input className="field" name="startAt" type="datetime-local" required/><input className="field" name="endAt" type="datetime-local"/><select className="field" name="status"><option>PLANNED</option><option>IN_PROGRESS</option><option>COMPLETED</option></select><textarea className="field" name="procedures" placeholder={t.procedures}/><textarea className="field" name="milestones" placeholder="Milestones"/><textarea className="field" name="complications" placeholder="Complications"/><select className="field" name="dischargeDocumentId"><option value="">{locale==="ar"?"اختر مستند الخروج عند إكمال العلاج":"Select discharge document when completing treatment"}</option>{documents.filter(document=>document.status==="CLEAN").map(document=><option key={document.documentId} value={document.documentId}>{document.fileName}</option>)}</select><label className="flex gap-2"><input name="dischargeReady" type="checkbox"/> {locale==="ar"?"جاهز للخروج":"Discharge ready"}</label><button className="btn-primary">{t.save}</button></form>}
 {caseSummary.status==="DISCHARGED"&&<form className="space-y-3" onSubmit={event=>submit(event,data=>mutate(`/doctor/cases/${caseSummary.id}/follow-ups`,{dueAt:date(data.get("dueAt")),mode:data.get("mode"),requiredTests:data.get("tests"),instructions:data.get("instructions")}))}><h4 className="font-bold">{t.follow}</h4><input className="field" name="dueAt" type="datetime-local" aria-label={t.due} required/><select className="field" name="mode"><option>VIDEO</option><option>PHONE</option><option>IN_PERSON</option></select><textarea className="field" name="tests" placeholder="Required tests"/><textarea className="field" name="instructions" placeholder={t.instructions}/><button className="btn-primary">{t.save}</button></form>}</>}
 </div></section>}

function CoordinatorFlow({caseId,status,version,careCategory,doctors,categories,staff,locale,t,mutate}:{caseId:string;status:string;version:number;careCategory?:string;doctors:VerifiedDoctor[];categories:CareCategory[];staff:StaffMember[];locale:Locale;t:typeof words.en;mutate:Mutate}){
 const[reason,setReason]=useState("");
 const[category,setCategory]=useState(careCategory??"");
 const[consultant,setConsultant]=useState("");
 const canAssign=["INTAKE_REVIEW","INFORMATION_REQUIRED","READY_FOR_CONSULTANT"].includes(status);
 const categoryChanged=category!==(careCategory??"");
 const options=(transitions[status]??[]).filter(s=>s!=="CONSULTANT_ASSIGNMENT_PENDING"&&s!=="READY_FOR_CONSULTANT");
 const consultants=doctors.filter(doc=>doc.careCategory===category);
 const categoryName=(cat:CareCategory)=>locale==="ar"?cat.nameAr:cat.nameEn;
 // Reset the editable selections when navigating to a different case or when the stored care area changes.
 const[syncKey,setSyncKey]=useState(`${caseId}|${careCategory??""}`);
 if(syncKey!==`${caseId}|${careCategory??""}`){setSyncKey(`${caseId}|${careCategory??""}`);setCategory(careCategory??"");setConsultant("");}
 const reset=()=>{setReason("");setConsultant("");};
 const doTransition=(target:string)=>{void mutate(`/coordinator/cases/${caseId}/transition`,{targetStatus:target,reason:reason||undefined,expectedVersion:version}).then(r=>{if(r)reset();});};
 const doAssign=()=>{if(!consultant)return;void mutate(`/coordinator/cases/${caseId}/assignments`,{assigneeSubject:consultant,assigneeRole:"DOCTOR",assignmentType:"PRIMARY",pod:null,reason:reason||"Assigned to consultant"}).then(r=>{if(r)reset();});};
 const saveCategory=()=>{if(!category||!categoryChanged)return;void mutate(`/coordinator/cases/${caseId}/care-category`,{careCategory:category,expectedVersion:version,reason:careCategory?"Coordinator corrected case care area":"Coordinator classified case care area"},"PUT");};
 return <>{options.length>0&&<div className="space-y-3"><h4 className="font-bold">{t.transition}</h4>
   <input className="field" value={reason} onChange={event=>setReason(event.target.value)} placeholder={t.reasonOptional}/>
   <div className="flex flex-wrap gap-2">{options.map(s=><button key={s} type="button" className={s==="CANCELLED"?"rounded-xl border border-alert-200 bg-white px-4 py-2 font-bold text-alert-700 transition hover:border-alert-400 hover:bg-alert-50":"btn-secondary"} onClick={()=>doTransition(s)}>{stateLabel(s,locale)}</button>)}</div>
  </div>}
  {canAssign&&<div className="space-y-3 rounded-xl border border-brand-200 bg-brand-50 p-4"><h4 className="font-bold text-brand-900">{t.assign}</h4><p className="text-sm leading-6 text-ink-600">{t.assignHelp}</p>
   <label className="block text-sm font-bold">{t.category}<select className="field mt-2" aria-label={t.category} value={category} onChange={event=>{setCategory(event.target.value);setConsultant("");}} required><option value="" disabled>{t.selectCategory}</option>{categories.map(cat=><option key={cat.slug} value={cat.slug}>{categoryName(cat)}</option>)}</select></label>
   {categoryChanged?<button className="btn-secondary" disabled={!category} onClick={saveCategory}>{t.saveCategory}</button>:category&&<p className="text-xs font-bold text-brand-700">✓ {t.categorySaved}</p>}
   <select className="field" value={consultant} onChange={event=>setConsultant(event.target.value)} disabled={!category||categoryChanged} required><option value="" disabled>{t.selectConsultant}</option>{consultants.map(doc=><option key={doc.subject} value={doc.subject}>{doc.displayName}{doc.subspecialty?` — ${doc.subspecialty}`:""}{doc.availabilityStatus?` (${doc.availabilityStatus})`:""}</option>)}</select>
   {!categoryChanged&&category&&consultants.length===0&&<p className="text-sm text-ink-500">{t.noDoctors}</p>}
   <button className="btn-primary" disabled={!consultant||categoryChanged} onClick={doAssign}>{t.assignBtn}</button>
  </div>}
  {["PROPOSAL_PREPARATION","ACCEPTED","TRAVEL_COORDINATION"].includes(status)&&<div className="space-y-3"><h4 className="font-bold">Operations & finance</h4>{(status==="PROPOSAL_PREPARATION"?["OPERATIONS","FINANCE"]:["OPERATIONS"]).map(role=><select key={role} className="field" defaultValue="" onChange={event=>{const subject=event.target.value;if(subject)void mutate(`/coordinator/cases/${caseId}/assignments`,{assigneeSubject:subject,assigneeRole:role,assignmentType:"PRIMARY",pod:null,reason:`Assigned to ${role.toLowerCase()}`}).then(()=>{event.target.value="";});}}><option value="">Assign {role.toLowerCase()}</option>{staff.filter(person=>person.role===role).map(person=><option key={person.subject} value={person.subject}>{person.name}</option>)}</select>)}</div>}
 </>;
}
export function TaskCreateForm({locale,caseId,mutate}:{locale:Locale;caseId:string;mutate:Mutate}){const t=words[locale];return <section className="card mt-6 p-5"><h3 className="title mb-4">{t.task}</h3><form className="space-y-3" onSubmit={event=>submit(event,data=>mutate(`/coordinator/cases/${caseId}/tasks`,{taskType:data.get("taskType"),title:data.get("title"),description:data.get("description"),ownerSubject:data.get("ownerSubject")||null,ownerRole:data.get("ownerRole")||null,priority:data.get("priority"),blocking:data.get("blocking")==="on",dueAt:data.get("dueAt")?new Date(String(data.get("dueAt"))).toISOString():null}))}><input className="field" name="title" placeholder={t.taskTitle} required/><textarea className="field" name="description" placeholder={t.instructions}/><div className="grid gap-3 sm:grid-cols-2"><select className="field" name="taskType" aria-label="Task type"><option>INFORMATION_REQUEST</option><option>DOCUMENT_REVIEW</option><option>CLINICAL_REVIEW</option><option>PROPOSAL</option><option>TRAVEL</option><option>TREATMENT</option><option>FOLLOW_UP</option><option>OTHER</option></select><select className="field" name="ownerRole" aria-label="Assign to"><option value="">Assign to me</option><option>PATIENT</option><option>COORDINATOR</option><option>DOCTOR</option><option>OPERATIONS</option><option>FINANCE</option></select><select className="field" name="priority" aria-label="Priority"><option>NORMAL</option><option>HIGH</option><option>URGENT</option><option>LOW</option></select><input className="field" name="dueAt" type="datetime-local" aria-label={t.due}/></div><input className="field" name="ownerSubject" placeholder={t.subject}/><label className="flex items-center gap-2 text-sm"><input name="blocking" type="checkbox"/> Blocking</label><button className="btn-primary">{t.task}</button></form></section>;}
function submit(event:FormEvent<HTMLFormElement>,action:(data:FormData)=>Promise<unknown>){event.preventDefault();const form=event.currentTarget;void action(new FormData(form)).then(result=>{if(result)form.reset();});}
function date(value:FormDataEntryValue|null){return value?new Date(String(value)).toISOString():null;}
