"use client";

import type { FormEvent } from "react";
import type { Locale } from "@/lib/i18n";

type CaseSummary={id:string;status:string;version:number};
type Mutate=(path:string,body?:unknown,method?:string)=>Promise<unknown>;
const transitions:Record<string,string[]>={RECEIVED:["INTAKE_REVIEW","CANCELLED"],INTAKE_REVIEW:["INFORMATION_REQUIRED","READY_FOR_CONSULTANT","CANCELLED"],INFORMATION_REQUIRED:["INTAKE_REVIEW","READY_FOR_CONSULTANT","CANCELLED"],READY_FOR_CONSULTANT:["CONSULTANT_ASSIGNMENT_PENDING","CANCELLED"],REVISION_REQUESTED:["PROPOSAL_PREPARATION"],ACCEPTED:["TRAVEL_COORDINATION"],TRAVEL_COORDINATION:["ARRIVAL_CONFIRMED","CANCELLED"],FOLLOW_UP:["CLOSED"]};
const words={en:{title:"Workflow controls",transition:"Change case state",reason:"Reason",assign:"Assign care-team member",subject:"OIDC account subject",task:"Create task",taskTitle:"Task title",travel:"Update travel plan",arrival:"Planned arrival",facility:"Facility",treatment:"Record treatment episode",procedures:"Procedures / milestones",follow:"Schedule follow-up",due:"Due date",instructions:"Instructions",save:"Save"},ar:{title:"إدارة مسار العمل",transition:"تغيير حالة الطلب",reason:"سبب التغيير",assign:"تعيين عضو في فريق الرعاية",subject:"معرّف حساب الهوية",task:"إنشاء مهمة",taskTitle:"عنوان المهمة",travel:"تحديث خطة السفر",arrival:"موعد الوصول المخطط",facility:"المنشأة الطبية",treatment:"تسجيل مرحلة العلاج",procedures:"الإجراءات والمراحل",follow:"جدولة المتابعة",due:"موعد الاستحقاق",instructions:"التعليمات",save:"حفظ"}};

export function CaseWorkflowActions({locale,role,caseSummary,mutate}:{locale:Locale;role:string;caseSummary:CaseSummary;mutate:Mutate}){const t=words[locale];if(role==="patient"||role==="finance"||role==="admin")return null;return <section className="card mt-6 p-5"><h3 className="title mb-4">{t.title}</h3><div className="grid gap-5 lg:grid-cols-2">
 {role==="coordinator"&&<><form className="space-y-3" onSubmit={event=>submit(event,data=>mutate(`/coordinator/cases/${caseSummary.id}/transition`,{targetStatus:data.get("targetStatus"),reason:data.get("reason"),expectedVersion:caseSummary.version}))}><h4 className="font-bold">{t.transition}</h4><select className="field" name="targetStatus" required>{(transitions[caseSummary.status]??[]).map(value=><option key={value} value={value}>{value.replaceAll("_"," ")}</option>)}</select><input className="field" name="reason" placeholder={t.reason} required/><button className="btn-primary">{t.save}</button></form>
 <form className="space-y-3" onSubmit={event=>submit(event,data=>mutate(`/coordinator/cases/${caseSummary.id}/assignments`,{assigneeSubject:data.get("subject"),assigneeRole:data.get("role"),assignmentType:"PRIMARY",pod:data.get("pod"),reason:data.get("reason")}))}><h4 className="font-bold">{t.assign}</h4><select className="field" name="role"><option value="DOCTOR">DOCTOR</option><option value="OPERATIONS">OPERATIONS</option><option value="FINANCE">FINANCE</option></select><input className="field" name="subject" placeholder={t.subject} required/><input className="field" name="pod" placeholder="Pod"/><input className="field" name="reason" placeholder={t.reason} required/><button className="btn-primary">{t.save}</button></form>
 <form className="space-y-3" onSubmit={event=>submit(event,data=>mutate(`/coordinator/cases/${caseSummary.id}/tasks`,{taskType:"FOLLOW_UP",title:data.get("title"),description:data.get("description"),ownerSubject:data.get("ownerSubject")||null,ownerRole:data.get("ownerRole")||null,priority:data.get("priority"),blocking:data.get("blocking")==="on",dueAt:data.get("dueAt")?new Date(String(data.get("dueAt"))).toISOString():null}))}><h4 className="font-bold">{t.task}</h4><input className="field" name="title" placeholder={t.taskTitle} required/><textarea className="field" name="description" placeholder={t.instructions}/><input className="field" name="ownerSubject" placeholder={t.subject}/><select className="field" name="ownerRole"><option value="">Unassigned</option><option>COORDINATOR</option><option>DOCTOR</option><option>OPERATIONS</option></select><select className="field" name="priority"><option>NORMAL</option><option>HIGH</option><option>URGENT</option><option>LOW</option></select><input className="field" name="dueAt" type="datetime-local"/><label className="flex gap-2"><input name="blocking" type="checkbox"/> Blocking</label><button className="btn-primary">{t.save}</button></form></>}
 {role==="operations"&&<form className="space-y-3" onSubmit={event=>submit(event,data=>mutate(`/operations/cases/${caseSummary.id}/travel`,{plannedArrival:date(data.get("arrival")),confirmedArrival:data.get("confirmedArrival")?date(data.get("confirmedArrival")):null,visaStatus:data.get("visaStatus"),flightDetails:data.get("flightDetails"),facility:data.get("facility"),status:data.get("status")},"PUT"))}><h4 className="font-bold">{t.travel}</h4><input className="field" name="arrival" type="datetime-local" aria-label={t.arrival}/><input className="field" name="confirmedArrival" type="datetime-local" aria-label="Confirmed arrival"/><input className="field" name="visaStatus" placeholder="Visa status"/><input className="field" name="flightDetails" placeholder="Flight details"/><input className="field" name="facility" placeholder={t.facility}/><select className="field" name="status"><option>PLANNING</option><option>CONFIRMED</option><option>ARRIVED</option></select><button className="btn-primary">{t.save}</button></form>}
 {role==="doctor"&&<><form className="space-y-3" onSubmit={event=>submit(event,data=>mutate(`/doctor/cases/${caseSummary.id}/treatment-episodes`,{facility:data.get("facility"),startAt:date(data.get("startAt")),endAt:data.get("endAt")?date(data.get("endAt")):null,status:data.get("status"),plannedProcedures:data.get("procedures"),actualProcedures:data.get("procedures"),milestones:data.get("milestones"),complications:data.get("complications"),dischargeReady:data.get("dischargeReady")==="on"}))}><h4 className="font-bold">{t.treatment}</h4><input className="field" name="facility" placeholder={t.facility} required/><input className="field" name="startAt" type="datetime-local" required/><input className="field" name="endAt" type="datetime-local"/><select className="field" name="status"><option>PLANNED</option><option>IN_PROGRESS</option><option>COMPLETED</option></select><textarea className="field" name="procedures" placeholder={t.procedures}/><textarea className="field" name="milestones" placeholder="Milestones"/><textarea className="field" name="complications" placeholder="Complications"/><label className="flex gap-2"><input name="dischargeReady" type="checkbox"/> Discharge ready</label><button className="btn-primary">{t.save}</button></form>
 <form className="space-y-3" onSubmit={event=>submit(event,data=>mutate(`/doctor/cases/${caseSummary.id}/follow-ups`,{dueAt:date(data.get("dueAt")),mode:data.get("mode"),requiredTests:data.get("tests"),instructions:data.get("instructions")}))}><h4 className="font-bold">{t.follow}</h4><input className="field" name="dueAt" type="datetime-local" aria-label={t.due} required/><select className="field" name="mode"><option>VIDEO</option><option>PHONE</option><option>IN_PERSON</option></select><textarea className="field" name="tests" placeholder="Required tests"/><textarea className="field" name="instructions" placeholder={t.instructions}/><button className="btn-primary">{t.save}</button></form></>}
 </div></section>}

function submit(event:FormEvent<HTMLFormElement>,action:(data:FormData)=>Promise<unknown>){event.preventDefault();const form=event.currentTarget;void action(new FormData(form)).then(()=>form.reset());}
function date(value:FormDataEntryValue|null){return value?new Date(String(value)).toISOString():null;}
