"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { useAuth } from "@/components/AuthProvider";
import { CaseWorkflowActions } from "@/components/portal/CaseWorkflowActions";
import type { Locale } from "@/lib/i18n";

type CaseView={id:string;caseNumber:string;status:string;patientName:string;country:string;preferredLanguage:string;createdAt:string;updatedAt:string;version:number;coordinatorSubject?:string;doctorSubject?:string};
type Assignment={id:string;assigneeSubject:string;assigneeRole:string;assignmentType:string;status:string;assignedAt:string;version:number};
type CaseDocument={documentId:string;fileName:string;contentType:string;sizeBytes:number;status:string;createdAt:string;confirmedAt?:string};
type VerifiedDoctor={subject:string;displayName:string;specialty?:string;subspecialty?:string;availabilityStatus?:string;careCategory?:string};
type CareCategory={slug:string;nameEn:string;nameAr:string};
type Review={id:string;versionNumber:number;status:string;suitability?:string;recommendedTreatment?:string;risksAndLimitations?:string;createdAt:string};
type ProposalItem={id:string;category:string;description:string;quantity:number;unitPrice:number;optional:boolean};
type Proposal={proposalId:string;versionId:string;versionNumber:number;status:string;language:string;currency?:string;validUntil?:string;operationalPlan?:string;items:ProposalItem[]};
type Workspace={caseSummary:CaseView;timeline:{type:string;label:string;occurredAt:string;status:string}[];tasks:{id:string;title:string;description?:string;status:string;priority:string;blocking:boolean;version:number}[];messages:{id:string;senderRole:string;body:string;createdAt:string;internalOnly:boolean}[];assignments:Assignment[];clinicalReviews:Review[];proposal?:Proposal};
type RoleKey="patient"|"coordinator"|"doctor"|"operations"|"finance"|"admin";
type MutationResult={id?:string;status?:string};
type Mutate=(path:string,body?:unknown,method?:string)=>Promise<MutationResult|undefined>;

const roleMap:Record<RoleKey,string[]>={patient:["PATIENT","PATIENT_REPRESENTATIVE"],coordinator:["COORDINATOR","COORDINATOR_LEAD"],doctor:["DOCTOR"],operations:["OPERATIONS"],finance:["FINANCE"],admin:["CREDENTIALING_ADMIN","SYSTEM_ADMIN","AUDITOR"]};
const copy={
  en:{title:"Secure care portal",subtitle:"One accountable workspace from intake through treatment and follow-up.",signIn:"Sign in securely",signOut:"Sign out",loading:"Loading your workspace…",noCases:"No cases are available in this queue.",claimTitle:"Link an existing request",caseId:"Case ID",code:"6-digit verification code",claim:"Link case",open:"Open workspace",back:"Back to queue",timeline:"Case journey",tasks:"Tasks",messages:"Secure messages",send:"Send message",message:"Write a message",assignments:"Care team",documents:"Patient documents",download:"Download",docScanning:"Security scan in progress",docUnavailable:"Unavailable",noDocuments:"No documents uploaded yet.",reviews:"Doctor reviews",coordinatorLabel:"Coordinator",consultantLabel:"Consultant",you:"You",assignedToYou:"You've been assigned to this case — accept to start your review.",proposal:"Patient proposal",coordinatorClaim:"Take ownership",ownershipHint:"You have view-only access. Take ownership to assign a consultant, change status, or create a proposal.",ownedByOther:"Another coordinator owns this case — you have view-only access.",handoff:"This case is with {name} for consultant review. Actions are locked until the clinical recommendation is ready.",status:"Status",transition:"Move case",reason:"Reason for change",doctorSubject:"Doctor account subject",assignDoctor:"Assign verified doctor",reviewTreatment:"Recommended treatment",reviewRisks:"Risks and limitations",saveReview:"Save clinical review",approveReview:"Approve review",createProposal:"Create proposal",item:"Service description",price:"Unit price",release:"Release to patient",operationsComplete:"Complete operational plan",financeApprove:"Approve commercial terms",accept:"Accept",decline:"Decline",revise:"Request revision",adminTitle:"Onboard a practitioner",name:"Legal name",subject:"Identity account subject",specialty:"Specialty",create:"Create profile",profileId:"Practitioner profile ID",credentialTitle:"Register verified credential",credentialType:"Credential type",reference:"Registration / license number",source:"Issuing authority",expires:"Expiry date",addCredential:"Add credential",decisionTitle:"Credentialing decision",approvePractitioner:"Approve practitioner",rejectPractitioner:"Reject practitioner",rejectionReason:"Rejection reason",success:"Saved successfully.",roleDenied:"Your account has no portal role assigned.",error:"The request could not be completed."},
  ar:{title:"بوابة رحلة الشفاء الآمنة",subtitle:"مساحة عمل مسؤولة واحدة من استقبال الحالة حتى العلاج والمتابعة.",signIn:"تسجيل الدخول الآمن",signOut:"تسجيل الخروج",loading:"جارٍ تحميل مساحة العمل…",noCases:"لا توجد حالات في قائمة العمل.",claimTitle:"ربط طلب سابق",caseId:"معرّف الحالة",code:"رمز التحقق المكوّن من 6 أرقام",claim:"ربط الحالة",open:"فتح مساحة العمل",back:"العودة إلى القائمة",timeline:"رحلة الحالة",tasks:"المهام",messages:"الرسائل الآمنة",send:"إرسال الرسالة",message:"اكتب رسالة",assignments:"فريق الرعاية",documents:"مستندات المريض",download:"تنزيل",docScanning:"جارٍ الفحص الأمني",docUnavailable:"غير متاح",noDocuments:"لم يتم رفع أي مستندات بعد.",reviews:"مراجعات الطبيب",coordinatorLabel:"المنسق",consultantLabel:"الاستشاري",you:"أنت",assignedToYou:"تم تعيينك لهذه الحالة — اقبل لبدء مراجعتك.",proposal:"المقترح المقدم للمريض",coordinatorClaim:"استلام مسؤولية الحالة",ownershipHint:"لديك صلاحية العرض فقط. استلم الحالة لتعيين استشاري أو تغيير الحالة أو إنشاء مقترح.",ownedByOther:"تملك هذه الحالة منسقة أخرى — لديك صلاحية العرض فقط.",handoff:"هذه الحالة قيد مراجعة الاستشاري {name}. الإجراءات مقفلة حتى تجهيز التوصية الطبية.",status:"الحالة",transition:"نقل الحالة",reason:"سبب التغيير",doctorSubject:"معرّف حساب الطبيب",assignDoctor:"تعيين طبيب معتمد",reviewTreatment:"العلاج الموصى به",reviewRisks:"المخاطر والقيود",saveReview:"حفظ المراجعة الطبية",approveReview:"اعتماد المراجعة",createProposal:"إنشاء المقترح",item:"وصف الخدمة",price:"سعر الوحدة",release:"إرسال المقترح للمريض",operationsComplete:"استكمال الخطة التشغيلية",financeApprove:"اعتماد الشروط المالية",accept:"موافقة",decline:"رفض",revise:"طلب تعديل",adminTitle:"إضافة طبيب للنظام",name:"الاسم القانوني",subject:"معرّف حساب الهوية",specialty:"التخصص",create:"إنشاء الملف",profileId:"معرّف ملف الطبيب",credentialTitle:"تسجيل مستند اعتماد",credentialType:"نوع الاعتماد",reference:"رقم التسجيل أو الترخيص",source:"جهة الإصدار",expires:"تاريخ الانتهاء",addCredential:"إضافة الاعتماد",decisionTitle:"قرار اعتماد الطبيب",approvePractitioner:"اعتماد الطبيب",rejectPractitioner:"رفض الطبيب",rejectionReason:"سبب الرفض",success:"تم الحفظ بنجاح.",roleDenied:"لا يملك هذا الحساب صلاحية لإحدى بوابات النظام.",error:"تعذر إكمال الطلب."}
};

export function Portal({locale}:{locale:Locale}){
  const t=copy[locale];const{user,roles,loading,signIn,signOut}=useAuth();const available=useMemo(()=>Object.keys(roleMap).filter(key=>roleMap[key as RoleKey].some(role=>roles.includes(role))) as RoleKey[],[roles]);
  const[active,setActive]=useState<RoleKey|undefined>();const[cases,setCases]=useState<CaseView[]>([]);const[workspace,setWorkspace]=useState<Workspace|null>(null);const[documents,setDocuments]=useState<CaseDocument[]>([]);const[doctors,setDoctors]=useState<VerifiedDoctor[]>([]);const[categories,setCategories]=useState<CareCategory[]>([]);const[busy,setBusy]=useState(false);const[notice,setNotice]=useState("");const[error,setError]=useState("");
  const currentRole=active&&available.includes(active)?active:available[0];
  const api=useCallback(async<T,>(path:string,init?:RequestInit):Promise<T>=>{if(!user)throw new Error("AUTHENTICATION_REQUIRED");const response=await fetch(`${process.env.NEXT_PUBLIC_API_BASE_URL??"http://localhost:8080"}/api/v1${path}`,{...init,headers:{Authorization:`Bearer ${user.access_token}`,...(init?.body?{"Content-Type":"application/json"}:{}),...init?.headers},cache:"no-store"});if(!response.ok){const body=await response.json().catch(()=>({message:t.error}));throw new Error(body.message??t.error);}return response.status===204?undefined as T:response.json();},[user,t.error]);
  const refresh=useCallback(async()=>{if(!currentRole||currentRole==="admin")return;setBusy(true);setError("");try{setCases(await api<CaseView[]>(`/${currentRole}/cases`));}catch(e){setError(e instanceof Error?e.message:t.error);}finally{setBusy(false);}},[currentRole,api,t.error]);
  useEffect(()=>{if(!currentRole||currentRole==="admin")return;void api<CaseView[]>(`/${currentRole}/cases`).then(setCases).catch(e=>setError(e instanceof Error?e.message:t.error));},[currentRole,api,t.error]);
  useEffect(()=>{if(currentRole!=="coordinator"){setDoctors([]);setCategories([]);return;}void api<VerifiedDoctor[]>("/coordinator/doctors").then(setDoctors).catch(()=>setDoctors([]));void api<CareCategory[]>("/coordinator/care-categories").then(setCategories).catch(()=>setCategories([]));},[currentRole,api]);
  async function openCase(item:CaseView){setBusy(true);setError("");try{const[ws,docs]=await Promise.all([api<Workspace>(`/${currentRole}/cases/${item.id}`),api<CaseDocument[]>(`/cases/${item.id}/documents`).catch(()=>[] as CaseDocument[])]);setWorkspace(ws);setDocuments(docs);}catch(e){setError(e instanceof Error?e.message:t.error);}finally{setBusy(false);}}
  async function downloadDoc(id:string){setError("");try{const res=await api<{downloadUrl:string}>(`/documents/${id}/download`);if(res?.downloadUrl)window.open(res.downloadUrl,"_blank","noopener,noreferrer");}catch(e){setError(e instanceof Error?e.message:t.error);}}
  async function mutate(path:string,body?:unknown,method="POST"):Promise<MutationResult|undefined>{setBusy(true);setError("");setNotice("");try{const result=await api<MutationResult>(path,{method,body:body===undefined?undefined:JSON.stringify(body)});setNotice(t.success);if(workspace)await openCase(workspace.caseSummary);else await refresh();return result;}catch(e){setError(e instanceof Error?e.message:t.error);return undefined;}finally{setBusy(false);}}
  if(loading)return <PortalFrame title={t.title} subtitle={t.loading}/>;
  if(!user)return <PortalFrame title={t.title} subtitle={t.subtitle}><button className="btn-primary" onClick={()=>void signIn()}>{t.signIn}</button></PortalFrame>;
  return <PortalFrame title={t.title} subtitle={t.subtitle}>
    <div className="mb-8 flex flex-wrap items-center justify-between gap-3"><div className="flex flex-wrap gap-2">{available.map(role=><button key={role} className={currentRole===role?"btn-primary":"btn-secondary"} onClick={()=>{setActive(role);setWorkspace(null);}}>{roleLabel(role,locale)}</button>)}</div><button className="btn-secondary" onClick={()=>void signOut()}>{t.signOut}</button></div>
    {!available.length&&<p className="rounded-xl bg-alert-50 p-4 text-alert-800">{t.roleDenied}</p>}
    {notice&&<p role="status" className="mb-4 rounded-xl bg-brand-50 p-4 text-brand-800">{notice}</p>}{error&&<p role="alert" className="mb-4 rounded-xl bg-alert-50 p-4 text-alert-800">{error}</p>}
    {currentRole === "admin"
      ? <AdminForm t={t} busy={busy} mutate={mutate}/>
      : workspace
        ? <WorkspaceView locale={locale} t={t} role={currentRole!} value={workspace} documents={documents} doctors={doctors} categories={categories} downloadDoc={downloadDoc} mySubject={user?.profile?.sub} busy={busy} back={()=>setWorkspace(null)} mutate={mutate}/>
        : <Queue locale={locale} t={t} role={currentRole} cases={cases} busy={busy} openCase={openCase} mutate={mutate}/>}
  </PortalFrame>;
}

function PortalFrame({title,subtitle,children}:{title:string;subtitle:string;children?:React.ReactNode}){return <section className="section bg-mist"><div className="container-site"><p className="eyebrow">RehletShifaa</p><h1 className="headline mt-3">{title}</h1><p className="lead mt-4 max-w-3xl">{subtitle}</p><div className="mt-8">{children}</div></div></section>}
function roleLabel(role:RoleKey,locale:Locale){const labels={en:{patient:"Patient",coordinator:"Coordinator",doctor:"Doctor",operations:"Operations",finance:"Finance",admin:"Credentialing"},ar:{patient:"المريض",coordinator:"منسق الحالة",doctor:"الطبيب",operations:"العمليات",finance:"المالية",admin:"اعتماد الأطباء"}};return labels[locale][role];}

function Queue({locale,t,role,cases,busy,openCase,mutate}:{locale:Locale;t:typeof copy.en;role?:RoleKey;cases:CaseView[];busy:boolean;openCase:(item:CaseView)=>void;mutate:Mutate}){
  return <div className="grid gap-6 lg:grid-cols-[1fr_2fr]">{role==="patient"&&<form className="card h-fit p-6" onSubmit={event=>{event.preventDefault();const data=new FormData(event.currentTarget);void mutate(`/patient/cases/${data.get("caseId")}/claim`,{code:data.get("code")});}}><h2 className="title">{t.claimTitle}</h2><label className="mt-4 block text-sm font-bold">{t.caseId}<input className="field mt-1" name="caseId" required/></label><label className="mt-4 block text-sm font-bold">{t.code}<input className="field mt-1" name="code" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} required/></label><button disabled={busy} className="btn-primary mt-5">{t.claim}</button></form>}<div className={`grid gap-4 ${role!=="patient"?"lg:col-span-2":""}`}>{!busy&&!cases.length&&<p className="card p-6">{t.noCases}</p>}{cases.map(item=><article key={item.id} className="card p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-bold text-brand-700">{item.caseNumber}</p><h2 className="title mt-1">{item.patientName}</h2><p className="text-ink-600">{item.country} · {new Intl.DateTimeFormat(locale).format(new Date(item.updatedAt))}</p></div><Status value={item.status} locale={locale}/></div><div className="mt-5 flex flex-wrap gap-2">{role==="coordinator"&&!item.coordinatorSubject&&<button className="btn-primary" onClick={()=>void mutate(`/coordinator/cases/${item.id}/claim`)}>{t.coordinatorClaim}</button>}<button className="btn-secondary" onClick={()=>openCase(item)}>{t.open}</button></div></article>)}</div></div>;
}

function WorkspaceView({locale,t,role,value,documents,doctors,categories,downloadDoc,mySubject,busy,back,mutate}:{locale:Locale;t:typeof copy.en;role:RoleKey;value:Workspace;documents:CaseDocument[];doctors:VerifiedDoctor[];categories:CareCategory[];downloadDoc:(id:string)=>void;mySubject?:string;busy:boolean;back:()=>void;mutate:Mutate}){
 const c=value.caseSummary;const draft=value.clinicalReviews.find(r=>r.status==="DRAFT");const approved=value.clinicalReviews.find(r=>r.status==="APPROVED");
 const isCoordinator=role==="coordinator";const owned=!!mySubject&&c.coordinatorSubject===mySubject;
 const doctorPhase=["CONSULTANT_ASSIGNMENT_PENDING","CONSULTANT_REVIEW"].includes(c.status);
 const doctorAssignment=value.assignments.find(a=>a.assigneeRole==="DOCTOR"&&(a.status==="PENDING"||a.status==="ACTIVE"));
 const assignedDoctorName=doctorAssignment?(doctors.find(d=>d.subject===doctorAssignment.assigneeSubject)?.displayName??doctorAssignment.assigneeSubject):"";
 const showActions=!isCoordinator||owned;const dim=isCoordinator&&owned&&doctorPhase;
 const isDoctor=role==="doctor";
 const myPending=isDoctor?value.assignments.find(a=>a.assigneeRole==="DOCTOR"&&a.status==="PENDING"&&(!mySubject||a.assigneeSubject===mySubject)):undefined;
 const renderWorkflow=showActions&&!(isDoctor&&doctorPhase);
 return <div>
  <button className="link-cta mb-5" onClick={back}>← {t.back}</button>
  <div className="card p-6"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-sm font-bold text-brand-700">{c.caseNumber}</p><h2 className="headline mt-1">{c.patientName}</h2><p>{c.country}</p></div><Status value={c.status} locale={locale}/></div>
   <div className="mt-4 flex flex-wrap gap-x-8 gap-y-2 border-t border-line pt-4 text-sm"><span><span className="text-ink-500">{t.status}: </span><strong>{statusLabel(c.status,locale)}</strong></span>{c.coordinatorSubject&&<span><span className="text-ink-500">{t.coordinatorLabel}: </span><strong className="break-all">{owned?t.you:c.coordinatorSubject}</strong></span>}{assignedDoctorName&&<span><span className="text-ink-500">{t.consultantLabel}: </span><strong>{assignedDoctorName}</strong></span>}</div>
  </div>
  {isCoordinator&&!owned&&<div className="mt-6 card flex flex-wrap items-center justify-between gap-3 border-l-4 border-brand-400 p-5"><p className="text-ink-600">{c.coordinatorSubject?t.ownedByOther:t.ownershipHint}</p>{!c.coordinatorSubject&&<button className="btn-primary" disabled={busy} onClick={()=>void mutate(`/coordinator/cases/${c.id}/claim`)}>{t.coordinatorClaim}</button>}</div>}
  {dim&&<div className="mt-6 card border-l-4 border-brand-400 bg-brand-50 p-5"><p className="font-bold text-brand-800">{t.handoff.replace("{name}",assignedDoctorName)}</p></div>}
  {myPending&&<div className="mt-6 card flex flex-wrap items-center justify-between gap-3 border-l-4 border-brand-400 bg-brand-50 p-5"><p className="font-bold text-brand-800">{t.assignedToYou}</p><div className="flex gap-2"><button className="btn-primary" disabled={busy} onClick={()=>void mutate(`/doctor/cases/${c.id}/assignments/${myPending.id}?accept=true`)}>{t.accept}</button><button className="btn-secondary" disabled={busy} onClick={()=>void mutate(`/doctor/cases/${c.id}/assignments/${myPending.id}?accept=false`)}>{t.decline}</button></div></div>}
  <Panel title={t.documents}>{documents.length?documents.map(doc=><div key={doc.documentId} className="flex flex-wrap items-center justify-between gap-3"><div><strong className="break-all">{doc.fileName}</strong><p className="text-sm text-ink-500">{formatBytes(doc.sizeBytes)} · {new Intl.DateTimeFormat(locale,{dateStyle:"medium"}).format(new Date(doc.createdAt))}</p></div>{doc.status==="CLEAN"?<button className="btn-secondary" onClick={()=>downloadDoc(doc.documentId)}>{t.download}</button>:<span className="rounded-full bg-mist px-3 py-1 text-sm font-bold text-ink-600">{(doc.status==="PENDING"||doc.status==="UPLOADED")?t.docScanning:t.docUnavailable}</span>}</div>):<p className="text-ink-500">{t.noDocuments}</p>}</Panel>
  <Panel title={t.reviews}>{value.clinicalReviews.length?value.clinicalReviews.map(r=><div key={r.id}><strong>v{r.versionNumber} · {r.status}</strong><p>{r.recommendedTreatment}</p>{r.risksAndLimitations&&<p className="text-sm text-ink-600">{r.risksAndLimitations}</p>}</div>):<Empty/>}{isDoctor&&<form onSubmit={event=>{event.preventDefault();const form=event.currentTarget;const data=new FormData(form);void mutate(`/doctor/cases/${c.id}/reviews`,{suitability:"SUITABLE",recommendedTreatment:data.get("treatment"),risksAndLimitations:data.get("risks")}).then(()=>form.reset());}}><textarea className="field mt-3" name="treatment" placeholder={t.reviewTreatment} required/><textarea className="field mt-3" name="risks" placeholder={t.reviewRisks} required/><button className="btn-primary mt-2">{t.saveReview}</button></form>}{isDoctor&&draft&&<button className="btn-secondary mt-3" onClick={()=>void mutate(`/doctor/cases/${c.id}/reviews/${draft.id}/approve`)}>{t.approveReview}</button>}</Panel>
  {renderWorkflow&&<div className={dim?"pointer-events-none opacity-50":""}><CaseWorkflowActions locale={locale} role={role} caseSummary={c} mutate={mutate} doctors={doctors} categories={categories}/></div>}
  <Panel title={t.proposal} wide>{value.proposal?<ProposalCard locale={locale} proposal={value.proposal}/>:<Empty/>}{showActions&&<div className={dim?"pointer-events-none opacity-50":""}><RoleActions role={role} t={t} c={c} proposal={value.proposal} approvedReview={approved} mutate={mutate}/></div>}</Panel>
  <Panel title={t.timeline}>{value.timeline.length?<ol className="space-y-4">{value.timeline.map(event=><li key={`${event.status}-${event.occurredAt}`} className="flex gap-3"><span className="mt-1.5 h-3 w-3 flex-none rounded-full bg-brand-500 ring-4 ring-brand-100"/><div><strong>{statusLabel(event.status,locale)}</strong><p className="text-xs text-ink-500">{new Intl.DateTimeFormat(locale,{dateStyle:"medium",timeStyle:"short"}).format(new Date(event.occurredAt))}</p></div></li>)}</ol>:<Empty/>}</Panel>
  <div className="mt-6 grid gap-6 xl:grid-cols-2">
   <Panel title={t.tasks}>{value.tasks.length?value.tasks.map(task=><div key={task.id}><strong>{task.title}</strong><p className="text-sm">{task.status} · {task.priority}</p></div>):<Empty/>}</Panel>
   <Panel title={t.messages}>{value.messages.map(m=><div key={m.id} className="rounded-lg bg-brand-50 p-3"><strong className="text-sm">{m.senderRole}</strong><p>{m.body}</p></div>)}{(["patient","doctor"].includes(role)||(role==="coordinator"&&showActions))&&<form onSubmit={event=>{event.preventDefault();const form=event.currentTarget;const data=new FormData(form);void mutate(`/${role}/cases/${c.id}/messages`,{threadType:role==="doctor"?"COORDINATOR_DOCTOR":"PATIENT_COORDINATOR",body:data.get("message"),language:locale,internalOnly:role!=="patient"}).then(()=>form.reset());}}><textarea className="field mt-3" name="message" aria-label={t.message} required/><button disabled={busy} className="btn-primary mt-2">{t.send}</button></form>}</Panel>
  </div>
 </div>;
}

function RoleActions({role,t,c,proposal,approvedReview,mutate}:{role:RoleKey;t:typeof copy.en;c:CaseView;proposal?:Proposal;approvedReview?:Review;mutate:Mutate}){
 if(role==="coordinator"&&approvedReview&&!proposal)return <form className="mt-4 grid gap-3 md:grid-cols-2" onSubmit={event=>{event.preventDefault();const data=new FormData(event.currentTarget);void mutate(`/coordinator/cases/${c.id}/proposals`,{clinicalReviewId:approvedReview.id,language:c.preferredLanguage,currency:"USD",includedServices:String(data.get("item")),excludedServices:"Services not explicitly included",paymentTerms:"Payment schedule to be confirmed",refundTerms:"Subject to provider terms",disclaimers:"This proposal is not procedure-specific medical consent.",validUntil:new Date(Date.now()+14*86400000).toISOString(),items:[{category:"MEDICAL",description:data.get("item"),quantity:1,unitPrice:Number(data.get("price")),optional:false,sortOrder:0}]});}}><input className="field" name="item" placeholder={t.item} required/><input className="field" name="price" type="number" min="0" step="0.01" placeholder={t.price} required/><button className="btn-primary md:col-span-2">{t.createProposal}</button></form>;
 if(role==="coordinator"&&proposal?.status==="FINANCE_APPROVED")return <button className="btn-primary mt-4" onClick={()=>void mutate(`/coordinator/cases/${c.id}/proposals/${proposal.versionId}/release`)}>{t.release}</button>;
 if(role==="operations"&&proposal?.status==="CLINICALLY_APPROVED")return <button className="btn-primary mt-4" onClick={()=>void mutate(`/operations/cases/${c.id}/proposals/${proposal.versionId}/complete`,"Operational plan confirmed")}>{t.operationsComplete}</button>;
 if(role==="finance"&&proposal?.status==="OPERATIONS_COMPLETED")return <button className="btn-primary mt-4" onClick={()=>void mutate(`/finance/cases/${c.id}/proposals/${proposal.versionId}/approve`)}>{t.financeApprove}</button>;
 if(role==="patient"&&proposal&&["RELEASED","VIEWED"].includes(proposal.status))return <div className="mt-4 flex flex-wrap gap-2"><button className="btn-primary" onClick={()=>void mutate(`/patient/cases/${c.id}/proposals/${proposal.versionId}/decision`,{decision:"ACCEPTED",selectedOptionalItemIds:[]})}>{t.accept}</button><button className="btn-secondary" onClick={()=>void mutate(`/patient/cases/${c.id}/proposals/${proposal.versionId}/decision`,{decision:"REVISION_REQUESTED",selectedOptionalItemIds:[],comment:"Please revise the proposal"})}>{t.revise}</button><button className="btn-secondary" onClick={()=>void mutate(`/patient/cases/${c.id}/proposals/${proposal.versionId}/decision`,{decision:"DECLINED",selectedOptionalItemIds:[]})}>{t.decline}</button></div>;
 return null;
}
function ProposalCard({locale,proposal}:{locale:Locale;proposal:Proposal}){const total=proposal.items.filter(i=>!i.optional).reduce((sum,i)=>sum+i.quantity*i.unitPrice,0);return <div className="rounded-xl bg-brand-50 p-5"><div className="flex justify-between gap-3"><strong>v{proposal.versionNumber} · {proposal.status}</strong><strong>{new Intl.NumberFormat(locale,{style:"currency",currency:proposal.currency??"USD"}).format(total)}</strong></div><ul className="mt-3 list-disc ps-5">{proposal.items.map(item=><li key={item.id}>{item.description} — {item.quantity} × {item.unitPrice}</li>)}</ul>{proposal.validUntil&&<p className="mt-3 text-sm">Valid until {new Intl.DateTimeFormat(locale).format(new Date(proposal.validUntil))}</p>}</div>}
function AdminForm({t,busy,mutate}:{t:typeof copy.en;busy:boolean;mutate:Mutate}){
 const[practitionerId,setPractitionerId]=useState("");
 return <div className="grid gap-6 xl:grid-cols-2">
  <form className="card space-y-4 p-6" onSubmit={event=>{event.preventDefault();const form=event.currentTarget;const data=new FormData(form);void mutate("/admin/practitioners",{legalName:data.get("name"),displayName:data.get("name"),externalSubject:data.get("subject"),specialty:data.get("specialty"),contractStatus:"PENDING",availabilityStatus:"UNAVAILABLE",expectedReviewHours:48}).then(result=>{if(result?.id){setPractitionerId(result.id);form.reset();}});}}>
   <h2 className="title">{t.adminTitle}</h2>
   <label className="block text-sm font-bold">{t.name}<input className="field mt-1" name="name" required/></label>
   <label className="block text-sm font-bold">{t.subject}<input className="field mt-1" name="subject" required/></label>
   <label className="block text-sm font-bold">{t.specialty}<input className="field mt-1" name="specialty" required/></label>
   <button disabled={busy} className="btn-primary">{t.create}</button>
  </form>
  <div className="space-y-6">
   <form className="card space-y-4 p-6" onSubmit={event=>{event.preventDefault();const form=event.currentTarget;const data=new FormData(form);void mutate(`/admin/practitioners/${practitionerId}/credentials`,{credentialType:data.get("credentialType"),referenceNumber:data.get("reference"),source:data.get("source"),expiresAt:toInstant(data.get("expires"))}).then(result=>{if(result)form.reset();});}}>
    <h2 className="title">{t.credentialTitle}</h2>
    <ProfileIdInput t={t} value={practitionerId} setValue={setPractitionerId}/>
    <label className="block text-sm font-bold">{t.credentialType}<input className="field mt-1" name="credentialType" required/></label>
    <label className="block text-sm font-bold">{t.reference}<input className="field mt-1" name="reference" required/></label>
    <label className="block text-sm font-bold">{t.source}<input className="field mt-1" name="source" required/></label>
    <label className="block text-sm font-bold">{t.expires}<input className="field mt-1" name="expires" type="date"/></label>
    <button disabled={busy||!practitionerId} className="btn-primary">{t.addCredential}</button>
   </form>
   <form className="card space-y-4 p-6" onSubmit={event=>event.preventDefault()}>
    <h2 className="title">{t.decisionTitle}</h2>
    <ProfileIdInput t={t} value={practitionerId} setValue={setPractitionerId}/>
    <label className="block text-sm font-bold">{t.rejectionReason}<textarea className="field mt-1" name="reason"/></label>
    <div className="flex flex-wrap gap-3"><button disabled={busy||!practitionerId} className="btn-primary" onClick={()=>void mutate(`/admin/practitioners/${practitionerId}/decision?approved=true`)}>{t.approvePractitioner}</button><button disabled={busy||!practitionerId} className="btn-secondary" onClick={event=>{const form=event.currentTarget.form;if(!form)return;const reason=new FormData(form).get("reason");void mutate(`/admin/practitioners/${practitionerId}/decision?approved=false&reason=${encodeURIComponent(String(reason??""))}`);}}>{t.rejectPractitioner}</button></div>
   </form>
  </div>
 </div>;
}
function ProfileIdInput({t,value,setValue}:{t:typeof copy.en;value:string;setValue:(value:string)=>void}){return <label className="block text-sm font-bold">{t.profileId}<input className="field mt-1" value={value} onChange={event=>setValue(event.target.value)} pattern="[0-9a-fA-F-]{36}" required/></label>}
function toInstant(value:FormDataEntryValue|null){return value?new Date(`${value}T23:59:59Z`).toISOString():null;}
function Panel({title,children,wide=false}:{title:string;children:React.ReactNode;wide?:boolean}){return <section className={`card mt-6 p-5 ${wide?"":""}`}><h3 className="title mb-4">{title}</h3><div className="space-y-3">{children}</div></section>}
function Empty(){return <p className="text-ink-500">—</p>}
function formatBytes(bytes:number){if(!bytes)return "0 B";const units=["B","KB","MB","GB"];const i=Math.min(units.length-1,Math.floor(Math.log(bytes)/Math.log(1024)));return `${(bytes/Math.pow(1024,i)).toFixed(i?1:0)} ${units[i]}`;}
const STATUS_LABELS:Record<string,{en:string;ar:string}>={RECEIVED:{en:"Received",ar:"تم الاستلام"},INTAKE_REVIEW:{en:"Intake review",ar:"مراجعة الاستقبال"},INFORMATION_REQUIRED:{en:"Information required",ar:"مطلوب معلومات"},READY_FOR_CONSULTANT:{en:"Ready for consultant",ar:"جاهزة للاستشاري"},CONSULTANT_ASSIGNMENT_PENDING:{en:"Assigned to consultant",ar:"تم التعيين للاستشاري"},CONSULTANT_REVIEW:{en:"Consultant review",ar:"مراجعة الاستشاري"},CLINICAL_RECOMMENDATION_READY:{en:"Recommendation ready",ar:"التوصية جاهزة"},PROPOSAL_PREPARATION:{en:"Proposal preparation",ar:"تحضير المقترح"},PROPOSAL_INTERNAL_APPROVAL:{en:"Internal approval",ar:"الموافقة الداخلية"},PROPOSAL_READY:{en:"Proposal ready",ar:"المقترح جاهز"},PATIENT_DECISION:{en:"Awaiting patient decision",ar:"بانتظار قرار المريض"},REVISION_REQUESTED:{en:"Revision requested",ar:"مطلوب تعديل"},ACCEPTED:{en:"Accepted",ar:"مقبول"},DECLINED:{en:"Declined",ar:"مرفوض"},TRAVEL_COORDINATION:{en:"Travel coordination",ar:"تنسيق السفر"},ARRIVAL_CONFIRMED:{en:"Arrival confirmed",ar:"تم تأكيد الوصول"},TREATMENT_IN_PROGRESS:{en:"Treatment in progress",ar:"العلاج جارٍ"},DISCHARGED:{en:"Discharged",ar:"تم الخروج"},FOLLOW_UP:{en:"Follow-up",ar:"المتابعة"},CLOSED:{en:"Closed",ar:"مغلقة"},CANCELLED:{en:"Cancelled",ar:"ملغاة"}};
function statusLabel(value:string,locale:Locale){return STATUS_LABELS[value]?.[locale]??value.replaceAll("_"," ");}
function Status({value,locale="en"}:{value:string;locale?:Locale}){return <span className="rounded-full bg-brand-100 px-3 py-1 text-sm font-bold text-brand-800">{statusLabel(value,locale)}</span>}
