"use client";

import { useCallback, useEffect, useState } from "react";
import type { Locale } from "@/lib/i18n";
type Api=<T,>(path:string,init?:RequestInit)=>Promise<T>;
type StaffFunction="COORDINATOR"|"OPERATIONS"|"FINANCE";
type Member={subject:string;name:string;role:string;staffFunction:StaffFunction;leadSubject?:string;email?:string;accountStatus:"INVITED"|"ACTIVE"|"DISABLED";invitedAt?:string};

const functions:StaffFunction[]=["COORDINATOR","OPERATIONS","FINANCE"];

export function ReportingTeam({api,locale,editable}:{api:Api;locale:Locale;editable:boolean}) {
  const [members,setMembers]=useState<Member[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(""),[saved,setSaved]=useState("");
  const [activeFunction,setActiveFunction]=useState<StaffFunction>("COORDINATOR");
  const ar=locale==="ar";
  const label=(value:StaffFunction)=>value==="COORDINATOR"?(ar?"التنسيق":"Coordination"):value==="OPERATIONS"?(ar?"العمليات":"Operations"):(ar?"المالية":"Finance");
  const load=useCallback(async()=>{setLoading(true);setError("");try{setMembers(await api<Member[]>("/admin/staff-teams"));}catch(e){setError(e instanceof Error?e.message:"Unable to load staff teams");}finally{setLoading(false);}},[api]);
  useEffect(()=>{void load();},[load]);
  const visible=members.filter(member=>member.staffFunction===activeFunction);
  const leads=visible.filter(member=>member.role.endsWith("_LEAD"));
  const assign=async(subject:string,leadSubject:string)=>{setSaving(subject);setSaved("");setError("");try{await api(`/admin/staff-teams/${encodeURIComponent(subject)}`,{method:"PUT",body:JSON.stringify({leadSubject:leadSubject||null})});setMembers(current=>current.map(member=>member.subject===subject?{...member,leadSubject:leadSubject||undefined}:member));setSaved(subject);}catch(e){setError(e instanceof Error?e.message:"Unable to update the team");}finally{setSaving("");}};
  const accountAction=async(member:Member,action:"resend-invite"|"disable"|"enable")=>{if(action==="disable"&&!window.confirm(ar?`تعطيل وصول ${member.name}؟ سيتم إنهاء قدرته على تسجيل الدخول.`:`Disable ${member.name}’s access? They will no longer be able to sign in.`))return;setSaving(member.subject);setSaved("");setError("");try{await api(`/admin/staff/${encodeURIComponent(member.subject)}/${action}${action==="resend-invite"?`?locale=${locale}`:""}`,{method:"POST"});await load();setSaved(member.subject);}catch(e){setError(e instanceof Error?e.message:"Unable to update the account");}finally{setSaving("");}};
  const accountLabel=(status:Member["accountStatus"])=>status==="ACTIVE"?(ar?"نشط":"Active"):status==="DISABLED"?(ar?"معطّل":"Disabled"):(ar?"بانتظار التفعيل":"Invitation pending");
  const accountTone=(status:Member["accountStatus"])=>status==="ACTIVE"?"border-emerald-200 bg-emerald-50 text-emerald-800":status==="DISABLED"?"border-slate-200 bg-slate-100 text-slate-700":"border-amber-200 bg-amber-50 text-amber-900";
  return <section className="card mt-6 overflow-hidden"><div className="border-b border-line bg-brand-50 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="title">{ar?"فرق الموظفين والقادة":"Staff teams & leads"}</h2><p className="mt-2 max-w-3xl text-sm text-ink-500">{ar?"نظّم موظفي التنسيق والعمليات والمالية تحت قادتهم. يمكن وجود عدة قادة في كل قسم، ولكل قائد فريق مستقل.":"Organize Coordination, Operations, and Finance staff under their leads. Each function can have multiple leads with separate teams."}</p></div><span className="rounded-full bg-white px-3 py-1 text-xs font-bold text-brand-800">{members.length} {ar?"موظف":"staff"}</span></div></div>
    <div role="tablist" aria-label={ar?"أقسام الموظفين":"Staff functions"} className="flex flex-wrap gap-1 border-b border-line px-5 pt-3">{functions.map(item=><button type="button" role="tab" aria-selected={activeFunction===item} key={item} onClick={()=>{setActiveFunction(item);setSaved("");setError("");}} className={`min-h-11 border-b-[3px] px-4 text-sm font-bold ${activeFunction===item?"border-brand-700 text-brand-800":"border-transparent text-ink-500"}`}>{label(item)} <span className="ms-1 rounded-full bg-brand-100 px-2 py-0.5 text-xs">{members.filter(member=>member.staffFunction===item).length}</span></button>)}</div>
    <div className="p-5">
    {loading&&<p role="status" className="mt-4">{ar?"جارٍ التحميل…":"Loading team…"}</p>}
    {error&&<p role="alert" className="mt-4 text-alert-800">{error} <button className="link-cta" onClick={()=>void load()}>{ar?"إعادة المحاولة":"Retry"}</button></p>}
    {!loading&&!visible.length&&!error&&<p className="rounded-xl border border-dashed border-line-strong bg-mist p-4 text-sm">{ar?`أضف حسابات ${label(activeFunction)} أولًا.`:`Add ${label(activeFunction)} accounts to start building teams.`}</p>}
    {!loading&&visible.length>0&&<><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{leads.map(lead=>{const direct=visible.filter(member=>member.leadSubject===lead.subject);return <article key={lead.subject} className="rounded-xl border border-line bg-white p-4"><div className="flex items-center justify-between gap-3"><div><p className="font-bold text-ink-900">{lead.name}</p><p className="text-xs text-brand-700">{ar?"قائد فريق":"Team lead"}</p></div><span className="rounded-full bg-brand-100 px-2.5 py-1 text-xs font-bold text-brand-800">{direct.length}</span></div><div className="mt-3 flex min-h-7 flex-wrap gap-1.5">{direct.length?direct.map(member=><span key={member.subject} className="rounded-full bg-mist px-2.5 py-1 text-xs text-ink-700">{member.name}</span>):<span className="text-xs text-ink-500">{ar?"لا يوجد أعضاء بعد":"No members yet"}</span>}</div></article>})}{leads.length===0&&<div className="rounded-xl border border-dashed border-line-strong bg-mist p-4 text-sm text-ink-600">{ar?"حوّل حسابًا إلى قائد فريق لبدء توزيع الموظفين.":"Promote an account to Team lead before assigning staff."}</div>}</div>
      <div className="mt-5 overflow-hidden rounded-xl border border-line"><ul className="divide-y divide-line">{visible.map(member=><li key={member.subject} className="grid gap-4 px-4 py-4 lg:grid-cols-[minmax(0,1.2fr)_minmax(10rem,0.7fr)_auto] lg:items-center"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="truncate text-sm font-bold text-ink-900">{member.name}</p><span className={`rounded-full border px-2.5 py-0.5 text-xs font-bold ${accountTone(member.accountStatus)}`}>{accountLabel(member.accountStatus)}</span></div><p className="mt-1 truncate text-xs text-ink-500">{member.email??(ar?"حساب قديم — لا يوجد بريد مسجّل":"Legacy account — no email recorded")} · {member.role.endsWith("_LEAD")?(ar?"قائد فريق":"Team lead"):(ar?"موظف":"Staff")}{saved===member.subject?<span role="status" className="ms-2 font-bold text-brand-700">✓ {ar?"تم الحفظ":"Saved"}</span>:null}</p></div><select aria-label={`${ar?"قائد":"Lead"}: ${member.name}`} className="field py-2 text-sm" value={member.leadSubject??""} disabled={!editable||saving===member.subject||leads.length===0||member.accountStatus==="DISABLED"} onChange={event=>void assign(member.subject,event.target.value)}><option value="">{ar?"بدون قائد":"Unassigned"}</option>{leads.filter(lead=>lead.subject!==member.subject&&lead.accountStatus==="ACTIVE").map(lead=><option key={lead.subject} value={lead.subject}>{lead.name}</option>)}</select>{editable&&<div className="flex flex-wrap gap-2 lg:justify-end">{member.accountStatus==="INVITED"&&<button type="button" className="btn-secondary !px-3 !py-2 text-xs" disabled={saving===member.subject} onClick={()=>void accountAction(member,"resend-invite")}>{ar?"إعادة إرسال الدعوة":"Resend invite"}</button>}{member.accountStatus==="DISABLED"?<button type="button" className="btn-secondary !px-3 !py-2 text-xs" disabled={saving===member.subject} onClick={()=>void accountAction(member,"enable")}>{ar?"إعادة التفعيل":"Restore access"}</button>:<button type="button" className="btn-secondary !px-3 !py-2 text-xs" disabled={saving===member.subject} onClick={()=>void accountAction(member,"disable")}>{ar?"تعطيل الوصول":"Disable access"}</button>}</div>}</li>)}</ul></div>
      {!editable&&<p className="mt-4 text-xs text-ink-500">{ar?"للقراءة فقط. مسؤول النظام هو من يغيّر توزيع الفرق.":"Read only. A system administrator manages team assignments."}</p>}</>}
    </div>
  </section>;
}

export function PractitionerDirectory({api,locale,value,onChange}:{api:Api;locale:Locale;value:string;onChange:(id:string)=>void}) {
  const [items,setItems]=useState<{id:string;displayName?:string;specialty?:string;email?:string;accountStatus?:string}[]>([]),[search,setSearch]=useState(""),[error,setError]=useState("");
  useEffect(()=>{let alive=true;void api<typeof items>("/admin/practitioners").then(rows=>{if(alive)setItems(rows);}).catch(e=>{if(alive)setError(e instanceof Error?e.message:"Unable to load consultants");});return()=>{alive=false;};},[api]);
  return <div className="space-y-3">{error&&<p role="alert" className="text-sm text-alert-800">{error}</p>}<label className="block text-sm font-semibold">{locale==="ar"?"البحث عن استشاري موجود":"Find an existing consultant"}<input type="search" className="field mt-2" value={search} onChange={e=>setSearch(e.target.value)}/></label><label className="block text-sm font-semibold">{locale==="ar"?"الاستشاري":"Consultant"}<select className="field mt-2" value={value} onChange={e=>onChange(e.target.value)}><option value="">{locale==="ar"?"اختر الاستشاري":"Select consultant"}</option>{items.filter(item=>item.id===value||`${item.displayName??""} ${item.specialty??""} ${item.email??""}`.toLowerCase().includes(search.toLowerCase())).map(item=><option key={item.id} value={item.id}>{item.displayName??item.id}{item.specialty?` · ${item.specialty}`:""}{item.accountStatus?` · ${item.accountStatus}`:""}</option>)}</select></label></div>;
}

type ConsultantAccount={id:string;displayName?:string;specialty?:string;careCategory?:string;credentialingStatus?:string;email?:string;accountStatus:"INVITED"|"ACTIVE"|"DISABLED"};
export function ConsultantAccounts({api,locale,editable}:{api:Api;locale:Locale;editable:boolean}){
 const[items,setItems]=useState<ConsultantAccount[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState("");const ar=locale==="ar";
 const load=useCallback(async()=>{setLoading(true);setError("");try{setItems(await api<ConsultantAccount[]>("/admin/practitioners"));}catch(e){setError(e instanceof Error?e.message:"Unable to load consultant accounts");}finally{setLoading(false);}},[api]);useEffect(()=>{void load();},[load]);
 const act=async(item:ConsultantAccount,action:"resend-invite"|"disable"|"enable")=>{if(action==="disable"&&!window.confirm(ar?`تعطيل وصول ${item.displayName}؟`:`Disable ${item.displayName}’s access?`))return;setBusy(item.id);setError("");setNotice("");try{await api(`/admin/practitioners/${item.id}/${action}${action==="resend-invite"?`?locale=${locale}`:""}`,{method:"POST"});setNotice(ar?"تم تحديث الحساب.":"Account updated.");await load();}catch(e){setError(e instanceof Error?e.message:"Unable to update consultant account");}finally{setBusy("");}};
 const label=(s:string)=>s==="ACTIVE"?(ar?"نشط":"Active"):s==="DISABLED"?(ar?"معطّل":"Disabled"):(ar?"بانتظار التفعيل":"Invitation pending");
 return <section className="card mt-6 overflow-hidden"><header className="border-b border-line bg-brand-50 p-5"><h2 className="title">{ar?"وصول الاستشاريين":"Consultant access"}</h2><p className="mt-2 text-sm text-ink-500">{ar?"تابع تفعيل الدعوات بصورة منفصلة عن اعتماد المؤهلات الطبية.":"Track account activation separately from clinical credential verification."}</p></header><div className="p-5">{loading&&<p role="status">{ar?"جارٍ التحميل…":"Loading…"}</p>}{error&&<p role="alert" className="mb-3 text-sm text-alert-800">{error}</p>}{notice&&<p role="status" className="mb-3 text-sm text-brand-800">✓ {notice}</p>}<div className="grid gap-3 md:grid-cols-2">{items.map(item=><article key={item.id} className="rounded-xl border border-line p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-bold">{item.displayName}</p><p className="mt-1 text-xs text-ink-500">{item.email??(ar?"حساب قديم":"Legacy account")} · {item.specialty}</p></div><span className="status-badge">{label(item.accountStatus)}</span></div><div className="mt-3 flex flex-wrap items-center justify-between gap-2 border-t border-line pt-3"><span className="text-xs text-ink-500">{ar?"الاعتماد":"Credentialing"}: {item.credentialingStatus}</span>{editable&&<div className="flex gap-2">{item.accountStatus==="INVITED"&&<button type="button" className="btn-secondary !px-3 !py-1.5 text-xs" disabled={busy===item.id} onClick={()=>void act(item,"resend-invite")}>{ar?"إعادة الدعوة":"Resend"}</button>}{item.accountStatus==="DISABLED"?<button type="button" className="btn-secondary !px-3 !py-1.5 text-xs" disabled={busy===item.id} onClick={()=>void act(item,"enable")}>{ar?"إعادة التفعيل":"Restore"}</button>:<button type="button" className="btn-secondary !px-3 !py-1.5 text-xs" disabled={busy===item.id} onClick={()=>void act(item,"disable")}>{ar?"تعطيل":"Disable"}</button>}</div>}</div></article>)}</div></div></section>;
}

type Identity={id:string;subjectType:string;status:string;documentType?:string;issuingCountry?:string;documentReferenceMasked?:string;requestedAt:string;method?:string};
export function IdentityReviewQueue({api,locale}:{api:Api;locale:Locale}) {
  const [items,setItems]=useState<Identity[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
  const ar=locale==="ar";
  const load=useCallback(async()=>{setLoading(true);setError("");try{setItems(await api<Identity[]>("/identity-review/queue"));}catch(e){setError(e instanceof Error?e.message:"Unable to load identity reviews");}finally{setLoading(false);}},[api]);
  useEffect(()=>{void load();},[load]);
  return <section className="space-y-4" aria-label={ar?"طلبات التحقق":"Verification requests"}>
    {loading&&<p role="status">{ar?"جارٍ التحميل…":"Loading requests…"}</p>}{error&&<p role="alert" className="card p-4 text-alert-800">{error} <button className="link-cta" onClick={()=>void load()}>{ar?"إعادة المحاولة":"Retry"}</button></p>}{notice&&<p role="status" className="card p-4 text-brand-700">{notice}</p>}
    {!loading&&!items.length&&!error&&<div className="card p-8"><h2 className="title">{ar?"لا توجد طلبات بانتظار المراجعة":"No verification requests waiting"}</h2><p className="mt-2 text-sm text-ink-500">{ar?"ستظهر الطلبات الجديدة هنا.":"New requests will appear here."}</p></div>}
    {items.map(item=><article key={item.id} className="card p-5"><div className="flex flex-wrap justify-between gap-3"><h2 className="title">{item.subjectType==="PATIENT"?ar?"هوية المريض":"Patient identity":ar?"هوية الممثل":"Representative identity"}</h2><span className="status-badge">{ar?"بانتظار المراجعة":"Awaiting review"}</span></div><dl className="mt-4 grid gap-3 sm:grid-cols-3">{[[ar?"المستند":"Document",item.documentType],[ar?"بلد الإصدار":"Issuing country",item.issuingCountry],[ar?"مرجع المستند":"Document reference",item.documentReferenceMasked]].filter(([,value])=>value).map(([label,value])=><div key={label}><dt className="text-xs text-ink-500">{label}</dt><dd className="text-sm font-semibold" dir="auto">{value}</dd></div>)}</dl>
      <p className="mt-4 text-sm text-ink-500">{ar?"سجّل القرار بعد مراجعة دليل الهوية عبر الإجراء المعتمد.":"Record a decision after reviewing identity evidence through the approved process."}</p>
      <form className="mt-4 space-y-3" onSubmit={async event=>{event.preventDefault();const data=new FormData(event.currentTarget);setBusy(true);setError("");try{await api(`/identity-review/${item.id}/decision`,{method:"POST",body:JSON.stringify({decision:data.get("decision"),reason:data.get("reason")})});await load();setNotice(ar?"تم تسجيل القرار.":"Decision recorded.");}catch(e){setError(e instanceof Error?e.message:"Unable to record decision");}finally{setBusy(false);}}}>
        <label className="block text-sm font-semibold">{ar?"القرار":"Decision"}<select name="decision" className="field mt-2" required defaultValue=""><option value="" disabled>{ar?"اختر القرار":"Select decision"}</option><option value="VERIFY">{ar?"تم التحقق":"Verify identity"}</option><option value="REJECT">{ar?"لم يتم التحقق":"Reject verification"}</option></select></label>
        <label className="block text-sm font-semibold">{ar?"سبب القرار":"Reason for decision"}<textarea name="reason" className="field mt-2" required maxLength={2000}/></label><button className="btn-primary" disabled={busy}>{ar?"تسجيل القرار":"Record decision"}</button>
      </form></article>)}
  </section>;
}
